force-app/main/default/objects/Case/fields/Actual_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>VHF-1712</description>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Property</description>
    <label>Property ID</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Property_Valuation_Date__c.field-meta.xml
<CustomField>
    <fullName>Property_Valuation_Date__c</fullName>
    <description>Property Valuation Date</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Property Valuation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEI_OLD__c.field-meta.xml
<CustomField>
    <fullName>SEI_OLD__c</fullName>
    <description>SEI(old)</description>
    <label>SEI (old)</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEM_new__c.field-meta.xml
<CustomField>
    <fullName>SEM_new__c</fullName>
    <description>SEM(new)</description>
    <label>SEM (new)</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEM_OLD__c.field-meta.xml
<CustomField>
    <fullName>SEM_OLD__c</fullName>
    <description>SEM(old)</description>
    <label>SEM (old)</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Actual_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shared_Equity_Interest__c.field-meta.xml
<CustomField>
    <fullName>Shared_Equity_Interest__c</fullName>
    <description>SEI =(SEM/(min(MV,AP)) -(P/LMV) )
SEM = Shared Equity Money
MV – Market value of the property
AP – Initial Acquisition Price
P – Amount to be paid by the applicant . Captured from the Annual Review or Windfall gain notification
LMV – Higher of AP or Market Value of the property (from VGV valuations)</description>
    <label>Shared Equity Interest</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shared_Equity_Money__c.field-meta.xml
<CustomField>
    <fullName>Shared_Equity_Money__c</fullName>
    <description>State&apos;s equity in the Property</description>
    <label>Shared Equity Money</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Stores the payment details that a participant need to make as part of post settlement process</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PID-{00000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Auto-populated when payment record is created</description>
    <label>Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Windfall Gains, Voluntary Payments, Income Threshold Exceeded, Final Payment, Early Payment</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Flag_Current_Payment_Regenerated_Record__c.field-meta.xml
<CustomField>
    <fullName>Flag_Current_Payment_Regenerated_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Please do not use this field for reporting purpose. Only for backend logic purpose</description>
    <label>Flag_Current_Payment_Regenerated_Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/GatewayResultCode__c.field-meta.xml
<CustomField>
    <fullName>GatewayResultCode__c</fullName>
    <description>Resulting transaction or error code returned by the payment gateway after the request</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Gateway Result Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/GatewayResultCodeDescription__c.field-meta.xml
<CustomField>
    <fullName>GatewayResultCodeDescription__c</fullName>
    <description>Description of the Gateway&apos;s result code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Gateway Result Code Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Parent_Payment__c.field-meta.xml
<CustomField>
    <fullName>Parent_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Auto-linked</description>
    <label>Parent Payment ID</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Regenerated__c.field-meta.xml
<CustomField>
    <fullName>Payment_Regenerated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Regenerated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Primary_Participant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Auto-linked when payment record is created</description>
    <label>Primary Participant Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Auto-linked when payment record is created</description>
    <label>Property</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Date__c</fullName>
    <description>Auto-populated when status is updated to payment requested</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Requested Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Shared_Equity_Interest__c.field-meta.xml
<CustomField>
    <fullName>Shared_Equity_Interest__c</fullName>
    <formula>Property__r.Shared_Equity_Interest__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shared Equity Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Updated by SRO Officer</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Payment Registered</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Request Expired</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
                <isActive>false</isActive>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Requested</fullName>
                <isActive>false</isActive>
                <label>Requested</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentRegenerationRequest.cls
/*******************************************************************************************
* @Name         Payment Regeneration Request (VHF-2979)
* @Author       Lavanya Kavuri
* @Date         09/12/2021
* @Description  This class is used for Payment Regeneration Request Lightning web component
*******************************************************************************************/ 
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*  1.0              Lavanya Kavuri     09/12/2021          Created      
*  1.1              Lavanya Kavuri      01/02/2022          Updated. AC9 Updated, VHF-4154 
*  1.2              Lavanya Kavuri      11/02/2022          Bugs: VHF-4652, VHF-4653, VHF-4655, VHF-4656                                           
*******************************************************************************************/
public with sharing class PaymentRegenerationRequest {
    
    public static String PAYMENT_ERROR = 'Active payment exists for the property. Cannot create a new payment request.';
    //public static String PAYMENT_ERROR = 'Active payment exists for the property. Cannot create a new payment request';
    public static String SET_NOT_MATCHED_ERROR = 'SEI and SEM has been updated. Create a new case and request payment.';
    public static String VALUATION_ERROR = 'Property valuation is not valid. Create a new case and request payment.';
   
    /*
    *Method: Validate Payment Regeneration Request 
    * @param: recordId
    * @output: Map<String,String> response
    */
    @AuraEnabled
    public static string validateRequest(String paymentRecId){

        Profile sysAdminProfile = [Select Id, Name from Profile where Name = 'System Administrator'];
        Id currentUserProfileId = UserInfo.getProfileId();

        system.debug('record Id coming=' + paymentRecId);
        Map<String,String> responseMap = new Map<String,String>();
        List<String> errorList = new List<String>();

            Payment__c paymentRecord = getPaymentRecord(paymentRecId);

            System.debug('payment record=' + paymentRecord);
            if(paymentRecord != null)
            {

                //is it System admin regenerating the payment record? 
                if(sysAdminProfile.Id == currentUserProfileId)
                {
                    //There is an error in the Payment Processing
                    if(paymentRecord.GatewayResultCode__c != null || paymentRecord.GatewayResultCodeDescription__c != null)
                    {
                        if(paymentRecord.Status__c == 'Created' || paymentRecord.Status__c == 'Payment Registered')
                        {
                            errorList.addAll(doValidations(paymentRecord));
                        }
                        else 
                        {
                            errorList.add('Invalid Request');
                        }
                    }
                    else 
                    {
                        errorList.add('Invalid Request');
                    }
                }
                else 
                {
                    errorList.addAll(doValidations(paymentRecord));
                }
                
            }
            else {
                //Something went wrong in getting the related payment record context. Log an error
                AuraHandledException e = new AuraHandledException('Something went wrong. Please try again later.');
                e.setMessage('Something went wrong. Please try again later.');
                throw e;
            }

            //We have some validation errors. append to response Map
            if(!errorList.isEmpty())
            {
                responseMap.put('errors', JSON.serialize(errorList));
            }
            //No validation errors, send an empty errorlist.
            else 
            {
                responseMap.put('errors', '');
            }  

        return JSON.serialize(responseMap);
    }



    /*
    *Method: Create Payment Regeneration Request 
    * @param: recordId
    * @output: Map<String,String> response
    */
    @AuraEnabled
    public static Payment__c createPaymentRequest(String paymentRecId, String comments) {
        String paymentNumber;
        Payment__c newPaymentRec = new Payment__c();
        Payment__c existingPaymentRecord = getPaymentRecord(paymentRecId);

        newPaymentRec.Case__c = existingPaymentRecord.Case__c;
        newPaymentRec.Property__c = existingPaymentRecord.Property__c;
        newPaymentRec.Primary_Participant__c = existingPaymentRecord.Primary_Participant__c;
        //newPaymentRec.Status__c = 'Payment Registered';
        newPaymentRec.Status__c = 'Created';// Changed to Created status as discussed
        newPaymentRec.Comments__c = existingPaymentRecord.Comments__c;
        newPaymentRec.OwnerId = existingPaymentRecord.OwnerId;
        newPaymentRec.Parent_Payment__c = existingPaymentRecord.Id;
        newPaymentRec.Requested_Date__c=System.today();
        newPaymentRec.Amount__c = existingPaymentRecord.Amount__c;
        newPaymentRec.ByPassValidation__c = true;
        newPaymentRec.Flag_Current_Payment_Regenerated_Record__c=true;
        insert newPaymentRec;

        //Need to get the inserted Payment record again, for the Payment Number 
        Payment__c newPayment = getPaymentRecord(newPaymentRec.Id);

        existingPaymentRecord.ByPassValidation__c = true;
        existingPaymentRecord.Payment_Regenerated__c = true;

        update existingPaymentRecord;

        return newPayment;
    }

    public static Payment__c getPaymentRecord(String paymentRecId) 
    {
        Payment__c paymentRecord = [Select 
                                        Id, Status__c, Payment_Regenerated__c, OwnerId, Comments__c, Name, Case__r.Property_Valuation_Date__c, 
                                        Case__r.SEI_OLD__c,Case__r.SEM_OLD__c, Case__r.SEM_new__c, Property__c, 
                                        GatewayResultCode__c, GatewayResultCodeDescription__c,
                                        Primary_Participant__c,Amount__c,
                                        Property__r.Shared_Equity_Interest__c, 
                                        Property__r.Shared_Equity_Money__c, 
                                        Property__r.Actual_Settlement_Date__c
                                        from Payment__c 
                                        where Id=: paymentRecId
                                        ];
        
        return paymentRecord;
    }

    public static List<String> doValidations(Payment__c paymentRecord)
    {

        List<String> errorMsgList = new List<String>();

        //Check one -> Is Payment regenerated once ? 
        if(paymentRecord.Payment_Regenerated__c) 
        {
            AuraHandledException e = new AuraHandledException('Payment has already been regenerated for this Payment Record.');
            e.setMessage('Payment has already been regenerated for this Payment Record.');
            throw e;
        }
        //No regenerated payment request, proceed to check validations.
        else 
        {
            //Get the list of all Payment Records to check for any active payments in progress.
            List<Payment__c> paymentsList = [Select Id, Status__c 
                                                from Payment__c 
                                                where 
                                                Property__c =: paymentRecord.Property__c
                                                and 
                                                Status__c not in ('Cancelled', 'Request Expired', 'Payment Received')
                                            ];

            //AC1 - Payment Not in Cancelled or Request Expired Status, throw an error
            if(!paymentsList.isEmpty())
            {
                String paymentError;
                for(Payment__c payment: paymentsList)
                {
                    System.debug('Payment Id=' + payment.Id);
                    System.debug('Payment status=' + payment.Status__c);
                    
                    System.debug('why is it coming here?');
                    //If any active payments found, validation failed, add the error message to validation errors.
                    paymentError = PAYMENT_ERROR;
                    
                }
                if(paymentError.length() > 0)
                {
                    errorMsgList.add(paymentError);
                }
                
            }

            //AC2 - Compare SEI SEM Values 
            if(paymentRecord.Case__r.SEI_OLD__c != paymentRecord.Property__r.Shared_Equity_Interest__c || paymentRecord.Case__r.SEM_OLD__c != paymentRecord.Property__r.Shared_Equity_Money__c)
            {
                //SEI and SEM values are not matched from case and property, add the error message to validation errors.
                String paymentError = SET_NOT_MATCHED_ERROR;
                errorMsgList.add(paymentError);
            }

            //AC9 - Valuation not more than 90 days 
            // If Valuation date is null, then check if the Actual Settlement Date on Property is not more than 90 days
            Integer daysBetween;
            if(paymentRecord.Case__r.Property_Valuation_Date__c != null)
            {
                Date valuationDate = paymentRecord.Case__r.Property_Valuation_Date__c;
                Date todaysDate = System.today();
                daysBetween = valuationDate.daysBetween(todaysDate);
                system.debug('days between=' + daysBetween);
            }

            if(paymentRecord.Case__r.Property_Valuation_Date__c == null && paymentRecord.Property__r.Actual_Settlement_Date__c != null)
            {
                Date settlementDate = paymentRecord.Property__r.Actual_Settlement_Date__c;
                Date todaysDate = System.today();
                daysBetween = settlementDate.daysBetween(todaysDate);
                system.debug('days between=' + daysBetween);
            }

            if(daysBetween > 90)
            {
                //Valution out of date, add the error message to validation errors.
                String paymentError = VALUATION_ERROR;
                errorMsgList.add(paymentError);
            }
        }

        return errorMsgList;
    }
}