force-app/main/default/objects/Case/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>VHF-1712</description>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Stores the payment details that a participant need to make as part of post settlement process</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PID-{00000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PaymentTriggerHelper.cls
/*
* Description: Trigger Handler for Case Object 
** Version History ** 
Created: Manish Jhingran, 20/12/2021
*/

public class PaymentTriggerHelper {
  /*
   * Reset bypass flag to false
   */
  public static void resetBypassAfterUpdate(List<Payment__c> PaymentList) {
    Set<Id> PaymentIds = new Set<Id>();
    for (Payment__c PL : PaymentList) {
      if (PL.BypassValidation__c)
        PaymentIds.add(PL.Id);
    }

    List<Payment__c> PaymentsToUpdate = [
      SELECT id, bypassvalidation__c
      FROM Payment__c
      WHERE id IN :PaymentIds
    ];

    if (!PaymentsToUpdate.isEmpty()) {
      for (Payment__c p : PaymentsToUpdate)
        p.BypassValidation__c = false;
      update PaymentsToUpdate;
    }
  }
}