force-app/main/default/objects/Case/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>VHF-1712</description>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Payment_Comments__c.field-meta.xml
<CustomField>
    <fullName>Payment_Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Payment_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Payment_Eligible__c</fullName>
    <description>Payment_Eligible</description>
    <label>Payment Eligible</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Property</description>
    <label>Property ID</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Proportionate_interest_amount__c.field-meta.xml
<CustomField>
    <fullName>Proportionate_interest_amount__c</fullName>
    <label>Proportional Interest Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Refinance_Approved__c.field-meta.xml
<CustomField>
    <fullName>Refinance_Approved__c</fullName>
    <label>Refinance Approved</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SEI_new__c.field-meta.xml
<CustomField>
    <fullName>SEI_new__c</fullName>
    <description>SEI(new)</description>
    <label>SEI (new)</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEI_OLD__c.field-meta.xml
<CustomField>
    <fullName>SEI_OLD__c</fullName>
    <description>SEI(old)</description>
    <label>SEI (old)</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEM_new__c.field-meta.xml
<CustomField>
    <fullName>SEM_new__c</fullName>
    <description>SEM(new)</description>
    <label>SEM (new)</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEM_OLD__c.field-meta.xml
<CustomField>
    <fullName>SEM_OLD__c</fullName>
    <description>SEM(old)</description>
    <label>SEM (old)</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Final_Payment.recordType-meta.xml
<RecordType>
    <fullName>Final_Payment</fullName>
    <active>true</active>
    <businessProcess>Final Payment</businessProcess>
    <label>Final Payment</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Income_Threshold_Exceeded.recordType-meta.xml
<RecordType>
    <fullName>Income_Threshold_Exceeded</fullName>
    <active>true</active>
    <businessProcess>Income Threshold Exceeded</businessProcess>
    <label>Income Threshold Exceeded</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Refinance.recordType-meta.xml
<RecordType>
    <fullName>Refinance</fullName>
    <active>true</active>
    <businessProcess>Refinance</businessProcess>
    <label>Refinance</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Voluntary_Payments.recordType-meta.xml
<RecordType>
    <fullName>Voluntary_Payments</fullName>
    <active>true</active>
    <businessProcess>Voluntary Payments</businessProcess>
    <label>Voluntary Payments</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Windfall_Gains.recordType-meta.xml
<RecordType>
    <fullName>Windfall_Gains</fullName>
    <active>true</active>
    <businessProcess>Windfall Gains</businessProcess>
    <label>Windfall Gains</label>
</RecordType>

force-app/main/default/objects/Order/fields/ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shared_Equity_Interest__c.field-meta.xml
<CustomField>
    <fullName>Shared_Equity_Interest__c</fullName>
    <description>SEI =(SEM/(min(MV,AP)) -(P/LMV) )
SEM = Shared Equity Money
MV – Market value of the property
AP – Initial Acquisition Price
P – Amount to be paid by the applicant . Captured from the Annual Review or Windfall gain notification
LMV – Higher of AP or Market Value of the property (from VGV valuations)</description>
    <label>Shared Equity Interest</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shared_Equity_Money__c.field-meta.xml
<CustomField>
    <fullName>Shared_Equity_Money__c</fullName>
    <description>State&apos;s equity in the Property</description>
    <label>Shared Equity Money</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Stores the payment details that a participant need to make as part of post settlement process</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PID-{00000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Auto-linked when payment record is created</description>
    <label>Property</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Shared_Equity_Interest__c.field-meta.xml
<CustomField>
    <fullName>Shared_Equity_Interest__c</fullName>
    <formula>Property__r.Shared_Equity_Interest__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shared Equity Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Updated by SRO Officer</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Payment Registered</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Request Expired</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
                <isActive>false</isActive>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Requested</fullName>
                <isActive>false</isActive>
                <label>Requested</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CasePaymentRequest.cls
/*******************************************************************************************
* @Name         Case Payment Request (VHF-3129, VHF-2002)
* @Author       Lavanya Kavuri
* @Date         17/12/2021
* @Description  This class is used for case payment request LWC.
*******************************************************************************************/ 
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*  1.0              Lavanya Kavuri     17/12/2021          Created  
*  1.1              Sourabh			   17/1/2022      Updated: Added 'Payment Received' as 
*													  inactive status
*  1.2              Lavanya Kavuri     28/1/2022      Added Final Payment Status - VHF-2002	
*  1.3              Lavanya Kavuri     23/03/2022     Added ITE Case Type - VHF-4312   	
*******************************************************************************************/
public with sharing class CasePaymentRequest {

    public static String ACTIVE_PAYMENT_ERROR = 'An active payment exists for the property';
    public static String PAYMENT_NOT_ELIGIBLE = 'The payment is not eligible. Please review calculation details';
    public static String NOT_IN_SYNC = 'The SEM and SEI not in sync with Property record. Please re-calculate and request payment';
    public static String NO_WINDFALL_CALCULATION = 'An updated SEI has not been calculated and the payment eligibility has not been determined';
    public static String NO_FINAL_CALCULATION = 'The final payment amount has not been calculated';
    public static String NO_REFINANCE = 'The loan refinance has not been approved';
    public static String WINDFALL_RECORD_TYPE_ID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Windfall_Gains').getRecordTypeId();
    public static String FINAL_PAYMENT_RECORD_TYPE_ID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Final_Payment').getRecordTypeId();
    public static String VOLUNTARY_PAYMENT_RECORD_TYPE_ID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Voluntary_Payments').getRecordTypeId();
    public static String ITE_CASE_TYPE_RECORD_TYPE_ID   = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Income_Threshold_Exceeded').getRecordTypeId();
    /*
    *Method: Validate Payment Regeneration Request 
    * @param: recordId
    * @output: Map<String,String> response
    */
    @AuraEnabled
    public static string validateRequest(String caseId){
        Map<String,String> responseMap = new Map<String,String>();
        List<String> errorMsgList = new List<String>();

        /*
            Step1: Check the below to allow 
            1. SEI has been calculated and results saved 
            2. 'Payment Eligible' field = yes 
            3. SEI(old) and SEM(old) values saved in the respective case are in sync with the property record. 
            4. No active payment records exist for the property
        */
        Case caseRecord = getCaseRecord(caseId); 

        //(VHF-3129 , AC1.1), (VHF-2002, AC2 )
        // Active payments exists for the property. Cannot proceed.
        List<Payment__c> paymentsList = [Select Id, Status__c 
                                                        from Payment__c 
                                                        where 
                                                        Property__c =: caseRecord.Property__c
                                                        and 
                                                        Status__c not in ('Cancelled', 'Request Expired', 'Payment Received')
                                                    ];
        
        
        /*
        * Common Scenario
        */ 

        if(!paymentsList.isEmpty())
        {
            System.debug('payment list exists');
            //String paymentError = ACTIVE_PAYMENT_ERROR;
            errorMsgList.add(ACTIVE_PAYMENT_ERROR);
        }

        //(VHF-3129, AC 1.3), (VHF-2002, AC3)
        //Not in Sync with Property 
        if(caseRecord.SEI_OLD__c != caseRecord.Property__r.Shared_Equity_Interest__c || caseRecord.SEM_OLD__c != caseRecord.Property__r.Shared_Equity_Money__c )
        {
            system.debug('sei sem not matching');
            //String notInSync = NOT_IN_SYNC;
            errorMsgList.add(NOT_IN_SYNC);
        }

        /*
        * Windfall Gains / Voluntary payments Scenario / ITE Type
        */ 

        if(caseRecord.RecordTypeId == WINDFALL_RECORD_TYPE_ID || caseRecord.RecordTypeId == VOLUNTARY_PAYMENT_RECORD_TYPE_ID || caseRecord.RecordTypeId == ITE_CASE_TYPE_RECORD_TYPE_ID)
        {
            system.debug('windfall gains / voluntary paymentrecord type / ITE record type');
            //(VHF-3129, AC 1.2) - Payment Ineligible 
            if(caseRecord.Payment_Eligible__c == 'No' || caseRecord.Payment_Eligible__c == null)
            {
                system.debug('payment not eligible');
                //String notEligibleError = PAYMENT_NOT_ELIGIBLE;
                errorMsgList.add(PAYMENT_NOT_ELIGIBLE);
            }

            //AC 1.4 - No Windfall Calulcation done 
            if(caseRecord.SEI_new__c == null || caseRecord.SEM_new__c == null)
            {
                system.debug('no windfall calculation');
                errorMsgList.add(NO_WINDFALL_CALCULATION);
            }
        }

        /*
        * Final Payment Scenario
        */ 
        if(caseRecord.RecordTypeId == FINAL_PAYMENT_RECORD_TYPE_ID)
        {
            system.debug('final payment record type');
            //(VHF-2002, AC4) - No Final Payment Calculation 
            if(caseRecord.Proportionate_interest_amount__c == null || caseRecord.Payment_Amount__c == null)
            {
                system.debug('no final payment calculation');
                errorMsgList.add(NO_FINAL_CALCULATION);
            }

        }

        /*
        * ITE Type Scenario
        */
        if(caseRecord.RecordTypeId == ITE_CASE_TYPE_RECORD_TYPE_ID)
        {
            system.debug('ITE payment record type');
            if(caseRecord.Refinance_Approved__c == 'No')
            {
                system.debug('refinanced not approved');
                errorMsgList.add(NO_REFINANCE);
            }
        }
        
        
        if(!errorMsgList.isEmpty())
        {
            responseMap.put('errors', JSON.serialize(errorMsgList));
        }
        else 
        {
            responseMap.put('errors', '');
        }
        
        return JSON.serialize(responseMap);
    }

    /*
    * Update the case with status = payment requested
    */

    @AuraEnabled
    public static Case updateCase(string caseId, String comments) 
    { 
        System.debug('coming into udpate case');
        System.debug('case Id=' + caseId);
        System.debug('case comments=' + comments);
        Case updateCase = getCaseRecord(caseId);
        updateCase.Payment_Comments__c = comments;
        updateCase.BypassValidation__c = true; 
        updateCase.Status = 'Payment Requested';
        System.debug('udpateCase=' + updateCase);
        update updateCase;

        System.debug('case after updated-' + updateCase);
        return updateCase;
    }


    public static Case getCaseRecord(String caseId)
    {
        Case caseRec = [Select 
                        Id, Payment_Eligible__c, SEI_new__c, SEI_OLD__c, SEM_new__c, SEM_OLD__c, Payment_Comments__c,
                        RecordTypeId, Property__c, BypassValidation__c, Property__r.Shared_Equity_Interest__c, 
                        Property__r.Shared_Equity_Money__c, Payment_Amount__c, Proportionate_interest_amount__c,
                        Refinance_Approved__c
                        from Case where Id =: caseId];

                        System.debug('case record =' + caseRec);
        return caseRec;
    }
}