force-app/main/default/objects/Case/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>VHF-1712</description>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Scheduled_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Settlement_Status__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Status__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upcoming settlement</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Overdue settlement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/ApplicationCaseId__c.field-meta.xml
<CustomField>
    <fullName>ApplicationCaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Final Applications</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Scheduled_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Settlement_Date__c</fullName>
    <description>Holds the scheduled date for settlement</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Date__c</fullName>
    <description>Scheduled Settlement Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>1.Must be later than Today&apos;s date.

2.If scheduled settlement date is less than 5 working days, then turnaround times may be more.</inlineHelpText>
    <label>Scheduled Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PopulateScheduledSettlementDateOnCase.cls
/*Created by Nayana Revanna.
 * Called from process builder - "VHF Final Application Flow"
 * Updates the Case with recent most active Final application with the scheduled date. 
 */
 /*******************************************************************************************/
/* MODIFICATION LOG
* Version           Modified by          Date               Description
*-------------------------------------------------------------------------------------------
*  1.1              Manish Jhingran      27/09/2021          Modification (Updating Case settlement status) & Bulkify the code 
*  VHF-2514         Sourabh Singh    	 11/10/2021			 	
*******************************************************************************************/

public class PopulateScheduledSettlementDateOnCase
{
@InvocableMethod
Public static void calculateSettlementDate(List < ID > caseID)
{
SYSTEM.DEBUG('METHOD ENTRY - calculateSettlementDate');
List < Contract > finalAppls = [SELECT ID,ApplicationCaseId__c, Status,Settlement_Date__c, ApplicationCaseId__r.Status,
ApplicationCaseId__r.Scheduled_Settlement_Date__c FROM CONTRACT WHERE ApplicationCaseId__c in : caseID
AND Status NOT IN('Cancelled', 'Rejected', 'Cancelled Settlement')
ORDER BY createdDate DESC];
//SYSTEM.DEBUG('***' + finalAppls[0].Settlement_Date__c); //VHF-2514:commented to avoid list index OOB exception
if (!finalAppls.isEmpty())
{
Map < Id, Case > mapCaseUpdate = new Map < Id, Case > ();
for (Contract objContract: finalAppls)
{
if (!mapCaseUpdate.containskey(objContract.ApplicationCaseId__c))
{
Case caseRec = new Case();
caseRec.ID = objContract.ApplicationCaseId__c;
caseRec.Status = objContract.ApplicationCaseId__r.Status;
caseRec.Scheduled_Settlement_Date__c = objContract.Settlement_Date__c;
SYSTEM.DEBUG('***caseRec.Status '+caseRec.Status);
SYSTEM.DEBUG('***^^^^caseRec.ID'+caseRec.ID);
SYSTEM.DEBUG('%%%%%%%%caseRec.Scheduled_Settlement_Date__c'+caseRec.Scheduled_Settlement_Date__c );
If(objContract.Settlement_Date__c >= System.Today()&& caseRec.status <> 'Closed' && objContract.Status <> 'Settled')
{
SYSTEM.DEBUG('*** Settlement_Date__c>=System.Today()');
caseRec.BypassValidation__c = True;
caseRec.Settlement_Status__c = 'Upcoming settlement';
}
else If(objContract.Settlement_Date__c <System.Today() && caseRec.Status == 'Settlement')
{
SYSTEM.DEBUG('@@@@@@@@@@Settlement_Date__c<System.Today()');
caseRec.BypassValidation__c = True;
caseRec.Settlement_Status__c = 'Overdue settlement';
}
else if (caseRec.status == 'Closed' && objContract.Status == 'Settled')
{
caseRec.BypassValidation__c = True;
SYSTEM.DEBUG('######caseRec.status==Closed');
caseRec.Settlement_Status__c = 'Settled';
}
mapCaseUpdate.put(caseRec.Id, caseRec);
}
}
update mapCaseUpdate.values();
}
}
}