force-app/main/default/objects/Contract/fields/IndividualApplicationId__c.field-meta.xml
<CustomField>
    <fullName>IndividualApplicationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provisional Application ID</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Final Applications</relationshipLabel>
    <relationshipName>Contracts_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Final_Application_In_Progress_c__c.field-meta.xml
<CustomField>
    <fullName>Final_Application_In_Progress_c__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final Application in Progress</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Hard_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Hard_Expiry_Date__c</fullName>
    <description>This date holds the final date beyond which no application can or should be extended.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Hard Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Second_Extension_Requested__c.field-meta.xml
<CustomField>
    <fullName>Second_Extension_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The second Expiry date extension indicator.</description>
    <label>Second Extension Requested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FinalAppBtnController.cls
public class FinalAppBtnController 
{
   @AuraEnabled
    public static boolean getBtnVisibile(String appId) 
    { 
        boolean showFlag = false;
        
        List<IndividualApplication> finalAppls = [select id, status,
                                     (select id,status from Contracts_del__r where status not in ('Cancelled','Rejected','Cancelled Settlement')) 
                                     from Individualapplication 
                                     where status = 'Provisionally Approved'
                                     and Id=:appId];   
        
        if(finalAppls.size()>0 && finalAppls[0].Contracts_del__r.size()==0)
            showFlag = true;
        
        system.debug('recid='+appId);
        system.debug('showflag='+showFlag);
        
        return showflag;
    }
    
    //Added by N Rev for VHF 2236
    @AuraEnabled
    public static boolean displayButtonForExpiry(String appId) 
    {
    	SYSTEM.DEBUG('METHOD ENTRY - displayButtonForExpiry');
    	IndividualApplication provApp = [SELECT Id,
                                            Hard_Expiry_Date__c,
                                            Second_Extension_Requested__c,
                                     		status,
                                            Final_Application_In_Progress_c__c 
                                    FROM IndividualApplication 
                                    WHERE Id = :appId];
        if(provApp.Final_Application_In_Progress_c__c == false &&
           provApp.Hard_Expiry_Date__c >= System.today() 
           && provApp.Second_Extension_Requested__c == false
           && provApp.status == 'Provisionally Approved'){
            return true;
        }
       	else
            return false;
    }
    
}