force-app/main/default/objects/Annual_Review__c/Annual_Review__c.object-meta.xml
<CustomObject>
    <description>Stores the responses to questions that participants to the VHF scheme need to complete on an annual basis</description>
    <label>Annual Review</label>
    <nameField>
        <displayFormat>AR-{0000000000}</displayFormat>
        <label>Annual Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Reviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Review__c/fields/Absence_end_date__c.field-meta.xml
<CustomField>
    <fullName>Absence_end_date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Absence #1 End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Absence_start_date__c.field-meta.xml
<CustomField>
    <fullName>Absence_start_date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Absence #1 Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Annual_Review_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Annual_Review_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Annual Review End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Annual_Review_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Annual_Review_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Annual Review Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in process builder and flow to allow updates to records otherwise locked by validations rules.</description>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Submission</fullName>
                <default>true</default>
                <label>Awaiting Submission</label>
            </value>
            <value>
                <fullName>Awaiting Verification</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Absence_Duration_Months__c.field-meta.xml
<CustomField>
    <fullName>Absence_Duration_Months__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Absence Duration(Months)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Absence_end_date__c.field-meta.xml
<CustomField>
    <fullName>Absence_end_date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Absence end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Absence_start_date__c.field-meta.xml
<CustomField>
    <fullName>Absence_start_date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Absence start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Annual_Review__c.field-meta.xml
<CustomField>
    <fullName>Annual_Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Annual Review ID</label>
    <referenceTo>Annual_Review__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>VHF-1712</description>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Valid_Absence_Duration_Months__c.field-meta.xml
<CustomField>
    <fullName>Valid_Absence_Duration_Months__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Valid Absence Duration (Months)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Final_Payment.recordType-meta.xml
<RecordType>
    <fullName>Final_Payment</fullName>
    <active>true</active>
    <businessProcess>Final Payment</businessProcess>
    <label>Final Payment</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Income_Threshold_Exceeded.recordType-meta.xml
<RecordType>
    <fullName>Income_Threshold_Exceeded</fullName>
    <active>true</active>
    <businessProcess>Income Threshold Exceeded</businessProcess>
    <label>Income Threshold Exceeded</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Long_Term_Absence.recordType-meta.xml
<RecordType>
    <fullName>Long_Term_Absence</fullName>
    <active>true</active>
    <businessProcess>Long Term Absence</businessProcess>
    <label>Long Term Absence</label>
</RecordType>

force-app/main/default/objects/Order/fields/ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Stores the payment details that a participant need to make as part of post settlement process</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PID-{00000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Windfall Gains, Voluntary Payments, Income Threshold Exceeded, Final Payment, Early Payment</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Updated by SRO Officer</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Payment Registered</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Request Expired</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
                <isActive>false</isActive>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Requested</fullName>
                <isActive>false</isActive>
                <label>Requested</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseTriggerHelper.cls
/*
* Description: Trigger Handler for Case Object 
** Version History ** 
Created: Sourabh Singh, 10/12/2021
*******************************************************************************************/
/* MODIFICATION LOG
 * Version          Developer          Date               Description
 *-------------------------------------------------------------------------------------------
 *  1.1             Arjun Singh        20/01/2022          Added method for duration and validation duration calculation
 *  1.2             Sourabh            24/1/2022           VHF- 4270
 *  1.3             Arjun Singh        03/02/2022          VHF-3082
 *  1.4             Manish             21/03/2022          VHF-4306
 */

public class CaseTriggerHelper {
  public  static String STATUS_CREATED = 'Created';
  public  static String STATUS_PAYMENT_REGISTERED = 'Payment Registered';
  public  static String STATUS_PAYMENT_REQUESTED = 'Payment Requested';
  public  static String STATUS_PAYMENT_RECEIVED = 'Payment Received';
  public  static String Err_Msg = 'Active payment records exists. Cannot reject the case.';
  Public  static String Err_Msg_Cancellation = 'Active payment records exists. Cannot cancel the case.';
  /*
   * Reset bypass flag to false
   */
  public static void resetBypassAfterUpdate(List<Case> caseList) {
    Set<Id> caseIds = new Set<Id>();
    for (Case c : caseList) {
      if (c.BypassValidation__c)
        caseIds.add(c.Id);
    }

    List<Case> casesToUpdate = [
      SELECT id, bypassvalidation__c
      FROM Case
      WHERE id IN :caseIds
    ];

    if (!casesToUpdate.isEmpty()) {
      for (Case c : casesToUpdate)
        c.BypassValidation__c = false;
      update casesToUpdate;
    }
  }
  
  /**
   * @Description : Calculate valid Absence Duration in Months
   */
  public static void calculateValidAbsenceMonths(List<Case> caseList) {
    Id longTermAbsenceRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName()
      .get('Long_Term_Absence')
      .getRecordTypeId();
    List<Case> longTermAbsenceCases = new List<Case>();
    Map<Id, Case> casesMap = new Map<Id, Case>();
    //Map<Id,Order> propertyMap = new Map<Id,Order>();
    //Set<Id> propertyIds = New Set<Id>();
    Set<Id> annualReviewIds = new Set<Id>();
    Map<Id, Annual_Review__c> annualReviewMap = new Map<Id, Annual_Review__c>();

    for (Case caseRecord : caseList) {
      if (caseRecord.recordTypeId == longTermAbsenceRecordTypeId) {
        longTermAbsenceCases.add(caseRecord);
        annualReviewIds.add(caseRecord.Annual_Review__c);
      }
    }

    for (Annual_Review__c annualReviewRec : [
      SELECT Id, Annual_Review_Start_Date__c, Annual_Review_End_Date__c
      FROM Annual_Review__c
      WHERE Id IN :annualReviewIds
    ]) {
      annualReviewMap.put(annualReviewRec.Id, annualReviewRec);
    }

    for (Case caseRec : longTermAbsenceCases) {
      System.debug('caseRec1>>>>' + caseRec);
      if (caseRec.origin == 'Participant Portal') {
        caseRec.Valid_Absence_Duration_Months__c = 0.0;
      } else if (
        annualReviewMap.containsKey(caseRec.Annual_Review__c) &&
        caseRec.Absence_start_date__c != null &&
        caseRec.Absence_end_date__c != null
      ) {
        date settlementStartDate = annualReviewMap.get(caseRec.Annual_Review__c)
          .Annual_Review_Start_Date__c;
        date settlementEndDate = annualReviewMap.get(caseRec.Annual_Review__c)
          .Annual_Review_End_Date__c;
        decimal totalvalidMonth=0.0;
        if (
          caseRec.Absence_start_date__c < settlementStartDate &&
          caseRec.Absence_end_date__c < settlementStartDate
        ) {
          // Before the review period range
          totalvalidMonth = 0.0;
        } else if (
          caseRec.Absence_start_date__c >= settlementStartDate &&
          caseRec.Absence_end_date__c <= settlementEndDate
        ) {
          //In between the review period range
          Integer noOfDays =
            caseRec.Absence_start_date__c.daysBetween(
              caseRec.Absence_end_date__c
            ) + 1;
          totalvalidMonth = getDurationInMonth(noOfDays);
        } else if (
          caseRec.Absence_start_date__c <= settlementStartDate &&
          caseRec.Absence_end_date__c <= settlementEndDate
        ) {
          //In between the review period range
          Integer noOfDays =
            settlementStartDate.daysBetween(caseRec.Absence_end_date__c) + 1;
          totalvalidMonth = getDurationInMonth(noOfDays);
        } else if (
          caseRec.Absence_start_date__c > settlementStartDate &&
          caseRec.Absence_end_date__c > settlementEndDate &&
          caseRec.Absence_start_date__c < settlementEndDate
        ) {
          // between and outside the end period
          Integer noOfDays =
            caseRec.Absence_start_date__c.daysBetween(settlementEndDate) + 1;
          totalvalidMonth = getDurationInMonth(noOfDays);
        } else if (
          caseRec.Absence_start_date__c > settlementStartDate &&
          caseRec.Absence_end_date__c > settlementEndDate
        ) {
          //both outside of end range
          totalvalidMonth = 0.0;
        }
        caseRec.Valid_Absence_Duration_Months__c = totalvalidMonth;
      }
      if (
      //  annualReviewMap.containsKey(caseRec.Annual_Review__c) &&  //Sourabh:commented to include cases with origin = Participant Portal
        caseRec.Absence_start_date__c != null &&
        caseRec.Absence_end_date__c != null
      ) {
        Integer noOfDays =
          caseRec.Absence_start_date__c.daysBetween(
            caseRec.Absence_end_date__c
          ) + 1;
        decimal durationInMonthValue = getDurationInMonth(noOfDays);
        caseRec.Absence_Duration_Months__c = durationInMonthValue;
      }
      System.debug('caseRec2>>>>' + caseRec);
    }
  }

  public static decimal getDurationInMonth(Integer days) {
    decimal durationDivider = decimal.valueOf(label.LTA_Duration_Divider);
    String totalDuration = String.valueOf(days / durationDivider);
    Integer trimmedTotalDuration = totalDuration.indexOf('.') + 2;
    decimal durationInMonthValue;
    if (totalDuration.indexOf('.') == -1) {
      durationInMonthValue = decimal.valueOf(totalDuration);
    } else {
      durationInMonthValue = decimal.valueOf(
        totalDuration.subString(0, trimmedTotalDuration)
      );
    }
    System.debug('durationInMonthValue>>>' + durationInMonthValue);
    return durationInMonthValue;
  }

  public static void finalPaymentCaseValidation(List<Case> newCaseList, Map<Id,Case>oldCaseMap){
    Set<Id> rejectedCaseIds = new Set<Id>();
    Set<String> statusToInclude = new Set<String>{STATUS_CREATED, STATUS_PAYMENT_REGISTERED, STATUS_PAYMENT_REQUESTED, STATUS_PAYMENT_RECEIVED};
    Id fullPaymentRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Final_Payment').getRecordTypeId();
    Map<Id,Payment__c> caseWithLatestPayment = new Map<Id, Payment__c>();

    for (Case cRecord : newCaseList) {
      if (oldCaseMap.get(cRecord.id).Status != cRecord.Status && cRecord.Status =='Rejected' && cRecord.RecordTypeId == fullPaymentRecordTypeId){
        rejectedCaseIds.add(cRecord.Id);
      }
    }
    for(Payment__c paymentRecord : [Select Id, Case__c, Status__c From Payment__c Where Case__c IN : rejectedCaseIds AND Status__c IN : statusToInclude order by createddate desc]){
      if(!caseWithLatestPayment.containsKey(paymentRecord.Case__c)){
        caseWithLatestPayment.put(paymentRecord.Case__c, paymentRecord);
      }
    }

    for(Case cRecord : newCaseList){
      if(caseWithLatestPayment.containsKey(cRecord.Id)){
        cRecord.addError(Err_Msg);
      }
    }
  }
  
   public static void finalPaymentCaseValidation_Cancellation(List<Case> newCaseList, Map<Id,Case>oldCaseMap){
    Set<Id> CancelledCaseIds = new Set<Id>();
    Set<String> statusToInclude = new Set<String>{STATUS_CREATED, STATUS_PAYMENT_REGISTERED, STATUS_PAYMENT_REQUESTED,STATUS_PAYMENT_RECEIVED};
    Id fullPaymentRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Final_Payment').getRecordTypeId();
    Map<Id,Payment__c> caseWithLatestPayment = new Map<Id, Payment__c>();

    for (Case cRecord : newCaseList) {
      
         if (oldCaseMap.get(cRecord.id).Status != cRecord.Status && cRecord.Status =='Cancelled' && cRecord.RecordTypeId == fullPaymentRecordTypeId){
        CancelledCaseIds.add(cRecord.Id);
      }
    }
    
    for(Payment__c paymentRecord : [Select Id, Case__c, Status__c From Payment__c Where Case__c IN : CancelledCaseIds AND Status__c IN : statusToInclude order by createddate desc]){
      if(!caseWithLatestPayment.containsKey(paymentRecord.Case__c)){
        caseWithLatestPayment.put(paymentRecord.Case__c, paymentRecord);
      }
    }

    for(Case cRecord : newCaseList){
      if(caseWithLatestPayment.containsKey(cRecord.Id)){
      //if (cRecord.Status =='Cancelled')
      //{
       cRecord.addError(Err_Msg_Cancellation);
      //  }
        
      //  if (cRecord.Status =='Rejected')
     //  {
      //  cRecord.addError(Err_Msg);
        //}
      }
    }
  
  }
  public static void ITE_CaseValidation_Cancellation(List<Case> newCaseList, Map<Id,Case>oldCaseMap){
    Set<Id> CancelledCaseIds = new Set<Id>();
    Set<String> statusToInclude = new Set<String>{STATUS_CREATED, STATUS_PAYMENT_REGISTERED, STATUS_PAYMENT_REQUESTED};
    Id ITERecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Income_Threshold_Exceeded').getRecordTypeId();
    Profile p = [select id,Name from Profile where id=:Userinfo.getProfileid()];
    Map<Id,Payment__c> caseWithLatestPayment = new Map<Id, Payment__c>();

    for (Case cRecord : newCaseList) {
         if (oldCaseMap.get(cRecord.id).Status != cRecord.Status && cRecord.Status =='Cancelled' && cRecord.RecordTypeId == ITERecordTypeId){
        CancelledCaseIds.add(cRecord.Id);
      }
    }
    for(Payment__c paymentRecord : [Select Id, Case__c, Status__c From Payment__c Where Case__c IN : CancelledCaseIds AND Status__c IN : statusToInclude order by createddate desc]){
      if(!caseWithLatestPayment.containsKey(paymentRecord.Case__c)){
        caseWithLatestPayment.put(paymentRecord.Case__c, paymentRecord);
      }
    }

    for(Case cRecord : newCaseList){
      if(caseWithLatestPayment.containsKey(cRecord.Id)&&(p.Name =='Operations')){
      
       cRecord.addError(Err_Msg_Cancellation);
     
      }
    }
    }
  }