force-app/main/default/objects/Annual_Review__c/Annual_Review__c.object-meta.xml
<CustomObject>
    <description>Stores the responses to questions that participants to the VHF scheme need to complete on an annual basis</description>
    <label>Annual Review</label>
    <nameField>
        <displayFormat>AR-{0000000000}</displayFormat>
        <label>Annual Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Reviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Review__c/fields/Primary_Participant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Primary participant linked to the annual review</description>
    <label>Primary Participant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annual Reviews</relationshipLabel>
    <relationshipName>Annual_Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <description>This field is used to track when a Major or Minor Update event occurs within an Annual Review</description>
    <label>Revision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minor Update Requested</fullName>
            </value>
            <value>
                <fullName>Minor Update Complete</fullName>
            </value>
            <value>
                <fullName>Major Update Requested</fullName>
            </value>
            <value>
                <fullName>Major Update Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Submission</fullName>
                <default>true</default>
                <label>Awaiting Submission</label>
            </value>
            <value>
                <fullName>Awaiting Verification</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Annual_Review__c.field-meta.xml
<CustomField>
    <fullName>Annual_Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Annual Review ID</label>
    <referenceTo>Annual_Review__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Individual_Application__c.field-meta.xml
<CustomField>
    <fullName>Individual_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual Application</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Individual_Application_Shadow__c.field-meta.xml
<CustomField>
    <fullName>Individual_Application_Shadow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Introduced with VHF-97 to access expiry date from the case object</description>
    <label>Individual_Application_Shadow</label>
    <referenceTo>Individual_Application_Shadow__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Participant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Participant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Participant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ApplicationCaseId__c.field-meta.xml
<CustomField>
    <fullName>ApplicationCaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Final Applications</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individual_Application_Shadow__c/Individual_Application_Shadow__c.object-meta.xml
<CustomObject>
    <label>Individual_Application_Shadow</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Individual_Application_Shadow Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shadow Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individual_Application_Shadow__c/fields/Individual_Application__c.field-meta.xml
<CustomField>
    <fullName>Individual_Application__c</fullName>
    <label>Individual Application</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Shadow Applications</relationshipLabel>
    <relationshipName>Shadow_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Individual_Application_Shadow__c.field-meta.xml
<CustomField>
    <fullName>Individual_Application_Shadow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual_Application_Shadow</label>
    <referenceTo>Individual_Application_Shadow__c</referenceTo>
    <relationshipLabel>Provisional Applications</relationshipLabel>
    <relationshipName>Provisional_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Stores the payment details that a participant need to make as part of post settlement process</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PID-{00000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Windfall Gains, Voluntary Payments, Income Threshold Exceeded, Final Payment, Early Payment</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Primary_Participant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Auto-linked when payment record is created</description>
    <label>Primary Participant Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Updated by SRO Officer</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Payment Registered</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Request Expired</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
                <isActive>false</isActive>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Requested</fullName>
                <isActive>false</isActive>
                <label>Requested</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContentDocumentLink_TriggerHelper.cls
/*******************************************************************************************
* @Name         ContentDocumentLink_TriggerHelper 
* @Author       Sebastian Anton <santon@salesforce.com>
* @Date         31/08/2021
* @Description  Triggered each time a content document is generated against a specified objects
*******************************************************************************************/
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*  1.0              Sebastian      31/08/2021          Initial Creation   
*  1.1              Sebastian      14/10/2021          Adjusted to copy notes related to Individual Applications to Case   
*  1.2              Sourabh		   1/12/2021           VHF-3560: Updated file visibility to 'AllUsers'
*  1.3              Sebastian      19/01/2022          Added verifyParticipantFileUploadAccess method to prevent participants uploading files
*                                                      when they are not permitted
*  1.4              Arjun Singh    21/02/2022          VHF-3316 - Final Payment - Generate Payout Document
*******************************************************************************************/
public class ContentDocumentLink_TriggerHelper {
    // Method: congaFileLinkToCase
    public static void congaFileLinkToCase(List<ContentDocumentLink> contentDocumentLinks){
        
        // Identify if any relevant ContentDocumentLinks have been inserted
        Map<Id, List<Id>> shadowApplicationContentDocumentLinksByLinkedEntityId = new Map<Id, List<Id>>();
        Map<Id, List<Id>> contractContentDocumentLinksByLinkByLinkedEntityId = new Map<Id, List<Id>>();
        Map<Id, List<Id>> individualApplicationContentDocumentLinksByLinkedEntityId = new Map<Id, List<Id>>();
        Map<Id, List<Id>> paymentContentDocumentLinksByLinkedEntityId = new Map<Id, List<Id>>();
        Set<Id> paymentContentDocumentIds = new Set<Id>();
        Set<Id> paymentPayoutDocumentContentDocumentsIds = new Set<Id>();

        for(ContentDocumentLink contentDocumentLink: contentDocumentLinks){
            System.debug('contentDocumentLink>>>>>'+contentDocumentLink);
            if(String.valueOf(contentDocumentLink.LinkedEntityID.getsObjectType()) == 'Individual_Application_Shadow__c'){
                if(shadowApplicationContentDocumentLinksByLinkedEntityId.containsKey(contentDocumentLink.linkedEntityId)){
                    shadowApplicationContentDocumentLinksByLinkedEntityId.get(contentDocumentLink.linkedEntityId).add(contentDocumentLink.contentdocumentId);
                }else{
                    shadowApplicationContentDocumentLinksByLinkedEntityId.put(contentDocumentLink.linkedEntityId, new List<String>{contentDocumentLink.contentdocumentId});
                }
                System.debug('*** Shadow CDL Processed: ' + contentDocumentLink.linkedEntityId + ' ' + contentDocumentLink.contentdocumentId);
            }else if(String.valueOf(contentDocumentLink.LinkedEntityID.getsObjectType()) == 'Contract'){
                if(contractContentDocumentLinksByLinkByLinkedEntityId.containsKey(contentDocumentLink.linkedEntityId)){
                    contractContentDocumentLinksByLinkByLinkedEntityId.get(contentDocumentLink.linkedEntityId).add(contentDocumentLink.contentdocumentId);
                }else{
                    contractContentDocumentLinksByLinkByLinkedEntityId.put(contentDocumentLink.linkedEntityId, new List<String>{contentDocumentLink.contentdocumentId});
                }
                System.debug('*** Contract CDL Processed: '+contentDocumentLink.linkedEntityId+' '+contentDocumentLink.contentdocumentId);
            }else if(String.valueOf(contentDocumentLink.linkedEntityID.getsObjectType()) == 'IndividualApplication'){
                if(individualApplicationContentDocumentLinksByLinkedEntityId.containsKey(contentDocumentLink.LinkedEntityId)){
                    individualApplicationContentDocumentLinksByLinkedEntityId.get(contentDocumentLink.LinkedEntityId).add(contentDocumentLink.contentDocumentId);
                }else{
                    individualApplicationContentDocumentLinksByLinkedEntityId.put(contentDocumentLink.linkedEntityId, new List<String>{contentDocumentLink.contentdocumentId});
                }
                System.debug('*** Individual Application CDL Processed: '+contentDocumentLink.linkedEntityId+' '+contentDocumentLink.contentdocumentId);
            }else if(String.valueOf(contentDocumentLink.linkedEntityID.getsObjectType()) == 'Payment__c'){
                paymentContentDocumentIds.add(contentDocumentLink.ContentDocumentId);
                if(paymentContentDocumentLinksByLinkedEntityId.containsKey(contentDocumentLink.LinkedEntityId)){
                    paymentContentDocumentLinksByLinkedEntityId.get(contentDocumentLink.LinkedEntityId).add(contentDocumentLink.contentDocumentId);
                }else{
                    paymentContentDocumentLinksByLinkedEntityId.put(contentDocumentLink.linkedEntityId, new List<String>{contentDocumentLink.contentdocumentId});
                }
                System.debug('*** Payment CDL Processed: '+contentDocumentLink.linkedEntityId+' '+contentDocumentLink.contentdocumentId);
            }
        } // End - for(ContentDocumentLink)l

        System.debug('*** Documents Linked to Shadow Application: ' + shadowApplicationContentDocumentLinksByLinkedEntityId);
        System.debug('*** Documents Linked to Contract: ' + contractContentDocumentLinksByLinkByLinkedEntityId);
        System.debug('*** Documents Linked to Individual Application: ' + individualApplicationContentDocumentLinksByLinkedEntityId);

        // Check if the Payment attched document is Payout Document and store it in paymentPayoutDocumentContentDocumentsIds
        for(ContentDocument cd: [Select Id from ContentDocument where Id IN : paymentContentDocumentIds AND title = 'Payout Document.pdf']){
            paymentPayoutDocumentContentDocumentsIds.add(cd.Id);
        }

        // If relevant ContentDocumentLinks are found then create links to appropirate objects 
        if(!shadowApplicationContentDocumentLinksByLinkedEntityId.isEmpty() || !contractContentDocumentLinksByLinkByLinkedEntityId.isEmpty() || !individualApplicationContentDocumentLinksByLinkedEntityId.isEmpty() || !paymentContentDocumentLinksByLinkedEntityId.isEmpty()){
            List<Individual_Application_Shadow__c> relatedShadowApplications = [SELECT ID, Individual_Application__c, Individual_Application__r.ApplicationCaseId 
                                                                                FROM Individual_Application_Shadow__c 
                                                                                WHERE ID 
                                                                                IN :shadowApplicationContentDocumentLinksByLinkedEntityId.keySet()];

            List<Contract> relatedContracts = [SELECT ID, ApplicationCaseId__c
                                                FROM Contract
                                                WHERE ID
                                                IN :contractContentDocumentLinksByLinkByLinkedEntityId.keySet()];

            List<IndividualApplication> relatedIndividualApplications = [SELECT ID, ApplicationCaseId
                                                                            FROM IndividualApplication
                                                                            WHERE ID
                                                                            IN :individualApplicationContentDocumentLinksByLinkedEntityId.keySet()];

            List<Payment__c> paymentRecords = [SELECT ID, Case__c  FROM Payment__c WHERE ID IN:  paymentContentDocumentLinksByLinkedEntityId.keySet()];

            List<ContentDocumentLink> contentDocumentLinksToInsert = new List<ContentDocumentLink>();

            for(Individual_Application_Shadow__c relatedShadowApplication: relatedShadowApplications){
                for(Id contentDocumentLinkId: shadowApplicationContentDocumentLinksByLinkedEntityId.get(relatedShadowApplication.Id)){
                    contentDocumentLinksToInsert.add(new ContentDocumentLink(
                                                    ContentDocumentId = contentDocumentLinkId,
                                                    LinkedEntityId = relatedShadowApplication.Individual_Application__c,
                                                    ShareType = 'V',
                                                    Visibility = 'AllUsers'));
                } // End - for(Id)
            } // End - for(Individual_Application_Shadow)
            for(Contract relatedContract: relatedContracts){
                for(Id contentDocumentLinkId: contractContentDocumentLinksByLinkByLinkedEntityId.get(relatedContract.Id)){
                    contentDocumentLinksToInsert.add(new ContentDocumentLink(
                                                    ContentDocumentId = contentDocumentLinkId,
                                                    linkedEntityId = relatedContract.ApplicationCaseId__c,
                                                    ShareType = 'V',
                                                    Visibility = 'AllUsers'));
                } // End - for(Id)
            } // End - for(Contract)
            for(IndividualApplication relatedIndividualApplication: relatedIndividualApplications){
                for(Id contentDocumentLinkId: individualApplicationContentDocumentLinksByLinkedEntityId.get(relatedIndividualApplication.Id)){
                    contentDocumentLinksToInsert.add(new ContentDocumentLink(
                                                    ContentDocumentId = contentDocumentLinkId,
                                                    linkedEntityId = relatedIndividualApplication.ApplicationCaseId,
                                                    ShareType = 'V',
                                                    Visibility = 'AllUsers'));
                } // End - for(Id)
            } // End - for(IndividualApplication)
            // Payout docuement 
            for(Payment__c paymentRecord : paymentRecords){
                for(Id contentDocumentLinkId: paymentContentDocumentLinksByLinkedEntityId.get(paymentRecord.Id)){
                    contentDocumentLinksToInsert.add(new ContentDocumentLink(
                                                    ContentDocumentId = contentDocumentLinkId,
                                                    linkedEntityId = paymentRecord.Case__c,
                                                    ShareType = 'V',
                                                    Visibility = 'AllUsers'));
                }
            }
            System.debug('*** Content Document Links to Insert: ' + contentDocumentLinksToInsert);

            // Insert new ContentDocumentLinks in to Salesforce
            List<Id> successfullyInsertedContentDocumentLinkIds = new List<Id>();
            if(!contentDocumentLinksToInsert.isEmpty()){
                List<Database.SaveResult> saveResults = Database.insert(contentDocumentLinksToInsert, false);
                for(Database.SaveResult sr: saveResults){
                    if(sr.isSuccess()){
                        successfullyInsertedContentDocumentLinkIds.add(sr.getId());
                    } else {
                        for(Database.Error err: sr.getErrors()){
                            System.debug('ERROR OCCURED: Failed Content Document Link Insertion: ID = '+sr.Id+' Status Code: '+err.getStatusCode()+' Message: '+err.getMessage());
                        }
                    }
                } // End - for(Database.saveResult)
            }
            System.debug('*** Successfully Inserted Content Document Links: ' + successfullyInsertedContentDocumentLinkIds);
        }
    } // End - congaFileLinkToCase
    
     /**
    * Methods     :  RestrictFileExtensionUpload
    * @author     :  Manish Jhingran
    * @version    :  $Revision: 1.0 $, $Date: 18/Sep/2021
    * @Description:  This method restrict the SRO users/User assigned to Operation profile to upload files with extensions exe,msg,bat and wrf
    */
    public static void restrictFileExtensionUpload(List<ContentDocumentLink> contentDocumentLinks){ 
        if(!contentDocumentLinks.isEmpty()){
            Id Operation_PROFILE_ID = [SELECT ProfileId FROM User WHERE Profile.Name = 'Operations' LIMIT 1].ProfileId;
            if(UserInfo.getProfileId() == Operation_PROFILE_ID){
                Set<Id> linkedContentDocuments = new Set<Id>();
                for(ContentDocumentLink contentDocumentLink: contentDocumentLinks){
                    linkedContentDocuments.add(contentDocumentLink.ContentDocumentId);
                }
                map<Id, ContentDocument> contentDocumentsByContentDocumentId = new map<Id, ContentDocument>([SELECT Id, Title, FileExtension FROM ContentDocument WHERE Id IN :linkedContentDocuments]);
                for(ContentDocumentLink contentDocumentLink: contentDocumentLinks) {
                    ContentDocument currentContentDocument = contentDocumentsByContentDocumentId.get(contentDocumentLink.ContentDocumentId);
                    if(currentContentDocument != null){
                        // Allow all files except : exe,wrf,msg and bat  
                        if((currentContentDocument.FileExtension == 'exe')||(currentContentDocument.FileExtension == 'msg')|| (currentContentDocument.FileExtension =='wrf')||(currentContentDocument.FileExtension =='bat')){
                            contentDocumentLink.addError('You can not upload file with extensions exe, msg, wrf and bat.');//Showing error    
                            System.debug('*** You can not upload file with extensions exe, msg, wrf and bat.');
                        }
                    }                        
                } // End - for(ContentDocumentLink)
            }  
        }
    }// End - restrictFileExtentionUpload

    // method: verifyParticipantFileUploadAccess
    public static void verifyParticapantFileUploadAccess(List<ContentDocumentLink> contentDocumentLinks){
        System.debug('*** Enter verifyParticapantFileUploadAccess method in ContentDocumentLink_TriggerHelper');
        System.debug('*** contentDocumentLinks to process: ' + contentDocumentLinks);
        // Find Annual Reviews linked to Content Document Links
        Set<Id> linkedAnnualReviewIds = new Set<Id>();
        for(ContentDocumentLink contentDocumentLink: contentDocumentLinks){
            if(String.valueOf(contentDocumentLink.LinkedEntityId.getsObjectType()) == 'Annual_Review__c'){
                linkedAnnualReviewIds.add(contentDocumentLink.LinkedEntityId);
            }
        } // End - for(ContentDocumentLink)

        // Check if file upload is allowed on each related Annual Review
        if(!linkedAnnualReviewIds.isEmpty()){
            // Check context user Profile is Participant
            Id participantProfileId = [SELECT Id FROM Profile WHERE Name = 'VHF Participant Community Plus User' LIMIT 1].Id;
            // Check context user if Primary Participant
            Boolean isPrimaryParticipant = [SELECT Contact.Primary_Participant__c FROM User WHERE Id = :userinfo.getUserId() LIMIT 1].Contact.Primary_Participant__c;
            if(userinfo.getProfileId() == participantProfileId && isPrimaryParticipant == true){
                // Create list of Annual Reviews Where file attachment is blocked
                Set<Id> blockedAnnualReviewIds = new Set<Id>();
                List<Annual_Review__c> linkedAnnualReviews = [SELECT Id, Status__c, Revision__c FROM Annual_Review__c WHERE Id IN :linkedAnnualReviewIds];
                for(Annual_Review__c annualReview: linkedAnnualReviews){
                    if((annualReview.Status__c == 'Awaiting Submission' || annualReview.Status__c == 'Awaiting Verification' || annualReview.Revision__c == 'Minor Update Requested') == false){
                        blockedAnnualReviewIds.add(annualReview.Id);
                        System.debug('*** File upload blocked on Annual Review: ' + annualReview.Id);
                    }
                } // End - for(Annual_Review__c)
                // Add errors to blocked content document links
                if(!blockedAnnualReviewIds.isEmpty()){
                    for(ContentDocumentLink contentDocumentLink: contentDocumentLinks){
                        if(blockedAnnualReviewIds.contains(contentDocumentLink.LinkedEntityId)){
                            contentDocumentLink.addError('Files cannot be uploaded at this time');
                        }
                    } // End - for(ContentDocumentLink)
                }
            }
        }
    } // End - verifyParticipantFileUploadAccess
}