force-app/main/default/objects/Individual_Application_Shadow__c/Individual_Application_Shadow__c.object-meta.xml
<CustomObject>
    <label>Individual_Application_Shadow</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Individual_Application_Shadow Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shadow Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individual_Application_Shadow__c/fields/Individual_Application__c.field-meta.xml
<CustomField>
    <fullName>Individual_Application__c</fullName>
    <label>Individual Application</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Shadow Applications</relationshipLabel>
    <relationshipName>Shadow_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Individual_Application_Shadow__c.field-meta.xml
<CustomField>
    <fullName>Individual_Application_Shadow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual_Application_Shadow</label>
    <referenceTo>Individual_Application_Shadow__c</referenceTo>
    <relationshipLabel>Provisional Applications</relationshipLabel>
    <relationshipName>Provisional_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
/*******************************************************************************************
* @Name         TaskTriggerHelperTest 
* @Author       Arjun Singh
* @Date         18/11/2021
* @Description  : Test Data Creation 
*******************************************************************************************/
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*  1.0              Arjun            18/11/2021          Initial Creation                                 
*******************************************************************************************/
@isTest
public with sharing class TestDataFactory {
    public static RegulatoryAuthorizationType getRegulatoryAuthorizationType(){
        return new RegulatoryAuthorizationType(Name = 'Victorian Homebuyer Fund');
    }
    public static IndividualApplication getIndividualApplication(Id RegulatoryAuthorizationTypeId, String statusVar ,date AppliedDateVar){
        IndividualApplication IndividualApplicationRecord = new IndividualApplication();
        IndividualApplicationRecord.LicenseTypeId = RegulatoryAuthorizationTypeId;
        IndividualApplicationRecord.status = statusVar;
        IndividualApplicationRecord.AppliedDate = AppliedDateVar;

        return IndividualApplicationRecord;

    }

    public static Individual_Application_Shadow__c getIndividualApplicationShadow(Id provisionalApplicataionId){
        Individual_Application_Shadow__c IndividualApplicationShadowRec = new Individual_Application_Shadow__c();
        IndividualApplicationShadowRec.Individual_Application__c = provisionalApplicataionId;

        return IndividualApplicationShadowRec;
    }
}