force-app/main/default/objects/Account/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <description>Financial Planner or Lender</description>
    <label>Business</label>
</RecordType>

force-app/main/default/objects/Case/fields/New_Panel_Financier__c.field-meta.xml
<CustomField>
    <fullName>New_Panel_Financier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Panel Financier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Refinance(New Panel Financier)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Confirmation__c/Confirmation__c.object-meta.xml
<CustomObject>
    <label>Refinance Confirmation</label>
    <nameField>
        <displayFormat>CF-{00000000}</displayFormat>
        <label>Confirmation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refinance Confirmations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Confirmation__c/fields/New_PF__c.field-meta.xml
<CustomField>
    <fullName>New_PF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Panel Financier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Refinance Confirmations (New PF)</relationshipLabel>
    <relationshipName>Confirmations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Confirmation__c/fields/Refinance_Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Refinance_Case_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Refinance Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Refinance Confirmations</relationshipLabel>
    <relationshipName>Confirmations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateCaseHandler.cls
public without sharing class UpdateCaseHandler {
    public static void UpdateNewPanelFinancier(Map<String, Object> input,Map<String, Object> output,Map<String, Object> options){
        Id caseId = (Id)input.get('CaseId');
        String sPanelFinancier = (String)input.get('NewPanelFinancier');
        output.put('success', false);
        if (caseId != null && String.isNotEmpty(sPanelFinancier)) {
            List<Account> listAccounts = [Select Id from Account where RecordType.Name = 'Business' and Name = :sPanelFinancier Limit 1];
            if(!listAccounts.isEmpty()){
                Case oCase = new Case(Id=caseId, New_Panel_Financier__c=listAccounts[0].Id);
                update oCase;
                List<Confirmation__c> CList = [Select Id, New_PF__c From Confirmation__c Where Refinance_Case_ID__c =: caseId order by createdDate desc];
                if(!CList.isEmpty()){
                    CList[0].New_PF__c = oCase.New_Panel_Financier__c ;
                    update CList[0];
                }
                
                output.put('success', true);
            }
        }
    }
}