force-app/main/default/objects/Account/fields/Final_Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Final_Application_Status__c</fullName>
    <description>VHF-1180</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Final Application Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to support a many to many relationship between a person account and an application.</description>
    <label>Applicant</label>
    <nameField>
        <displayFormat>Applicant - {0000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/IndividualApplication__c.field-meta.xml
<CustomField>
    <fullName>IndividualApplication__c</fullName>
    <label>Individual Application</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract/fields/IndividualApplicationId__c.field-meta.xml
<CustomField>
    <fullName>IndividualApplicationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provisional Application ID</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Final Applications</relationshipLabel>
    <relationshipName>Contracts_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VGSODataShare.cls
/**
* Class Name  : VGSODataShare
* Methods     : shareRecords 
* @author       Sourabh Singh
* @version      $Revision: 1.0 $, $Date: 28/Sep/2021
*/
public class VGSODataShare 
{
    @InvocableMethod
    public static void shareRecords (List<Id> finalAppIds)
    {
        Map<Id,String> provAppIdtoFinalStatus = new Map<Id,String>();
        Map<Id,String> mapAccIdtoFinalAppStatus = new Map<Id,String>();
        List<id> provAppIds = new List<Id>();
        system.debug('finalAppIds='+finalAppIds);
        try
        {
            for(contract finalApp : [select Id,IndividualApplicationId__c,Status 
                                     FROM Contract where id in:finalAppIds])
            {
                provAppIds.add(finalApp.IndividualApplicationId__c);
                provAppIdtoFinalStatus.put(finalApp.IndividualApplicationId__c,finalApp.Status);
            }
            for(Applicant__c a:[select Account__c, IndividualApplication__c 
                                from Applicant__c 
                                where IndividualApplication__c in :provAppIds])
            {
                mapAccIdtoFinalAppStatus.put(a.Account__c,provAppIdtoFinalStatus.get(a.IndividualApplication__c));
            }
            
            //update person accounts for VGSO sharing rule 
            List<Account> accList = [select Id, Final_Application_Status__c from Account 
                                     where id in:mapAccIdtoFinalAppStatus.keySet()];
            for (Account a : accList) 
            {
                a.Final_Application_Status__c = mapAccIdtoFinalAppStatus.get(a.id);
            } 
            if(!accList.isEmpty())
                update accList;
        }catch(Exception e)
        {
            System.debug('Error in VGSODataShare:'+ e);
        }
        
    }
}