force-app/main/default/objects/Account/fields/Final_Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Final_Application_Status__c</fullName>
    <description>VHF-1180</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Final Application Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Panel_Finance_Officer__c.field-meta.xml
<CustomField>
    <fullName>Panel_Finance_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>VHF-3105</description>
    <label>Panel Finance Officer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Contact)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <description>Financial Planner or Lender</description>
    <label>Business</label>
</RecordType>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to support a many to many relationship between a person account and an application.</description>
    <label>Applicant</label>
    <nameField>
        <displayFormat>Applicant - {0000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/IndividualApplication__c.field-meta.xml
<CustomField>
    <fullName>IndividualApplication__c</fullName>
    <label>Individual Application</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>VHF-1712</description>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <description>sub status specific to victorian homebuyer fund</description>
    <label>Sub Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Notification Sent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/ApplicationCaseId__c.field-meta.xml
<CustomField>
    <fullName>ApplicationCaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Final Applications</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Folio__c.field-meta.xml
<CustomField>
    <fullName>Folio__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Folio</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/IndividualApplicationId__c.field-meta.xml
<CustomField>
    <fullName>IndividualApplicationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provisional Application ID</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Final Applications</relationshipLabel>
    <relationshipName>Contracts_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Loan_Term_Years__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term_Years__c</fullName>
    <inlineHelpText>Loan Term Should be between 2 - 30 years</inlineHelpText>
    <label>Loan Term (Years)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Lot_Number__c.field-meta.xml
<CustomField>
    <fullName>Lot_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Lot Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Panel_Finance_Officer__c.field-meta.xml
<CustomField>
    <fullName>Panel_Finance_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel Finance Officer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Final Applications</relationshipLabel>
    <relationshipName>Final_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Plan_Number__c.field-meta.xml
<CustomField>
    <fullName>Plan_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <label>Volume</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Final_Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Final_Application_Status__c</fullName>
    <description>VHF-1180</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Final Application Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Lender_Account__c.field-meta.xml
<CustomField>
    <fullName>Lender_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel Financier Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individual Applications</relationshipLabel>
    <relationshipName>Individual_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Panel_Finance_Officer__c.field-meta.xml
<CustomField>
    <fullName>Panel_Finance_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel Finance Officer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Individual Applications</relationshipLabel>
    <relationshipName>Individual_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/ContractTriggerHelperTest.cls
/*
* Contract Trigger 
* Author: 
** Version History ** 
Create Date:
Modified: Sourabh Singh, 11/Oct/2021, VHF-2596  
             added testSetup method 
             fixed test class errors
             added coverage for 'validateStatusBeforeUpdate'
*/ 

@isTest(SeeAllData=FALSE)
public class ContractTriggerHelperTest {
    
    private static final Decimal CONST_MEDICARE_NUM = Decimal.valueOf('21234567080');
    private static final Decimal CONST_CARD_NUM = Decimal.valueOf('212345670');
    private static final Decimal CONST_REF_NUM = Decimal.valueOf('1');
    private static final String PROFILE = 'VHF Lender Community Plus User';
    private static final Id PERSONACCOUNT_RECORDTYPEID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
    private static final Id BUSINESSACCOUNT_RECORDTYPEID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
    private static final Id STANDARDCONTACT_RECORDTYPEID = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Contact').getRecordTypeId();
    @TestSetup
    private static void setup() {
        
        UserRole customRole = new UserRole(DeveloperName = 'CustomRole', Name = 'Custom Role');
        insert customRole;
        
        User userWithARole = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            firstName = 'Role',
            LastName = 'User',
            Email = 'testSysAdUser@test.com',
            Username = 'testSysAdUser@test.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'Australia/Sydney',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_AU',
            UserRoleId = customRole.Id
        );
        insert userWithARole;
        
        user sysAdUser = [SELECT Id FROM user WHERE Email = 'testSysAdUser@test.com'];
        System.runAs(sysAdUser) {
            
            Account oOzBankRecord = new Account(
                Name = 'Oz Bank',
                ownerId= sysAdUser.id,
                recordtypeid = BUSINESSACCOUNT_RECORDTYPEID
            );
            insert oOzBankRecord;
            
            Contact oContact = new Contact(
                FirstName='lender',
                LastName='officer1',
                Email = 'lender.Officer1@getnada.com',
                Phone = '+61 2 9311 1111',
                AccountId = oOzBankRecord.Id,
                recordtypeid = STANDARDCONTACT_RECORDTYPEID
            );
            insert oContact;
            
            Profile communityProfile = [SELECT Id FROM profile WHERE Name = :PROFILE Limit 1];
            User comPortalUser = new User();
            comPortalUser.ContactId = oContact.Id;
            comPortalUser.Username = oContact.Email;
            comPortalUser.Email = oContact.Email;
            comPortalUser.LastName = oContact.LastName;
            comPortalUser.CommunityNickname = oContact.LastName + '_' + System.currentTimeMillis();
            comPortalUser.Alias = string.valueOf(oContact.LastName.substring(0,1) + Math.random() ).substring(0,5);
            comPortalUser.TimeZoneSidKey = 'Australia/Sydney';
            comPortalUser.LocaleSidKey = 'en_AU';
            comPortalUser.EmailEncodingKey = 'ISO-8859-1';
            comPortalUser.ProfileId = communityProfile.Id;
            comPortalUser.LanguageLocaleKey = 'en_US';
            comPortalUser.IsActive = true;
            insert comPortalUser;
            
            Account oApplicantPersonAccountRecord = new Account();
            oApplicantPersonAccountRecord.MedicareNumber__pc = CONST_MEDICARE_NUM;
            oApplicantPersonAccountRecord.Medicare_Card_Number__pc = CONST_CARD_NUM;
            oApplicantPersonAccountRecord.Medicare_Reference_Number__pc = CONST_REF_NUM;
            oApplicantPersonAccountRecord.IsActiveApplicant__pc = 'Yes';
            oApplicantPersonAccountRecord.RecordTypeId = PERSONACCOUNT_RECORDTYPEID;
            oApplicantPersonAccountRecord.PersonEmail = 'test@email.com.invalid';
            oApplicantPersonAccountRecord.LastName = 'TestLastName';
            oApplicantPersonAccountRecord.PersonMailingCity = 'TestCity';
            oApplicantPersonAccountRecord.PersonMailingState = 'Victoria';
            oApplicantPersonAccountRecord.PersonMailingStreet = 'TestStreetVictoria';
            
            
            
            oApplicantPersonAccountRecord.PersonMailingPostalCode = '3000';
            insert oApplicantPersonAccountRecord;
            System.debug('*** Results: ' + oApplicantPersonAccountRecord);
            
            Case applicationCase = new Case();
            applicationCase.AccountId = oApplicantPersonAccountRecord.Id;
            applicationCase.Status = 'Submitted';
            applicationCase.Sub_Status__c = 'Pending';
            applicationCase.Subject = 'TestLastName - Vic Housing Fund Application';
            insert applicationCase;
            
            RegulatoryAuthorizationType authType = new RegulatoryAuthorizationType(
                Name = 'Victorian Homebuyer Fund',
                RegulatoryAuthCategory = 'License'
            );
            insert authType;
            
            IndividualApplication oIndividualApplication = new IndividualApplication();
            oIndividualApplication.AccountId = oApplicantPersonAccountRecord.Id;
            oIndividualApplication.ApplicationCaseId = applicationCase.Id;
            oIndividualApplication.Category = 'Grant';
            //oIndividualApplication.Status = 'Provisional Application Submitted';
            oIndividualApplication.Status = 'Draft';
            oIndividualApplication.AppliedDate = Date.today();
            oIndividualApplication.LicenseTypeId = authType.Id;
            oIndividualApplication.Lender_Account__c = oOzBankRecord.Id;
            oIndividualApplication.Panel_Finance_Officer__c = oContact.Id;
            oIndividualApplication.Final_Application_Status__c = '';
            insert oIndividualApplication;
            
            Applicant__c oApplicant = new Applicant__c();
            oApplicant.Account__c = oApplicantPersonAccountRecord.Id;
            oApplicant.IndividualApplication__c = oIndividualApplication.Id;
            insert oApplicant;
            
            Contract finalApp = new Contract();
            finalApp.IndividualApplicationId__c = oIndividualApplication.Id;
            finalApp.AccountId = oApplicantPersonAccountRecord.Id;
            finalApp.Status = 'draft';
            finalApp.ApplicationCaseId__c = applicationCase.Id; 
            finalApp.Loan_Term_Years__c = 28;
            finalApp.Lot_Number__c = '1';
            finalApp.Plan_Number__c = 'PS832324H';
            finalApp.Folio__c = '1';
            finalApp.Volume__c = 1;
            finalApp.Panel_Finance_Officer__c = oContact.Id;
            insert finalApp;            
        }
        
    }
    
    public static testMethod void ValidatePlanLotFolioVolumeTestNegativeCase()
        
    {
        IndividualApplication ia = [select id, Final_Application_Status__c from IndividualApplication limit 1 ];
        List<Contract>lstContract = [SELECT Id,Lot_Number__c, Volume__c, Plan_Number__c,Folio__c FROM Contract]; 
        Test.startTest();
        ContractTriggerHelper.ValidatePlanLotFolioVolume(lstContract);  
        Test.stopTest(); 
        
    }
    public static testMethod void ValidatePlanLotFolioVolumeTestPositiveCase()
        
    {
        IndividualApplication ia = [select id, Final_Application_Status__c from IndividualApplication limit 1 ];
        List<Contract> lstContract = [SELECT Id,Lot_Number__c, Volume__c, Plan_Number__c,Folio__c FROM Contract]; 
        Test.startTest();
        ContractTriggerHelper.ValidatePlanLotFolioVolume(lstContract);  
        Test.stopTest(); 
        
    }
    
    public static testMethod void UpdateFolioSuffixToUpperCaseTestSuccess()
        
    {
        IndividualApplication ia = [select id, Final_Application_Status__c from IndividualApplication limit 1 ];
        List<Contract> lstContract = [SELECT Id,Lot_Number__c, Volume__c, Plan_Number__c,Folio__c FROM Contract];
        Test.startTest();
        System.assertEquals('1', lstContract[0].Folio__c);
        System.assertEquals('PS832324H', lstContract[0].Plan_Number__c);
        Test.stopTest(); 
        
    }
    
    public static testMethod void testValidateStatusBeforeUpdate()
    {
        IndividualApplication ia = [select id, Final_Application_Status__c from IndividualApplication limit 1 ];
        List<Contract> lstContract = [SELECT Id,Lot_Number__c, Volume__c, Plan_Number__c,Folio__c,status,BypassValidation__c FROM Contract]; 
        test.startTest();
        ContractTriggerHelper.validateStatusBeforeUpdate(lstContract); 
        test.stopTest();        
    }
}