force-app/main/default/objects/Account/fields/Panel_Finance_Officer__c.field-meta.xml
<CustomField>
    <fullName>Panel_Finance_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>VHF-3105</description>
    <label>Panel Finance Officer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Contact)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <description>Financial Planner or Lender</description>
    <label>Business</label>
</RecordType>

force-app/main/default/objects/Annual_Review__c/Annual_Review__c.object-meta.xml
<CustomObject>
    <description>Stores the responses to questions that participants to the VHF scheme need to complete on an annual basis</description>
    <label>Annual Review</label>
    <nameField>
        <displayFormat>AR-{0000000000}</displayFormat>
        <label>Annual Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Reviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Submission</fullName>
                <default>true</default>
                <label>Awaiting Submission</label>
            </value>
            <value>
                <fullName>Awaiting Verification</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to support a many to many relationship between a person account and an application.</description>
    <label>Applicant</label>
    <nameField>
        <displayFormat>Applicant - {0000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/IndividualApplication__c.field-meta.xml
<CustomField>
    <fullName>IndividualApplication__c</fullName>
    <label>Individual Application</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case/fields/Individual_Application__c.field-meta.xml
<CustomField>
    <fullName>Individual_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual Application</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Individual_Application_Shadow__c.field-meta.xml
<CustomField>
    <fullName>Individual_Application_Shadow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Introduced with VHF-97 to access expiry date from the case object</description>
    <label>Individual_Application_Shadow</label>
    <referenceTo>Individual_Application_Shadow__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <description>sub status specific to victorian homebuyer fund</description>
    <label>Sub Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Notification Sent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/ApplicationCaseId__c.field-meta.xml
<CustomField>
    <fullName>ApplicationCaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Final Applications</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Folio__c.field-meta.xml
<CustomField>
    <fullName>Folio__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Folio</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/IndividualApplicationId__c.field-meta.xml
<CustomField>
    <fullName>IndividualApplicationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provisional Application ID</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Final Applications</relationshipLabel>
    <relationshipName>Contracts_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Loan_Term_Years__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term_Years__c</fullName>
    <inlineHelpText>Loan Term Should be between 2 - 30 years</inlineHelpText>
    <label>Loan Term (Years)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Lot_Number__c.field-meta.xml
<CustomField>
    <fullName>Lot_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Lot Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Panel_Finance_Officer__c.field-meta.xml
<CustomField>
    <fullName>Panel_Finance_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel Finance Officer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Final Applications</relationshipLabel>
    <relationshipName>Final_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Panel_Financier_Name__c.field-meta.xml
<CustomField>
    <fullName>Panel_Financier_Name__c</fullName>
    <formula>Panel_Finance_Officer__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Panel Financier Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Plan_Number__c.field-meta.xml
<CustomField>
    <fullName>Plan_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <label>Volume</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Individual_Application_Shadow__c/Individual_Application_Shadow__c.object-meta.xml
<CustomObject>
    <label>Individual_Application_Shadow</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Individual_Application_Shadow Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shadow Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individual_Application_Shadow__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shadow Applications</relationshipLabel>
    <relationshipName>Shadow_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individual_Application_Shadow__c/fields/Individual_Application__c.field-meta.xml
<CustomField>
    <fullName>Individual_Application__c</fullName>
    <label>Individual Application</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Shadow Applications</relationshipLabel>
    <relationshipName>Shadow_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individual_Application_Shadow__c/fields/Panel_Financier_Name__c.field-meta.xml
<CustomField>
    <fullName>Panel_Financier_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Panel Financier Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Individual_Application_Shadow__c.field-meta.xml
<CustomField>
    <fullName>Individual_Application_Shadow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual_Application_Shadow</label>
    <referenceTo>Individual_Application_Shadow__c</referenceTo>
    <relationshipLabel>Provisional Applications</relationshipLabel>
    <relationshipName>Provisional_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Lender_Account__c.field-meta.xml
<CustomField>
    <fullName>Lender_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel Financier Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individual Applications</relationshipLabel>
    <relationshipName>Individual_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Panel_Finance_Officer__c.field-meta.xml
<CustomField>
    <fullName>Panel_Finance_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel Finance Officer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Individual Applications</relationshipLabel>
    <relationshipName>Individual_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Folio__c.field-meta.xml
<CustomField>
    <fullName>Folio__c</fullName>
    <description>Folio</description>
    <formula>Contract.Folio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Folio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Lot_Number__c.field-meta.xml
<CustomField>
    <fullName>Lot_Number__c</fullName>
    <description>Lot Number</description>
    <formula>Contract.Lot_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lot Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Panel_Financier_Name__c.field-meta.xml
<CustomField>
    <fullName>Panel_Financier_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Panel Financier for which the property is currently being financed by</description>
    <label>Panel Financier Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Plan_Number__c.field-meta.xml
<CustomField>
    <fullName>Plan_Number__c</fullName>
    <description>Plan Number</description>
    <formula>Contract.Plan_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plan Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <description>Volume</description>
    <formula>Contract.Volume__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Stores the payment details that a participant need to make as part of post settlement process</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PID-{00000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Panel_Financier_Name__c.field-meta.xml
<CustomField>
    <fullName>Panel_Financier_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel Financier Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments (Panel Financier Name)</relationshipLabel>
    <relationshipName>Payments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Updated by SRO Officer</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Payment Registered</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Request Expired</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
                <isActive>false</isActive>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Requested</fullName>
                <isActive>false</isActive>
                <label>Requested</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VHFTestDataFactory.cls
/*
* Desription: TestData Factory for the Test Class Data Setup 
* Author: Lavanya Kavuri (lkavuri@salesforce.com)
** Version History ** 
Created: Date: Oct-13-2021
*******************************************************************************************/
/* MODIFICATION LOG
 * Version          Developer          Date               Description
 *-------------------------------------------------------------------------------------------
 *  1.1             Arjun Singh        20/01/2022          Added method for Annual Review Creation
 */
public class VHFTestDataFactory {
  //Medicare Number 1
  private static final Decimal CONST_MEDICARE_NUM = Decimal.valueOf(
    '21234567080'
  );
  private static final Decimal CONST_CARD_NUM = Decimal.valueOf('212345670');
  private static final Decimal CONST_REF_NUM = Decimal.valueOf('1');

  /*
   * Account Methods
   */

  //Create Lender Account - RecordType: Business
  public static Account createLenderAccount(String name) {
    //Get the lender recordType Id
    Id lenderRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
      .get('Business')
      .getRecordTypeId();

    Account accRec = new Account();
    accRec.Name = name;
    accRec.RecordTypeId = lenderRecordTypeId;

    return accRec;
  }

  public static Account createApplicantPersonAccountWithDetails(
    String isActive,
    String firstName,
    String lastName,
    String email
  ) {
    //Get the Primary Participant RecordType Id
    Id primaryPartRecordId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
      .get('PersonAccount')
      .getRecordTypeId();
    Account newPrimaryRec = new Account();
    newPrimaryRec.MedicareNumber__pc = CONST_MEDICARE_NUM;
    newPrimaryRec.Medicare_Card_Number__pc = CONST_CARD_NUM;
    newPrimaryRec.Medicare_Reference_Number__pc = CONST_REF_NUM;
    newPrimaryRec.FirstName = firstName;
    newPrimaryRec.PersonEmail = email;
    newPrimaryRec.LastName = lastName;
    //newPrimaryRec.Primary_Participant__pc = isPrimary;
    newPrimaryRec.IsActiveApplicant__pc = isActive;
    newPrimaryRec.PersonMailingCity = 'Melbourne';
    newPrimaryRec.PersonMailingPostalCode = '3000';
    newPrimaryRec.PersonMailingState = 'Victoria';
    newPrimaryRec.PersonMailingStreet = '150 Collins Street';
    newPrimaryRec.PersonMailingCountry = 'Australia';

    return newPrimaryRec;
  }

  //Create Primary Participant Account  - RecordType: PersonAccount
  public static Account createApplicantPersonAccount(String isActive) {
    //Get the Primary Participant RecordType Id
    Id primaryPartRecordId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
      .get('PersonAccount')
      .getRecordTypeId();
    Account newPrimaryRec = new Account();
    newPrimaryRec.MedicareNumber__pc = CONST_MEDICARE_NUM;
    newPrimaryRec.Medicare_Card_Number__pc = CONST_CARD_NUM;
    newPrimaryRec.Medicare_Reference_Number__pc = CONST_REF_NUM;
    newPrimaryRec.PersonEmail = 'test@email.com.invalid';
    newPrimaryRec.LastName = 'TestLastName';
    //newPrimaryRec.Primary_Participant__pc = isPrimary;
    newPrimaryRec.IsActiveApplicant__pc = isActive;
    newPrimaryRec.PersonMailingCity = 'Melbourne';
    newPrimaryRec.PersonMailingPostalCode = '3000';
    newPrimaryRec.PersonMailingState = 'Victoria';
    newPrimaryRec.PersonMailingStreet = '150 Collins Street';
    newPrimaryRec.PersonMailingCountry = 'Australia';
    newPrimaryRec.IsActiveApplicant__pc = 'Yes';
    newPrimaryRec.Is_Participant__pc = true;
    return newPrimaryRec;
  }

  /*
   * Contact Methods
   */

  //Create Contact for Lender Account
  public static Contact createLenderContact(
    Id accountId,
    String firstName,
    String lastName,
    String email,
    String phone
  ) {
    Id standardRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName()
      .get('Contact')
      .getRecordTypeId();

    Contact newConRec = new Contact();
    newConRec.AccountId = accountId;
    newConRec.FirstName = firstName;
    newConRec.LastName = lastName;
    newConRec.Email = email;
    newConRec.Phone = phone;
    newConRec.RecordTypeId = standardRecordTypeId;

    return newConRec;
  }

  /*
   * Case Methods
   */

  public static Case createCase(
    String participantAcctId,
    String status,
    String subStatus,
    String recordTypeId
  ) {
    Case newAppCase = new Case();
    newAppCase.RecordTypeId = recordTypeId;
    newAppCase.AccountId = participantAcctId;
    newAppCase.Status = status;
    newAppCase.Sub_Status__c = subStatus;
    newAppCase.Subject = 'Test case for application - Vic house funding';

    return newAppCase;
  }

  /*
   * Provisional Application Methods
   */

  //Create Provisional Application - Depdens on Regulatory Authorization Type. So, we need to create that first

  //Create Regulatory Authorization Type
  public static RegulatoryAuthorizationType createRegAuth(
    String name,
    String authType
  ) {
    RegulatoryAuthorizationType newRegAuth = new RegulatoryAuthorizationType();
    newRegAuth.Name = name;
    newRegAuth.RegulatoryAuthCategory = authType;
    return newRegAuth;
  }

  //Create Comprehensive Provisional Application  - With all the fields
  public static IndividualApplication createProvisionalApplication(
    String licenseId,
    String lenderAcctId,
    String panelOfficerId,
    String participantAcctId,
    String caseId
  ) {
    IndividualApplication newProvApp = new IndividualApplication();
    newProvApp.AccountId = participantAcctId;
    newProvApp.ApplicationCaseId = caseId;
    newProvApp.Category = 'Grant';
    newProvApp.Status = 'Draft';
    newProvApp.AppliedDate = Date.today();
    newProvApp.LicenseTypeId = licenseId;
    newProvApp.Lender_Account__c = lenderAcctId;
    newProvApp.Panel_Finance_Officer__c = panelOfficerId;
    return newProvApp;
  }

  //Create simple Provisional Application - With Few Fields
  public static IndividualApplication createSimpleProvApp(
    String licenseId,
    String status,
    Date appliedDate
  ) {
    IndividualApplication newSimpleApp = new IndividualApplication();
    newSimpleApp.LicenseTypeId = licenseId;
    newSimpleApp.Status = status;
    newSimpleApp.AppliedDate = appliedDate;
    return newSimpleApp;
  }

  //Create Provisional Application Shadow
  public static Individual_Application_Shadow__c createProvAppShadow(
    Id provAppId
  ) {
    Individual_Application_Shadow__c shadowApplication = new Individual_Application_Shadow__c();
    shadowApplication.Individual_Application__c = provAppId;
    return shadowApplication;
  }

  //Create Applicant

  public static Applicant__c createApplicant(
    String participantId,
    String applicationId
  ) {
    Applicant__c newApplicant = new Applicant__c();
    newApplicant.Account__c = participantId;
    newApplicant.IndividualApplication__c = applicationId;

    return newApplicant;
  }

  //Create Final Application

  public static Contract createFinalApplication(
    String provAppId,
    string participantAcctId,
    String status,
    String caseId,
    Integer loanterm,
    string lotnum,
    string plannum,
    string folio,
    Decimal volume,
    string panelOfficerId
  ) {
    Contract newFinalApp = new Contract();
    newFinalApp.IndividualApplicationId__c = provAppId;
    newFinalApp.AccountId = participantAcctId;
    newFinalApp.Status = status;
    newFinalApp.ApplicationCaseId__c = caseId;
    newFinalApp.Loan_Term_Years__c = loanterm;
    newFinalApp.Lot_Number__c = lotnum;
    newFinalApp.Plan_Number__c = plannum;
    newFinalApp.Folio__c = folio;
    newFinalApp.Volume__c = volume;
    newFinalApp.Panel_Finance_Officer__c = panelOfficerId;

    return newFinalApp;
  }

  //Create Property Record

  public static Order createProperty(
    String accountId,
    String status,
    String panelOfficerId
  ) {
    Order newProperty = new Order();
    newProperty.accountId = accountId;
    newProperty.Status = status;
    newProperty.EffectiveDate = System.today();
    newProperty.Panel_Financier_Name__c = panelOfficerId;

    return newProperty;
  }

  //Create User Methods

  /* Custom Role */
  public static UserRole createCustomRole(
    String roleName,
    String developerName
  ) {
    UserRole newRole = new UserRole();
    newRole.DeveloperName = developerName;
    newRole.Name = roleName;

    return newRole;
  }

  /*Create Admin User with Role */
  public static User createAdminUser(
    String roleId,
    String email,
    String username,
    String firstName,
    String lastName,
    String alias
  ) {
    User newUser = new User();
    newUser.profileId = [
      SELECT Id
      FROM Profile
      WHERE Name = 'System Administrator'
    ]
    .Id;
    newUser.FirstName = firstName;
    newUser.LastName = lastName;
    newUser.Email = email;
    newUser.Username = username + System.currentTimeMillis();
    newUser.CompanyName = 'TESTSRO';
    newUser.Title = 'title';
    newUser.Alias = alias;
    newUser.TimeZoneSidKey = 'Australia/Sydney';
    newUser.EmailEncodingKey = 'ISO-8859-1';
    newUser.LanguageLocaleKey = 'en_US';
    newUser.LocaleSidKey = 'en_AU';
    newUser.UserRoleId = roleId;

    return newUser;
  }

  public static User createInternalUser(
    String roleId,
    String profileId,
    String email,
    String username,
    String firstName,
    String lastName,
    String alias
  ) {
    User newUser = new User();
    newUser.FirstName = firstName;
    newUser.LastName = lastName;
    newUser.Email = email;
    newUser.Username = username + System.currentTimeMillis();
    newUser.CompanyName = 'TESTSRO';
    newUser.Title = 'title';
    newUser.Alias = alias;
    newUser.TimeZoneSidKey = 'Australia/Sydney';
    newUser.EmailEncodingKey = 'ISO-8859-1';
    newUser.LanguageLocaleKey = 'en_US';
    newUser.LocaleSidKey = 'en_AU';
    newUser.UserRoleId = roleId;
    newUser.ProfileId = profileId;

    return newUser;
  }

  public static User createCommunityUser(
    String personContactId,
    String email,
    String lastName,
    String username,
    String nickname,
    String alias,
    String profileId
  ) {
    User comPortalUser = new User();
    comPortalUser.ContactId = personContactId;
    comPortalUser.Username = username;
    comPortalUser.Email = email;
    comPortalUser.LastName = lastName;
    comPortalUser.CommunityNickname = nickname;
    comPortalUser.Alias = alias;
    comPortalUser.TimeZoneSidKey = 'Australia/Sydney';
    comPortalUser.LocaleSidKey = 'en_AU';
    comPortalUser.EmailEncodingKey = 'ISO-8859-1';
    comPortalUser.ProfileId = profileId;
    comPortalUser.LanguageLocaleKey = 'en_US';
    comPortalUser.IsActive = true;

    return comPortalUser;
  }

  //Payment Creation Methods
  public static Payment__c createPayment(
    String status,
    String caseId,
    String applicantAcctId
  ) {
    Payment__c newPayment = new Payment__c();
    newPayment.Status__c = status;
    newPayment.Amount__c = 25000;
    newPayment.Case__c = caseId;
    newPayment.Primary_Participant__c = applicantAcctId;
    newPayment.Requested_Date__c = System.today();

    return newPayment;
  }

  public static Annual_Review__c createAnnualReview(
    String propertyId,
    String primaryParticipantId,
    date annualReviewStartDate,
    date annualReviewEndDate
  ) {
    Annual_Review__c annualReview = new Annual_Review__c();
    annualReview.Property__c = propertyId;
    annualReview.Primary_Participant__c = primaryParticipantId;
    annualReview.Annual_Review_Start_Date__c = annualReviewStartDate;
    annualReview.Annual_Review_End_Date__c = annualReviewEndDate;

    return annualReview;
  }
}