force-app/main/default/objects/Account/fields/Panel_Finance_Officer__c.field-meta.xml
<CustomField>
    <fullName>Panel_Finance_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>VHF-3105</description>
    <label>Panel Finance Officer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Contact)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to support a many to many relationship between a person account and an application.</description>
    <label>Applicant</label>
    <nameField>
        <displayFormat>Applicant - {0000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>VHF-1712</description>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Individual_Application_Shadow__c.field-meta.xml
<CustomField>
    <fullName>Individual_Application_Shadow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Introduced with VHF-97 to access expiry date from the case object</description>
    <label>Individual_Application_Shadow</label>
    <referenceTo>Individual_Application_Shadow__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/VHF_Application_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>VHF_Application_Record_Type</fullName>
    <active>true</active>
    <businessProcess>VHF Application Support Process</businessProcess>
    <label>VHF Applications</label>
</RecordType>

force-app/main/default/objects/Contract/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/IndividualApplicationId__c.field-meta.xml
<CustomField>
    <fullName>IndividualApplicationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provisional Application ID</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Final Applications</relationshipLabel>
    <relationshipName>Contracts_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Panel_Finance_Officer__c.field-meta.xml
<CustomField>
    <fullName>Panel_Finance_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel Finance Officer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Final Applications</relationshipLabel>
    <relationshipName>Final_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individual_Application_Shadow__c/Individual_Application_Shadow__c.object-meta.xml
<CustomObject>
    <label>Individual_Application_Shadow</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Individual_Application_Shadow Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shadow Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individual_Application_Shadow__c/fields/First_Extension_Requested__c.field-meta.xml
<CustomField>
    <fullName>First_Extension_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Copy field value from Individual Application</description>
    <label>First Extension Requested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individual_Application_Shadow__c/fields/Second_Extension_Requested__c.field-meta.xml
<CustomField>
    <fullName>Second_Extension_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Second Extension Requested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Expiry_Date1__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Final_Application_In_Progress_c__c.field-meta.xml
<CustomField>
    <fullName>Final_Application_In_Progress_c__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final Application in Progress</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/First_Extension_Requested__c.field-meta.xml
<CustomField>
    <fullName>First_Extension_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The checkbox is an indicator for 1st extension of Provisional Application</description>
    <label>First Extension Requested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Hard_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Hard_Expiry_Date__c</fullName>
    <description>This date holds the final date beyond which no application can or should be extended.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Hard Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Individual_Application_Shadow__c.field-meta.xml
<CustomField>
    <fullName>Individual_Application_Shadow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual_Application_Shadow</label>
    <referenceTo>Individual_Application_Shadow__c</referenceTo>
    <relationshipLabel>Provisional Applications</relationshipLabel>
    <relationshipName>Provisional_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Panel_Finance_Officer__c.field-meta.xml
<CustomField>
    <fullName>Panel_Finance_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel Finance Officer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Individual Applications</relationshipLabel>
    <relationshipName>Individual_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Second_Extension_Requested__c.field-meta.xml
<CustomField>
    <fullName>Second_Extension_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The second Expiry date extension indicator.</description>
    <label>Second Extension Requested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CalculateProvisionalExpiryDatesTest.cls
@isTest
private class CalculateProvisionalExpiryDatesTest {
/*******************************************************************************************
* @Name         CalculateProvisionalExpiryDatesTest 
* @Author       Nayana Revanna
* @Date         07/09/2021
* @Description  This class is the test class of CalculateProvisionalExpiryDates Class
*******************************************************************************************/ 
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*  1.1              Lavanya Kavuri     25/11/2021          Fixed the Test Class                                                     
*******************************************************************************************/

@TestSetup
static void setup(){
    
    UserRole newCustomRole = VHFTestDataFactory.createCustomRole('CustomRole', 'CustomRole');
    insert newCustomRole;

    User newAdminUser = VHFTestDataFactory.createAdminUser(newCustomRole.Id, 'testSysAdminUser@test.com', 'testSysAdminUser@test.com', 'testuser', 'admin', 'testad');
    insert newAdminUser;

    User adminUser = [Select Id from User where Email = 'testSysAdminUser@test.com'];

    EmailTemplate validEmailTemplate = new EmailTemplate();
    validEmailTemplate.isActive = true;
    validEmailTemplate.Name = 'name';
    validEmailTemplate.DeveloperName = 'unique_name_addSomethingSpecialHere';
    validEmailTemplate.TemplateType = 'text';
    validEmailTemplate.FolderId = UserInfo.getUserId();

    insert validEmailTemplate;

    System.runAs(adminUser)
    {
        Account bankAccount = VHFTestDataFactory.createLenderAccount('Oz Bank');
        insert bankAccount;

        Contact lenderContact = VHFTestDataFactory.createLenderContact(bankAccount.Id, 'lender', 'officer', 'lender.officer@ozbanktest.com', '+61 2 9311 1111');
        insert lenderContact;

        Account applicantAccount = VHFTestDataFactory.createApplicantPersonAccount('Yes');
        insert applicantAccount;

        Id applicationCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('VHF_Application_Record_Type').getRecordTypeId();
        Case applicationCase = VHFTestDataFactory.createCase(applicantAccount.Id, 'Submitted', 'Pending', applicationCaseRecordTypeId);
        insert applicationCase;

        RegulatoryAuthorizationType authType = VHFTestDataFactory.createRegAuth('Victorian Homebuyer Fund', 'License');
        insert authType;

        IndividualApplication newApplication = VHFTestDataFactory.createProvisionalApplication(authType.Id, bankAccount.Id, lenderContact.Id, applicantAccount.Id, applicationCase.Id);
        insert newApplication;
        
        Individual_Application_Shadow__c NewShadowOBJInst= VHFTestDataFactory.createProvAppShadow(newApplication.Id);
        insert NewShadowOBJInst;
        
        Applicant__c newApplicant = VHFTestDataFactory.createApplicant(applicantAccount.Id, newApplication.Id);
        insert newApplicant;

        Contract newFinalApplication = VHFTestDataFactory.createFinalApplication(newApplication.Id, applicantAccount.Id, 'draft', applicationCase.Id, 28, '1', 'PS832324H', '1', 1, lenderContact.Id);
        insert newFinalApplication;
    }
    
}

@isTest private static void reqDateMoreThanSoftExp() {
    
    IndividualApplication app = [Select Id from IndividualApplication LIMIT 1];
    Contract finalApp = [Select Id from Contract where IndividualApplicationId__c =: app.Id];

    EmailTemplate validEmailTemplate = [Select Id from EmailTemplate LIMIT 1];
   
    //Update applications 
    IndividualApplication updateApplication = [Select Id,Panel_Finance_Officer__c,First_Extension_Requested__c,Second_Extension_Requested__c,Expiry_Date1__c, Hard_Expiry_Date__c from IndividualApplication WHERE Id =: app.Id]; 
    
    emailmessage em = new emailmessage();
    em.fromaddress = 'Test@test.com';
    em.toaddress = 'test1@test.com';
    em.subject = 'Test Email';
    em.textbody = 'testing';
    em.EmailTemplateId = validEmailTemplate.Id;
    em.parentid = updateApplication.id;
    
    
    Date expDate = System.today().addMonths(3);
    updateApplication.Expiry_Date1__c = expDate;
    updateApplication.BypassValidation__c = true;
    updateApplication.status = 'Provisionally Approved';
    updateApplication.Final_Application_In_Progress_c__c = false;
    updateApplication.First_Extension_Requested__c = false;
    updateApplication.Second_Extension_Requested__c = false;

    Integer emailCountOriginal = Limits.getEmailInvocations();
    Test.startTest();
   
        update updateApplication; 

    //Convert to List of Ids 
    List<Id> appUpdateIds = new List<Id>(); 
    appUpdateIds.add(updateApplication.Id); 

    //Set expirys 
    ProvisionalApplication.setExpiry(appUpdateIds);
    String dateExt = CalculateProvisionalExpiryDates.calculateExpDate(updateApplication.Id);
    CalculateProvisionalExpiryDates.saveNewExpiryDate(Date.valueOf(dateExt), updateApplication.Id);
    
 
    Date dtAssert= Date.valueOf(dateExt);
    System.assertEquals(dateExt, String.valueOf(dtAssert));
    Test.stopTest();

    Integer emailCountAfter = Limits.getEmailInvocations();
    
    
}


@isTest private static void softExpMoreThanReqDateTest() {
    
    Test.startTest();
    IndividualApplication app = [Select Id from IndividualApplication LIMIT 1];
   
    //Update applications 
    IndividualApplication updateApplication = [Select Id,First_Extension_Requested__c,Second_Extension_Requested__c,Expiry_Date1__c, Hard_Expiry_Date__c from IndividualApplication WHERE Id =: app.Id]; 
    Date expDate = System.today().addMonths(3);
    updateApplication.Expiry_Date1__c = expDate;
    updateApplication.status = 'Provisionally Approved';
    updateApplication.Final_Application_In_Progress_c__c = false;
    updateApplication.First_Extension_Requested__c = true;
    updateApplication.Second_Extension_Requested__c = false;
    update updateApplication; 

    //Convert to List of Ids 
    List<Id> appUpdateIds = new List<Id>(); 
    appUpdateIds.add(updateApplication.Id); 

    //Set expirys 
    ProvisionalApplication.setExpiry(appUpdateIds);
    String dateExt = CalculateProvisionalExpiryDates.calculateExpDate(updateApplication.Id);
    CalculateProvisionalExpiryDates.saveNewExpiryDate(Date.valueOf(dateExt), updateApplication.Id);
    
 
    Date dtAssert= Date.valueOf(dateExt);
    System.assertEquals(dateExt, String.valueOf(dtAssert));
    Test.stopTest();

    
    
}

@isTest static void testBothExtDone() {
Test.startTest();

    IndividualApplication app = [Select Id from IndividualApplication LIMIT 1];
   
    //Update applications 
    IndividualApplication updateApplication = [Select Id,First_Extension_Requested__c,Second_Extension_Requested__c,Expiry_Date1__c, Hard_Expiry_Date__c from IndividualApplication WHERE Id =: app.Id]; 
    Date expDate = System.Today();
    updateApplication.Expiry_Date1__c = expDate;
    updateApplication.status = 'Provisionally Approved';
    updateApplication.Final_Application_In_Progress_c__c = false;
    updateApplication.Hard_Expiry_Date__c=System.today().addMonths(12);
    update updateApplication; 

    //Convert to List of Ids
    List<Id> appUpdateIds = new List<Id>();
    appUpdateIds.add(updateApplication.Id);

    //Set expirys
    ProvisionalApplication.setExpiry(appUpdateIds);
    String dateExt = CalculateProvisionalExpiryDates.calculateExpDate(updateApplication.Id);
    CalculateProvisionalExpiryDates.saveNewExpiryDate(Date.valueOf(dateExt), updateApplication.Id);
 
    Date dtAssert= Date.valueOf(dateExt);
       System.assertEquals(dateExt, String.valueOf(dtAssert));
    Test.stopTest();

 
    
}


}