force-app/main/default/objects/Account/fields/Panel_Finance_Officer__c.field-meta.xml
<CustomField>
    <fullName>Panel_Finance_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>VHF-3105</description>
    <label>Panel Finance Officer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Contact)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to support a many to many relationship between a person account and an application.</description>
    <label>Applicant</label>
    <nameField>
        <displayFormat>Applicant - {0000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Aboriginal_Applicants__c.field-meta.xml
<CustomField>
    <fullName>Aboriginal_Applicants__c</fullName>
    <formula>Individual_Application_Shadow__r.Aboriginal_Applicants__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Aboriginal Applicants</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>VHF-1712</description>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Scheduled_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Settlement_Status__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Status__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upcoming settlement</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Overdue settlement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/VHF_Application_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>VHF_Application_Record_Type</fullName>
    <active>true</active>
    <businessProcess>VHF Application Support Process</businessProcess>
    <label>VHF Applications</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Aboriginal_Applicants__c.field-meta.xml
<CustomField>
    <fullName>Aboriginal_Applicants__c</fullName>
    <formula>IndividualApplicationId__r.Aboriginal_Applicants__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Aboriginal Applicants</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ApplicantNames__c.field-meta.xml
<CustomField>
    <fullName>ApplicantNames__c</fullName>
    <formula>IndividualApplicationId__r.ApplicantNames__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Names</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ApplicationCaseId__c.field-meta.xml
<CustomField>
    <fullName>ApplicationCaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Final Applications</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Folio__c.field-meta.xml
<CustomField>
    <fullName>Folio__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Folio</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/IndividualApplicationId__c.field-meta.xml
<CustomField>
    <fullName>IndividualApplicationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provisional Application ID</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Final Applications</relationshipLabel>
    <relationshipName>Contracts_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Lot_Number__c.field-meta.xml
<CustomField>
    <fullName>Lot_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Lot Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Panel_Finance_Officer__c.field-meta.xml
<CustomField>
    <fullName>Panel_Finance_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel Finance Officer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Final Applications</relationshipLabel>
    <relationshipName>Final_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Plan_Number__c.field-meta.xml
<CustomField>
    <fullName>Plan_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Scheduled_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Settlement_Date__c</fullName>
    <description>Holds the scheduled date for settlement</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Date__c</fullName>
    <description>Scheduled Settlement Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>1.Must be later than Today&apos;s date.

2.If scheduled settlement date is less than 5 working days, then turnaround times may be more.</inlineHelpText>
    <label>Scheduled Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <label>Volume</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Aboriginal_Applicants__c.field-meta.xml
<CustomField>
    <fullName>Aboriginal_Applicants__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If any of the applicants is an aboriginal person</description>
    <label>Aboriginal or Torres Strait Islander</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/ApplicantNames__c.field-meta.xml
<CustomField>
    <fullName>ApplicantNames__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Applicant Names</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Panel_Finance_Officer__c.field-meta.xml
<CustomField>
    <fullName>Panel_Finance_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel Finance Officer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Individual Applications</relationshipLabel>
    <relationshipName>Individual_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PopulateSchSettlementDateOnCaseTest.cls
/*******************************************************************************************
* @Name         PopulateSchSettlementDateOnCaseTest
* @Author       
* @Date         
* @Description  
*******************************************************************************************/
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*  1.0             
*  1.1              Lavanya Kavuri       25/11/2021          Fixing Test Class   
* 1.2				Sourabh		 		26/11/2021	         Fixes errors  	
*******************************************************************************************/
@isTest
public class PopulateSchSettlementDateOnCaseTest {

    @TestSetup
    static void makeData(){
        Id vhfApplicationsCaseRT_Id = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('VHF_Application_Record_Type').getRecordTypeId();
        Account oOzBankRecord = VHFTestDataFactory.createLenderAccount('Oz Bank');
        insert oOzBankRecord;

        Contact oContact = VHFTestDataFactory.createLenderContact(oOzBankRecord.Id, 'lender123', 'officer1', 'lender.Officer112@getnada.com', '+61 2 9311 1111');
        insert oContact;

        Account applicant1 = VHFTestDataFactory.createApplicantPersonAccountWithDetails('Yes', 'app', 'one', 'app.onetwo@apptwo.com');
        insert applicant1;

        Case applicationCase = VHFTestDataFactory.createCase(applicant1.Id, 'Final Approval Requested', 'Pending', vhfApplicationsCaseRT_Id);
        applicationCase.Scheduled_Settlement_Date__c = System.Today();
        applicationCase.BypassValidation__c = true;
        applicationCase.Settlement_Status__c = 'Upcoming Settlement';
        insert applicationCase;
                
        RegulatoryAuthorizationType authType = VHFTestDataFactory.createRegAuth('Victorian HomebuyerFund', 'License');
        insert authType;
                
        IndividualApplication oIndividualApplication = VHFTestDataFactory.createProvisionalApplication(authType.Id, oOzBankRecord.Id, oContact.Id, applicant1.Id, applicationCase.Id );
        insert oIndividualApplication;

        Applicant__c oApplicant1 = VHFTestDataFactory.createApplicant(applicant1.Id, oIndividualApplication.Id);
        insert oApplicant1;

        Contract finalApp = VHFTestDataFactory.createFinalApplication(oIndividualApplication.Id, applicant1.Id, 'draft', applicationCase.Id, 28, '1', 'PS832324H', '1', 1, oContact.Id);
        insert finalApp;
    }
    public static testMethod void populateScheduledSettlementDateOnCaseTestCaseone()

    {
        
        List <Contract> lstContract1 = [SELECT Id, Lot_Number__c, Volume__c, Plan_Number__c, Folio__c FROM Contract];
        List <Case> lstCase1 = [Select Id, Status, Scheduled_Settlement_Date__c from case];
        List <Id> CSId = new List <Id>();
        for (Case CSObj: lstCase1) 
        {
            CSId.add(CSObj.Id);
        }
        Test.startTest();
        PopulateScheduledSettlementDateOnCase.calculateSettlementDate(CSId);
        Test.stopTest();

    }
    
    public static testMethod void populateScheduledSettlementDateOnCaseTestCasetwo() {
        Date yesterday = System.Today().addDays(-1);
        Account testAccount2 = new Account(Name = 'Test Name');
        insert testAccount2;

        Contact cont2 = new Contact();
        cont2.FirstName = 'Test';
        cont2.LastName = 'testContact2';
        cont2.accountid = testAccount2.id;
        cont2.Email = 'Test@test.com';
        insert cont2;
        Case testCase2 = new Case(Status = 'Final Approval Requested', Scheduled_Settlement_Date__c = yesterday);
        insert testCase2;
        RegulatoryAuthorizationType testRegulatoryAuthorizationType2 = new RegulatoryAuthorizationType(Name = 'Test');
        insert testRegulatoryAuthorizationType2;
        IndividualApplication testIndividualApplication2 = new IndividualApplication(
            LicenseTypeId = testRegulatoryAuthorizationType2.Id,
            AppliedDate = System.now(),
            Aboriginal_Applicants__c = false,
            Panel_Finance_Officer__c = cont2.id,
            Category = 'Grant',
            ApplicantNames__c = 'Test One, Test Two');
        insert testIndividualApplication2;


        Contract testContract2 = new Contract(IndividualApplicationId__c = testIndividualApplication2.Id,
            Status = 'Final Application Submitted',
            Panel_Finance_Officer__c = cont2.id,
            Bypassvalidation__c = true,
            ApplicationCaseId__c = testCase2.Id,
            Settlement_Date__c = yesterday, AccountId = testAccount2.Id, Plan_Number__c = 'LP074245', Lot_Number__c = '13G', Folio__c = '1', Volume__c = integer.ValueOf(23623));
        insert testContract2;
        List < Contract > lstContract2 = new List < Contract > ([SELECT Id, Lot_Number__c, Volume__c, Plan_Number__c, Folio__c FROM Contract WHERE Id =: testContract2.Id and Status NOT IN('Cancelled', 'Rejected', 'Cancelled Settlement')]);

        List < Case > lstCase2 = new List <
            case >([Select Id, Status, Scheduled_Settlement_Date__c from
                case WHERE Id =: testCase2.Id
            ]);
        List < Id > CSId2 = new List < Id > ();
        for (Case CSObj2: lstCase2) {
            CSId2.add(CSObj2.Id);
        }

        Test.startTest();
        PopulateScheduledSettlementDateOnCase.calculateSettlementDate(CSId2);
        Test.stopTest();

    }
}