force-app/main/default/objects/Account/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applicant Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The property linked to approved participants in the VHF scheme</description>
    <label>Property</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <description>Financial Planner or Lender</description>
    <label>Business</label>
</RecordType>

force-app/main/default/objects/Annual_Review__c/Annual_Review__c.object-meta.xml
<CustomObject>
    <description>Stores the responses to questions that participants to the VHF scheme need to complete on an annual basis</description>
    <label>Annual Review</label>
    <nameField>
        <displayFormat>AR-{0000000000}</displayFormat>
        <label>Annual Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Reviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Review__c/fields/Annual_Review_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Annual_Review_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Annual Review End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Annual_Review_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Annual_Review_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Annual Review Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Campaign</description>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Annual Reviews</relationshipLabel>
    <relationshipName>Annual_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>Date when annual review is due. Ten business days(14 Calendar days) adjusted for when final day falls on a public holiday or weekend.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Participant_Four__c.field-meta.xml
<CustomField>
    <fullName>Participant_Four__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Account Id of additional participant populated during monthly batch job and used by validation rule to limit access</description>
    <label>Participant Four</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annual Reviews (Participant Four)</relationshipLabel>
    <relationshipName>Annual_Reviews_P4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Participant_Name_1__c.field-meta.xml
<CustomField>
    <fullName>Participant_Name_1__c</fullName>
    <description>Name entered by primary participant while filling out the annual review to associate with the gross annual income</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Participant Name 1</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Participant_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Participant_Name_2__c</fullName>
    <description>Name entered by primary participant while filling out the annual review to associate with the gross annual income.  Note: May not match lookup field Participant 2 as that was populated by batch job prior to annual review being filled out</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Participant Name 2</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Participant_Name_3__c.field-meta.xml
<CustomField>
    <fullName>Participant_Name_3__c</fullName>
    <description>Name entered by primary participant while filling out the annual review to associate with the gross annual income.  Note: May not match lookup field Participant 3 as that was populated by batch job prior to annual review being filled out</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Participant Name 3</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Participant_Name_4__c.field-meta.xml
<CustomField>
    <fullName>Participant_Name_4__c</fullName>
    <description>Name entered by primary participant while filling out the annual review to associate with the gross annual income.  Note: May not match lookup field Participant 4 as that was populated by batch job prior to annual review being filled out</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Participant Name 4</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Participant_Three__c.field-meta.xml
<CustomField>
    <fullName>Participant_Three__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Account Id of additional participant populated during monthly batch job and used by validation rule to limit access</description>
    <label>Participant Three</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annual Reviews (Participant Three)</relationshipLabel>
    <relationshipName>Annual_Reviews_P3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Participant_Two__c.field-meta.xml
<CustomField>
    <fullName>Participant_Two__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Account Id of additional participant populated during monthly batch job and used by validation rule to limit access</description>
    <label>Participant Two</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annual Reviews (Participant Two)</relationshipLabel>
    <relationshipName>Annual_Reviews_P2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Primary_Participant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Primary participant linked to the annual review</description>
    <label>Primary Participant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annual Reviews</relationshipLabel>
    <relationshipName>Annual_Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Annual Reviews</relationshipLabel>
    <relationshipName>Annual_Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Submission</fullName>
                <default>true</default>
                <label>Awaiting Submission</label>
            </value>
            <value>
                <fullName>Awaiting Verification</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Actual_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AnnualReviewGeneratorService.cls
/*******************************************************************************************
* @Name         AnnualReviewGeneratorService
* @Author       Sebastian Anton <santon@salesforce.com>
* @Date         21/10/2021
* @Description  Service class to allow generation of Annual Review records from different contexts.
*******************************************************************************************/
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*  1.0              Sebastian      21/10/2021          Initial Creation
*  1.1              Lawrence        1/11/2021          Calls BusinessDaysCalculation class
*  1.2				Lawrence		8/11/2021          Saves campaign id if available
*******************************************************************************************/
public class AnnualReviewGeneratorService {
    // Invocable method to be called from 'Create Replacement Annual Review' flow 
    @InvocableMethod(label='Create Replacement Annual Review' description='Creates replacement Annual Review Record for specified Annual Review and returns ID of new Annual Review. Only one Annual Review Can be generated at a time.'category='Annual Review')
    public static list<ID> AnnualReviewGeneratorService(list<Id> requestedAnnualReviews) {
        System.debug('*** INVOCABLE METHOD CALL: Create Annual Reviews ***');
        System.debug('Requested Properties: '+requestedAnnualReviews);
        list<Annual_Review__c> annualReviews = [SELECT Property__c, Annual_Review_Start_Date__c FROM Annual_Review__c WHERE Id IN :requestedAnnualReviews];
        list<Id> requestedProperties = new list<Id>();
        for(Annual_Review__c annualReview: annualReviews){
            requestedProperties.add(annualReview.Property__c);
        }
        list<Order> fullPropertyInfo = [SELECT Id, Actual_Settlement_Date__c, 
                                    (SELECT Id, Name, PersonContactId, Is_Participant__pc, Primary_Participant__pc, IsActiveApplicant__pc 
                                    FROM Accounts__r)
                                    FROM Order
                                    WHERE Id IN :requestedProperties];
        list<Id> newAnnualReviews = generateAnnualReviews(fullPropertyInfo, null, annualReviews[0].Annual_Review_Start_Date__c.year());
        return newAnnualReviews;
    }

    public static list<Id> generateAnnualReviews(list<Order> activeProperties, id campaignId, Integer specifiedYear){
        // Create Annual Review Records
        System.debug('*** METHOD CALL: AnnualReviewGeneratorService.generateAnnualReviews ***');
        System.debug('Active Properties: ' + activeProperties);
        System.debug('Test actual settlement date: '+activeProperties[0].Actual_Settlement_Date__c);
        Id queueId = [SELECT Id FROM Group WHERE Name = 'VHF Annual Review Queue' AND Type = 'Queue' LIMIT 1].Id;
        //Call BusinessDaysCalculation.getWorkingDayDateAfterNDays with 10 business working days
        Datetime now = Datetime.now();
        String currentDateTime = now.format('yyyy-MM-dd\'T\'HH:mm:ss.SSSZ');
        string sMethodName = 'getWorkingDayDateAfterNDays';
        Map<String, Object> inputMap = new Map<String, Object>{'NthWorkingDay'=>10,'startDate'=>currentDateTime};
        Map<String, Object> outputMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        new BusinessDaysCalculation().invokeMethod(sMethodName, inputMap, outputMap, options);
        Date dueDate = (Date)outputMap.get('NthWorkingDay_Date');
        List<Annual_Review__c> annualReviewRecordsToInsert= new List<Annual_Review__c>();
        list<Id> primaryApplicantContactIds = new list<Id>();

        for(Order activeProperty: activeProperties){

            // Calculate Annual Review Period
            date startDate = date.newInstance(specifiedYear-1, activeProperty.Actual_Settlement_Date__c.month(), activeProperty.Actual_Settlement_Date__c.day());
            date endDate = startDate.addYears(1).addDays(-1);
            System.debug('Start Date: ' + startDate + ' End Date: ' + endDate);

            Account primaryApplicant;
            Id primaryApplicantContactId;
            List<Account> nonPrimaryApplicants = new List<Account>();
            System.debug('related accounts: ' + activeProperty.Accounts__r);
            for(Account applicant: activeProperty.Accounts__r){
                System.debug('*** Active Property: ' + activeProperty.Id);
                System.debug('*** Debug: ' + applicant.Name + ' ID: ' + applicant.Id);
                if(applicant.Primary_Participant__pc == true){
                    primaryApplicant = applicant;
                    primaryApplicantContactId = applicant.PersonContactId;
                }else if(applicant.IsActiveApplicant__pc == 'Yes' && applicant.Primary_Participant__pc == false){
                    nonPrimaryApplicants.add(applicant);
                }
            } // End - for(Account)
            System.debug('Non Primary Applicants: ' + nonPrimaryApplicants);

            primaryApplicantContactIds.add(primaryApplicantContactId);

            if(nonPrimaryApplicants.size() == 0){
                annualReviewRecordsToInsert.add(new Annual_Review__c(
                                                OwnerId = queueId,
                                                Status__c = 'Awaiting Submission',
                                                Primary_Participant__c = primaryApplicant.Id,
                                                Property__c = activeProperty.Id,
                                                Due_Date__c = dueDate,
                                                Participant_Name_1__c = primaryApplicant.Name,
                								campaign__c = campaignId,
                                                Annual_Review_Start_Date__c = startDate,
                                                Annual_Review_End_Date__c = endDate));
            }else if(nonPrimaryApplicants.size() == 1){
                annualReviewRecordsToInsert.add(new Annual_Review__c(
                                                OwnerId = queueId,
                                                Status__c = 'Awaiting Submission',
                                                Primary_Participant__c = primaryApplicant.Id,
                                                Participant_Two__c = nonPrimaryApplicants[0].Id,
                                                Property__c = activeProperty.Id,
                                                Due_Date__c = dueDate,
                                                Participant_Name_1__c = primaryApplicant.Name,
                                                Participant_Name_2__c = nonPrimaryApplicants[0].Name,
                								campaign__c = campaignId,
                                                Annual_Review_Start_Date__c = startDate,
                                                Annual_Review_End_Date__c = endDate));
            }else if(nonPrimaryApplicants.size() == 2){
                annualReviewRecordsToInsert.add(new Annual_Review__c(
                                                OwnerId = queueId,
                                                Status__c = 'Awaiting Submission',
                                                Primary_Participant__c = primaryApplicant.Id,
                                                Participant_Two__c = nonPrimaryApplicants[0].Id,
                                                Participant_Three__c = nonPrimaryApplicants[1].Id,
                                                Property__c = activeProperty.Id,
                                                Due_Date__c = dueDate,
                                                Participant_Name_1__c = primaryApplicant.Name,
                                                Participant_Name_2__c = nonPrimaryApplicants[0].Name,
                                                Participant_Name_3__c = nonPrimaryApplicants[1].Name,
                								campaign__c = campaignId,
                                                Annual_Review_Start_Date__c = startDate,
                                                Annual_Review_End_Date__c = endDate));
            }else if(nonPrimaryApplicants.size() == 3){
                annualReviewRecordsToInsert.add(new Annual_Review__c(
                                                OwnerId = queueId,
                                                Status__c = 'Awaiting Submission',
                                                Primary_Participant__c = primaryApplicant.Id,
                                                Participant_Two__c = nonPrimaryApplicants[0].Id,
                                                Participant_Three__c = nonPrimaryApplicants[1].Id,
                                                Participant_Four__c = nonPrimaryApplicants[2].Id,
                                                Property__c = activeProperty.Id,
                                                Due_Date__c = dueDate,
                                                Participant_Name_1__c = primaryApplicant.Name,
                                                Participant_Name_2__c = nonPrimaryApplicants[0].Name,
                                                Participant_Name_3__c = nonPrimaryApplicants[1].Name,
                                                Participant_Name_4__c = nonPrimaryApplicants[2].Name,
                								campaign__c = campaignId,
                                                Annual_Review_Start_Date__c = startDate,
                                                Annual_Review_End_Date__c = endDate));
            }
        } // End - for(Order)

        if (campaignId != null){
            // Create Campaign Member Records
            list<CampaignMember> campaignMembersToInsert = new list<CampaignMember>();
            for(Id primaryAppContactId: primaryApplicantContactIds){
                campaignMembersToInsert.add(new CampaignMember(CampaignId = campaignId, ContactId = primaryAppContactId, Status = 'Pending'));
            } // End for(Id)
            // Insert Campaign Member Records
            list<Id> successfullyInsertedCampaignMemberRecords = new list<Id>();
            if(!campaignMembersToInsert.isEmpty()){
                list<Database.SaveResult> saveResults = Database.insert(campaignMembersToInsert, false);
                for(Database.SaveResult sr: saveResults){
                    if(sr.isSuccess()){
                        successfullyInsertedCampaignMemberRecords.add(sr.getId());
                    } else {
                        for(Database.Error err: sr.getErrors()){
                            System.debug('ERROR OCCURED: Failed Campaign Member Insertion: ID = '+sr.Id+' Status Code: '+err.getStatusCode()+ 'Message: '+err.getMessage());
                        }
                    }
                } // End - for(Database.saveResult)
            }
            if(!successfullyInsertedCampaignMemberRecords.isEmpty()){
                System.debug('*** Successfully Inserted Campaign Members: '+successfullyInsertedCampaignMemberRecords);
            }
        }
        
        // Insert Annual Review Records
        list<Id> successfullyInsertedAnnualReviewRecords = new list<Id>();
        list<Id> failureRecords = new list<Id>();
        Integer totalRecords = 0, errorRecords = 0, successfulRecords = 0;
        String processLog = '';
        if(!annualReviewRecordsToInsert.isEmpty()){
            list<Database.SaveResult> saveResults = Database.insert(annualReviewRecordsToInsert, false);
            for(Database.SaveResult sr: saveResults){
                if(sr.isSuccess()){
                    successfulRecords++;
                    successfullyInsertedAnnualReviewRecords.add(sr.getId());
                } else {
                    for(Database.Error err: sr.getErrors()){
                        errorRecords++;
                        String error = 'ERROR OCCURED: Failed Annual Review Insertion: ID = '+sr.Id+' Status Code: '+err.getStatusCode()+ 'Message: '+err.getMessage();
                        System.debug(error);
                        failureRecords.add(sr.Id);
                        processLog += error  + '<br>';
                    }
                }
            } // End - for(Database.saveResult)
        }
        if(!successfullyInsertedAnnualReviewRecords.isEmpty()){
            System.debug('*** Successfully Inserted Annual Reviews: '+successfullyInsertedAnnualReviewRecords);
        }
        if(!failureRecords.isEmpty()){
            processLog = 
            '#########################' + '<br>' +
            'Annual Review Insertion' + '<br>' +
            'End DateTime: ' + DateTime.now() + '<br>' +
            'Total Success Records: ' + successfulRecords + '<br>' +
            'Total Failed Records: ' + errorRecords + '<br>' +
            'List of Failed Records: ' + failureRecords + '<br>' +
            '#########################' + '<br>' +
            processLog;

            // Notify Admin of Failed Records
            list<Messaging.SingleEmailMessage> singleEmailMessages = new list<Messaging.SingleEmailMessage>();
            // Awaiting email address from vhf-2787. Implement using custom metadata type.
            list<String> toAddresses = new list<String>{'test@sro.vic.gov.au.invalid'};
            Messaging.SingleEmailMessage singleEmail = new Messaging.SingleEmailMessage();
            singleEmail.setSubject('Test Single Email');
            singleEmail.setToAddresses(toAddresses);
            singleEmail.setHtmlBody(processLog);
            singleEmail.setSubject('Annual Review Batch Failure');
            singleEmailMessages.add(singleEmail);
            Messaging.sendEmail(singleEmailMessages);
        }

        return successfullyInsertedAnnualReviewRecords;
    }
}