force-app/main/default/objects/Account/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The property linked to approved participants in the VHF scheme</description>
    <label>Property</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <description>Financial Planner or Lender</description>
    <label>Business</label>
</RecordType>

force-app/main/default/objects/Annual_Review__c/Annual_Review__c.object-meta.xml
<CustomObject>
    <description>Stores the responses to questions that participants to the VHF scheme need to complete on an annual basis</description>
    <label>Annual Review</label>
    <nameField>
        <displayFormat>AR-{0000000000}</displayFormat>
        <label>Annual Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Reviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Review__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Campaign</description>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Annual Reviews</relationshipLabel>
    <relationshipName>Annual_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Annual Reviews</relationshipLabel>
    <relationshipName>Annual_Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Actual_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Panel_Financier_Name__c.field-meta.xml
<CustomField>
    <fullName>Panel_Financier_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Panel Financier for which the property is currently being financed by</description>
    <label>Panel Financier Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/AnnualReviewRerunBatchTest.cls
/*******************************************************************************************
* @Name         AnnualReviewRerunBatchTest
* @Author       Sebastian Anton <santon@salesforce.com>
* @Date         12/11/2021
* @Description  Tests AnnualReviewRerunBatch.cls
*******************************************************************************************/
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*  1.0              Sebastian      21/10/2021          Initial Creation
*******************************************************************************************/
@isTest
public with sharing class AnnualReviewRerunBatchTest {
    // Keep scope less than or equal to batchSize for assertion to work
    private static integer scope = 20;
    private static integer batchSize = 20;
    public static testMethod void testRerunAnnualReviewBatch(){
        // Create Person Account Records
        Id personAccountRT_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        list<Account> individualAccounts = new list<account>();
        for(Integer i = 0; i < scope; i++){
                individualAccounts.add(new Account(FirstName = 'Test' + i,
                                            LastName = 'Person Account',
                                            RecordTypeId = personAccountRT_ID,
                                            Is_Participant__pc = True,
                                            Primary_Participant__pc = True,
                                            IsActiveApplicant__pc = 'Yes',
                                            personEmail = 'testEmail@sro.vic.gov.au.invalid',
                                            PersonMailingStreet = '2 ABC Street',
                                            PersonMailingCity = 'Melbourne',
                                            PersonMailingState = 'Victoria',
                                            PersonMailingPostalCode = '3000'));
        }
        insert individualAccounts;
        // Create Business Account Record
        Id businessAccountRT_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        Account businessAccount = new Account(Name = 'Bank of Victoria', 
                                                RecordTypeID = businessAccountRT_ID);
        insert businessAccount;
        // Create Property Records
        integer currentMonth = Date.today().month();
        Integer lastYear = Date.today().year() - 1;
        list<Order> properties = new list<Order>();
        for(Integer i = 0; i < scope; i++){
            properties.add(new Order(AccountId = individualAccounts[i].Id,
                                        EffectiveDate = Date.newInstance(lastYear, currentMonth, 4),
                                        status = 'Draft',
                                        Panel_Financier_Name__c = businessAccount.Id,
                                        Actual_Settlement_Date__c = Date.newInstance(lastYear, currentMonth, 4)));
        }
        insert properties;
        for(integer i = 0; i < scope; i++){
            individualAccounts[i].Property__c = properties[i].Id;
        }
        update individualAccounts;

        // Attach One Secondary Applicant
        list<Account> oneSecondaryApplicants = AnnualReviewBatchTest.generatePersonAccounts(1, 'alpha');
        oneSecondaryApplicants[0].Property__c = properties[0].Id;
        update oneSecondaryApplicants;

        // Attach Two Secondary Applicant
        list<Account> twoSecondaryApplicants = AnnualReviewBatchTest.generatePersonAccounts(2, 'beta');
        twoSecondaryApplicants[0].Property__c = properties[1].Id;
        twoSecondaryApplicants[1].Property__c = properties[1].Id;
        update twoSecondaryApplicants;

        // Attach Three Secondary Applicant
        list<Account> threeSecondaryApplicants = AnnualReviewBatchTest.generatePersonAccounts(3, 'tango');
        threeSecondaryApplicants[0].Property__c = properties[2].Id;
        threeSecondaryApplicants[1].Property__c = properties[2].Id;
        threeSecondaryApplicants[2].Property__c = properties[2].Id;
        update threeSecondaryApplicants;

        // Run Batch
        Test.startTest();
        //AnnualReviewBatch annualReview = new AnnualReviewBatch();
        //Id batchProcessId = Database.executeBatch(annualReview, batchSize);
        list<Integer> month = new list<Integer>{Date.today().month(), Date.today().year()};
        list<list<Integer>> runVariable = new list<list<Integer>>();
        runVariable.add(month);
        AnnualReviewRerunBatch.AnnualReviewRerunBatch(runVariable);
        Test.stopTest();
        // Check Result
        Integer countAnnualReviews = [SELECT COUNT() FROM Annual_Review__c];
        System.assertEquals(scope, countAnnualReviews);
        
        //Check Campaign ID of Annual Reviews and Campaign Members are populated
        List<Annual_Review__c> AR = [SELECT Id, campaign__c FROM Annual_Review__c];
        for (Annual_Review__c myAR: AR){
            System.assertNotEquals(null, myAR.Campaign__c);
        }
        
        List<CampaignMember> members = [SELECT Id, CampaignId FROM CampaignMember];
        for (CampaignMember myCM: members){
            System.assertNotEquals(null, myCM.CampaignId);
        }
    }
}