force-app/main/default/objects/Account/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The property linked to approved participants in the VHF scheme</description>
    <label>Property</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/Annual_Review__c.object-meta.xml
<CustomObject>
    <description>Stores the responses to questions that participants to the VHF scheme need to complete on an annual basis</description>
    <label>Annual Review</label>
    <nameField>
        <displayFormat>AR-{0000000000}</displayFormat>
        <label>Annual Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Reviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Review__c/fields/Absence_end_date__c.field-meta.xml
<CustomField>
    <fullName>Absence_end_date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Absence #1 End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Absence_start_date__c.field-meta.xml
<CustomField>
    <fullName>Absence_start_date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Absence #1 Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in process builder and flow to allow updates to records otherwise locked by validations rules.</description>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <description>A field that must be set before an Annual Review can be cancelled</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Cancellation Reason</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Annual Reviews</relationshipLabel>
    <relationshipName>Annual_Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Absence_Duration_Months__c.field-meta.xml
<CustomField>
    <fullName>Absence_Duration_Months__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Absence Duration(Months)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Absence_end_date__c.field-meta.xml
<CustomField>
    <fullName>Absence_end_date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Absence end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Absence_start_date__c.field-meta.xml
<CustomField>
    <fullName>Absence_start_date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Absence start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Actual_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Annual_Review__c.field-meta.xml
<CustomField>
    <fullName>Annual_Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Annual Review ID</label>
    <referenceTo>Annual_Review__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>VHF-1712</description>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <description>Cancellation_Reason</description>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Final payment required</fullName>
            </value>
            <value>
                <fullName>Payment not eligible</fullName>
            </value>
            <value>
                <fullName>Participant Request</fullName>
            </value>
            <value>
                <fullName>Panel Financier Request</fullName>
            </value>
            <value>
                <fullName>Not eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Cancellation_Reason_Comments__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason_Comments__c</fullName>
    <description>Cancellation Reason Comments</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Cancellation Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Property</description>
    <label>Property ID</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <description>sub status specific to victorian homebuyer fund</description>
    <label>Sub Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Notification Sent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Valid_Absence_Duration_Months__c.field-meta.xml
<CustomField>
    <fullName>Valid_Absence_Duration_Months__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Valid Absence Duration (Months)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Final_Payment.recordType-meta.xml
<RecordType>
    <fullName>Final_Payment</fullName>
    <active>true</active>
    <businessProcess>Final Payment</businessProcess>
    <label>Final Payment</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Income_Threshold_Exceeded.recordType-meta.xml
<RecordType>
    <fullName>Income_Threshold_Exceeded</fullName>
    <active>true</active>
    <businessProcess>Income Threshold Exceeded</businessProcess>
    <label>Income Threshold Exceeded</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Long_Term_Absence.recordType-meta.xml
<RecordType>
    <fullName>Long_Term_Absence</fullName>
    <active>true</active>
    <businessProcess>Long Term Absence</businessProcess>
    <label>Long Term Absence</label>
</RecordType>

force-app/main/default/objects/Order/fields/Actual_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Stores the payment details that a participant need to make as part of post settlement process</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PID-{00000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <description>Updated by SRO officer</description>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Incorrect Calculation</fullName>
            </value>
            <value>
                <fullName>Payment not Required</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Auto-linked when payment record is created</description>
    <label>Property</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHelperTest.cls
/*
* Description: Test class for caseTrigger  
** Version History ** 
Created: Sourabh Singh, 10/12/2021
*******************************************************************************************/
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*  1.1              Arjun             20/01/2022          Added test method for duration and validation duration calculation
*  1.2              Arjun Singh       03/02/2022          VHF-3082    
*  1.3              Manish             21/03/2022          VHF-4306
*/ 

@isTest
private class CaseTriggerHelperTest 
{   
    
    
    @TestSetup
    static void setup() 
    {    
        final Id LTA_RECORDTYPEID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Long_Term_Absence').getRecordTypeId();
        
        UserRole newCustomRole = VHFTestDataFactory.createCustomRole('CustomRole', 'CustomRole');
        insert newCustomRole;
        
        User newAdminUser = VHFTestDataFactory.createAdminUser(newCustomRole.Id, 'testSysAdminUser@test.com', 'testSysAdminUser@test.com', 'testuser', 'admin', 'testad');
        insert newAdminUser;
        
        User adminUser = [Select Id from User where Email = 'testSysAdminUser@test.com'];
        
        System.runAs(adminUser)
        {
            Account accPerson = VHFTestDataFactory.createApplicantPersonAccountWithDetails('Yes', 'test', 'last', 'emailc@test.com');
            insert accPerson;
            
            
            Account acc = VHFTestDataFactory.createLenderAccount('Bank');
            insert acc;
            
            Order property = VHFTestDataFactory.createProperty(accPerson.Id, 'Draft', acc.Id);
            property.Actual_Settlement_Date__c = date.Today() - 10;
            insert property; 

            Annual_Review__c annualReview = VHFTestDataFactory.createAnnualReview(property.Id, accPerson.Id, date.today()-10, date.today()+354);
            insert annualReview;
            
           
            Case newLTACase = new Case();
            newLTACase.AccountId = accPerson.Id;
            newLTACase.ContactId = accPerson.PersonContactId;
            newLTACase.Status = 'New';
            newLTACase.Sub_Status__c = 'Pending';
            newLTACase.Subject = 'Test LTA case';
            newLTACase.recordTypeId = LTA_RECORDTYPEID;
            newLTACase.Property__c = property.id; 
            newLTACase.Annual_Review__c = annualReview.Id;
            insert newLTACase;

            
        
        }
    }
    
    public static testMethod void testResetBypass()        
    {
        Case c = [select id, status, BypassValidation__c from case limit 1 ];
        Test.startTest();
        c.status = 'In Review';
        c.BypassValidation__c = true;
        update c;
        Case cs = [select id, status, BypassValidation__c from case limit 1 ];
        System.assertEquals(cs.BypassValidation__c,false);
        Test.stopTest();         
    }
    public static testMethod void testTotalDuration()        
    {
        Case c = [select id, Absence_start_date__c, Absence_end_date__c from case limit 1 ];        
        c.Absence_start_date__c = date.today();
        c.Absence_end_date__c = date.today() + 92;

        Test.startTest();
        update c;
        Case cs = [select id, Absence_Duration_Months__c from case limit 1 ];        
        Test.stopTest();  
        System.assertEquals(cs.Absence_Duration_Months__c,3.0);
    }
    public static testMethod void testValidTotalDurationBeforeRange()        
    {
        Case c = [select id, Absence_start_date__c, Absence_end_date__c from case limit 1 ];        
        c.Absence_start_date__c = date.today() - 150;
        c.Absence_end_date__c = date.today() -90 ;

        Test.startTest();
        update c;
        Case cs = [select id, Valid_Absence_Duration_Months__c from case limit 1 ];        
        Test.stopTest(); 
        System.assertEquals(cs.Valid_Absence_Duration_Months__c,0);
    }
    public static testMethod void testValidTotalDurationInbetweenRange()        
    {
        Case c = [select id, Absence_start_date__c, Absence_end_date__c from case limit 1 ];        
        c.Absence_start_date__c = date.today() ;
        c.Absence_end_date__c = date.today() + 92 ;

        Test.startTest();
        update c;
        Case cs = [select id, Valid_Absence_Duration_Months__c from case limit 1 ];        
        Test.stopTest();  
        System.assertEquals(cs.Valid_Absence_Duration_Months__c,3.0);
    }
    public static testMethod void testValidTotalDurationInbetweenAndOutOfRange()        
    {
        Case c = [select id, Absence_start_date__c, Absence_end_date__c from case limit 1 ];        
        c.Absence_start_date__c = date.today() + 350;
        c.Absence_end_date__c = date.today() + 450 ;

        Test.startTest();
        update c;
        Case cs = [select id, Valid_Absence_Duration_Months__c from case limit 1 ];        
        Test.stopTest();  
        System.assertEquals(cs.Valid_Absence_Duration_Months__c,0.1);
    }
    public static testMethod void testValidTotalDurationOutOfRange()        
    {
        Case c = [select id, Absence_start_date__c, Absence_end_date__c from case limit 1 ];        
        c.Absence_start_date__c = date.today() + 390;
        c.Absence_end_date__c = date.today() + 450 ;

        Test.startTest();
        update c;
        Case cs = [select id, Valid_Absence_Duration_Months__c from case limit 1 ];        
        Test.stopTest(); 
        System.assertEquals(cs.Valid_Absence_Duration_Months__c,0.0);
    }
    public static testMethod void testParticipantPortalCreatedCases()        
    {
        Case c = [select id, Absence_start_date__c, Absence_end_date__c from case limit 1 ];        
        c.Absence_start_date__c = date.today() + 20;
        c.Absence_end_date__c = date.today() + 50 ;
        c.Origin = 'Participant Portal';
        c.Status = 'In Review';
        Test.startTest();
        update c;
        Case cs = [select id, Valid_Absence_Duration_Months__c, Absence_Duration_Months__c from case limit 1 ];        
        Test.stopTest(); 
        System.assertEquals(cs.Valid_Absence_Duration_Months__c,0.0);
    }
    public static testMethod void testFullPaymentCaseValidation()        
    {   Account participantRecord = [Select Id,PersonContactId from Account where PersonEmail ='emailc@test.com'];
        Id fullPaymentRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Final_Payment').getRecordTypeId();
        Order property = [Select Id From Order limit 1];
        
        participantRecord.Property__c = property.Id;
        participantRecord.Is_Participant__pc = true;
        participantRecord.Is_Participant__pc = true;
        update participantRecord;
       
       Case FullPaymentCase = new Case();
        FullPaymentCase.AccountId = participantRecord.Id;
        FullPaymentCase.ContactId = participantRecord.PersonContactId;
        FullPaymentCase.Status = 'New';
        FullPaymentCase.Sub_Status__c = 'Pending';
        FullPaymentCase.Subject = 'Test Full Payment case';
        FullPaymentCase.recordTypeId = fullPaymentRecordTypeId;
        FullPaymentCase.Property__c = property.id; 
        insert FullPaymentCase;

        Payment__c payment = VHFTestDataFactory.createPayment('Created', FullPaymentCase.Id, participantRecord.Id);
        insert payment;

        Test.startTest();
        try{            
            FullPaymentCase.status = 'Rejected';
            update FullPaymentCase;
        }catch(Exception e){
            String errMsg = e.getMessage();
            System.assert(errMsg.contains(CaseTriggerHelper.Err_Msg));
        }
        Test.stopTest();
    }
    
    public static testMethod void testFullPaymentCaseValidationCancellation()        
    {   Account participantRecord = [Select Id,PersonContactId from Account where PersonEmail ='emailc@test.com'];
        Id fullPaymentRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Final_Payment').getRecordTypeId();
        Order property = [Select Id From Order limit 1];
        
        participantRecord.Property__c = property.Id;
        participantRecord.Is_Participant__pc = true;
        participantRecord.Is_Participant__pc = true;
        update participantRecord;
       
       Case FullPaymentCase = new Case();
        FullPaymentCase.AccountId = participantRecord.Id;
        FullPaymentCase.ContactId = participantRecord.PersonContactId;
        FullPaymentCase.Status = 'New';
        FullPaymentCase.Sub_Status__c = 'Pending';
        FullPaymentCase.Subject = 'Test Full Payment case';
        FullPaymentCase.recordTypeId = fullPaymentRecordTypeId;
        FullPaymentCase.Property__c = property.id; 
        insert FullPaymentCase;

        Payment__c payment = VHFTestDataFactory.createPayment('Created', FullPaymentCase.Id, participantRecord.Id);
        insert payment;

        Test.startTest();
        try{            
            FullPaymentCase.status = 'Cancelled';
            update FullPaymentCase;
        }catch(Exception e){
            String errMsg = e.getMessage();
            System.assert(errMsg.contains(CaseTriggerHelper.Err_Msg_Cancellation));
        }
        Test.stopTest();
    }
     public static testMethod void testITE_CaseValidationCancellation()        
    {   Account participantRecord = [Select Id,PersonContactId from Account where PersonEmail ='emailc@test.com'];
        Id ITERecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Income_Threshold_Exceeded').getRecordTypeId();
        Order property = [Select Id From Order limit 1];
        
        participantRecord.Property__c = property.Id;
        participantRecord.Is_Participant__pc = true;
        participantRecord.Is_Participant__pc = true;
        update participantRecord;
       
       Case ITECase = new Case();
        ITECase.AccountId = participantRecord.Id;
        ITECase.ContactId = participantRecord.PersonContactId;
        ITECase.Status = 'New';
        ITECase.Sub_Status__c = 'Pending';
        ITECase.Subject = 'Test ITE case';
        ITECase.recordTypeId = ITERecordTypeId;
        ITECase.Property__c = property.id; 
        ITECase.BypassValidation__c = true;
        ITECase.Cancellation_Reason_Comments__c = 'Test close comments';
        ITECase.Cancellation_Reason__c = 'Other';
        insert ITECase;

        Payment__c payment = VHFTestDataFactory.createPayment('Created', ITECase.Id, participantRecord.Id);
        insert payment;

        Test.startTest();
        try{            
            ITECase.Status = 'Cancelled';
            update ITECase;
        }catch(Exception e){
            String errMsg = e.getMessage();
            System.debug('Error Message: ' + errMsg);
            System.assert(errMsg.contains(CaseTriggerHelper.Err_Msg_Cancellation));
        }
        Test.stopTest();
    }
}