force-app/main/default/objects/Account/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The property linked to approved participants in the VHF scheme</description>
    <label>Property</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Actual_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Property</description>
    <label>Property ID</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Proportionate_interest_amount__c.field-meta.xml
<CustomField>
    <fullName>Proportionate_interest_amount__c</fullName>
    <label>Proportional Interest Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <description>sub status specific to victorian homebuyer fund</description>
    <label>Sub Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Notification Sent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Property_Sale.recordType-meta.xml
<RecordType>
    <fullName>Property_Sale</fullName>
    <active>true</active>
    <businessProcess>Property Sale</businessProcess>
    <label>Property Sale</label>
</RecordType>

force-app/main/default/objects/Order/fields/Actual_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PropertySalePayoutDocumentPreChecksTest.cls
/*******************************************************************************************
* @Author       Arjun Singh
* @Date         08/03/2022
* @Description  Test Class for PropertySalePayoutDocumentPreChecks
*******************************************************************************************/ 
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*  1.0              Arjun Singh       08/03/2022          Created  
*******************************************************************************************/
@isTest
private class PropertySalePayoutDocumentPreChecksTest {
    @TestSetup
    static void setup() 
    { 
        final Id ProperySale_RECORDTYPEID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Property_Sale').getRecordTypeId();
        
        UserRole newCustomRole = VHFTestDataFactory.createCustomRole('CustomRole', 'CustomRole');
        insert newCustomRole;
        
        User newAdminUser = VHFTestDataFactory.createAdminUser(newCustomRole.Id, 'testSysAdminUser@test.com', 'testSysAdminUser@test.com', 'testuser', 'admin', 'testad');
        insert newAdminUser;
        
        User adminUser = [Select Id from User where Email = 'testSysAdminUser@test.com'];
        
        System.runAs(adminUser)
        {
            Account accPerson = VHFTestDataFactory.createApplicantPersonAccountWithDetails('Yes', 'test', 'last', 'emailc@test.com');
            insert accPerson;
            
            
            Account acc = VHFTestDataFactory.createLenderAccount('Bank');
            insert acc;
            
            Order property = VHFTestDataFactory.createProperty(accPerson.Id, 'Draft', acc.Id);
            property.Actual_Settlement_Date__c = date.Today() - 10;
            insert property;     
            
            accPerson.Property__c = property.Id;
            accPerson.Is_Participant__pc = true;
            accPerson.Is_Participant__pc = true;
            update accPerson;
           
            Case newPropertySaleCase = new Case();
            newPropertySaleCase.AccountId = accPerson.Id;
            newPropertySaleCase.ContactId = accPerson.PersonContactId;
            newPropertySaleCase.Status = 'New';
            newPropertySaleCase.Sub_Status__c = 'Pending';
            newPropertySaleCase.Subject = 'Test ProperySale case';
            newPropertySaleCase.recordTypeId = ProperySale_RECORDTYPEID;
            newPropertySaleCase.Property__c = property.id; 
            insert newPropertySaleCase;            
        
        }
    }
    public static testMethod void testvalidateRequest()        
    {
        Case caseRecord = [Select Id from Case limit 1];
        String validationMsg;
        Test.startTest();
        validationMsg = PropertySalePayoutDocumentPreChecks.validateRequest(String.valueOf(caseRecord.Id));
        Test.stopTest();
        System.assertEquals(validationMsg, PropertySalePayoutDocumentPreChecks.CALCULATE_PIA_MSG);
    }
    public static testMethod void testvalidateRequest_AwaitingSettlement()        
    {
        Case caseRecord = [Select Id, status from Case limit 1];
        caseRecord.status= 'Awaiting Settlement';
        caseRecord.Proportionate_interest_amount__c = 10;
        update caseRecord;
        String validationMsg;
        Test.startTest();
        validationMsg = PropertySalePayoutDocumentPreChecks.validateRequest(String.valueOf(caseRecord.Id));
        Test.stopTest();
        System.assertEquals(validationMsg, PropertySalePayoutDocumentPreChecks.AWAITIING_SETTLEMENT_MSG);
    }
    public static testMethod void testupdatePropertySaleCase()        
    {
        Case caseRecord = [Select Id, status from Case limit 1];
        Group propertySaleVGSOQueue = new Group();
        propertySaleVGSOQueue.Name = 'Property Sale VGSO queue';
        insert propertySaleVGSOQueue;
        Test.startTest();
            PropertySalePayoutDocumentPreChecks.updatePropertySaleCase(String.valueOf(caseRecord.Id));
        Test.stopTest();
        Case caseRecordAfterUpdate = [Select Id, status from Case limit 1];
        System.assertEquals(caseRecordAfterUpdate.status, PropertySalePayoutDocumentPreChecks.AWAITING_SETTLEMENT_STATUS);
    }
}