force-app/main/default/objects/Account/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The property linked to approved participants in the VHF scheme</description>
    <label>Property</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <description>Financial Planner or Lender</description>
    <label>Business</label>
</RecordType>

force-app/main/default/objects/Annual_Review__c/Annual_Review__c.object-meta.xml
<CustomObject>
    <description>Stores the responses to questions that participants to the VHF scheme need to complete on an annual basis</description>
    <label>Annual Review</label>
    <nameField>
        <displayFormat>AR-{0000000000}</displayFormat>
        <label>Annual Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Reviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Review__c/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in process builder and flow to allow updates to records otherwise locked by validations rules.</description>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Primary_Participant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Primary participant linked to the annual review</description>
    <label>Primary Participant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annual Reviews</relationshipLabel>
    <relationshipName>Annual_Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Annual Reviews</relationshipLabel>
    <relationshipName>Annual_Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Submission</fullName>
                <default>true</default>
                <label>Awaiting Submission</label>
            </value>
            <value>
                <fullName>Awaiting Verification</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Actual_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Annual_Review__c.field-meta.xml
<CustomField>
    <fullName>Annual_Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Annual Review ID</label>
    <referenceTo>Annual_Review__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>VHF-1712</description>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Individual_Application__c.field-meta.xml
<CustomField>
    <fullName>Individual_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual Application</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Individual_Application_Shadow__c.field-meta.xml
<CustomField>
    <fullName>Individual_Application_Shadow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Introduced with VHF-97 to access expiry date from the case object</description>
    <label>Individual_Application_Shadow</label>
    <referenceTo>Individual_Application_Shadow__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Property</description>
    <label>Property ID</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <description>sub status specific to victorian homebuyer fund</description>
    <label>Sub Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Notification Sent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Final_Payment.recordType-meta.xml
<RecordType>
    <fullName>Final_Payment</fullName>
    <active>true</active>
    <businessProcess>Final Payment</businessProcess>
    <label>Final Payment</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/Panel_Financier_Name__c.field-meta.xml
<CustomField>
    <fullName>Panel_Financier_Name__c</fullName>
    <formula>CreatedBy.Contact.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Panel Financier Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual_Application_Shadow__c/Individual_Application_Shadow__c.object-meta.xml
<CustomObject>
    <label>Individual_Application_Shadow</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Individual_Application_Shadow Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shadow Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individual_Application_Shadow__c/fields/Individual_Application__c.field-meta.xml
<CustomField>
    <fullName>Individual_Application__c</fullName>
    <label>Individual Application</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Shadow Applications</relationshipLabel>
    <relationshipName>Shadow_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individual_Application_Shadow__c/fields/Panel_Financier_Name__c.field-meta.xml
<CustomField>
    <fullName>Panel_Financier_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Panel Financier Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Individual_Application_Shadow__c.field-meta.xml
<CustomField>
    <fullName>Individual_Application_Shadow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual_Application_Shadow</label>
    <referenceTo>Individual_Application_Shadow__c</referenceTo>
    <relationshipLabel>Provisional Applications</relationshipLabel>
    <relationshipName>Provisional_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Actual_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Panel_Financier_Name__c.field-meta.xml
<CustomField>
    <fullName>Panel_Financier_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Panel Financier for which the property is currently being financed by</description>
    <label>Panel Financier Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Stores the payment details that a participant need to make as part of post settlement process</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PID-{00000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Panel_Financier_Name__c.field-meta.xml
<CustomField>
    <fullName>Panel_Financier_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel Financier Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments (Panel Financier Name)</relationshipLabel>
    <relationshipName>Payments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Primary_Participant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Auto-linked when payment record is created</description>
    <label>Primary Participant Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Auto-linked when payment record is created</description>
    <label>Property</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Updated by SRO Officer</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Payment Registered</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Request Expired</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
                <isActive>false</isActive>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Requested</fullName>
                <isActive>false</isActive>
                <label>Requested</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/ContentDocumentLink_TriggerHelperTest.cls
/*******************************************************************************************
* @Name         ContentDocumentLink_TriggerHelperTest 
* @Author       Sebastian Anton <santon@salesforce.com>
* @Date         31/08/2021
* @Description  Tests ContentDocumentLink_TriggerHelper.cls
*******************************************************************************************/
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*  1.0              Sebastian      31/08/2021          Initial Creation	 
*  1.1              Sebastian      19/01/2022          Added Participant File Upload Test
*  1.2              Arjun Singh    21/02/2022          VHF-3316 - Final Payment - Generate Payout Document
*******************************************************************************************/
@isTest(SeeAllData=FALSE)
public class ContentDocumentLink_TriggerHelperTest {
    public static testMethod void testContentDocumentLink(){
        // Regulatory Authorisation Type
        RegulatoryAuthorizationType testRegulatoryAuthorizationType = new RegulatoryAuthorizationType(Name = 'Test');
        insert testRegulatoryAuthorizationType;

        Case testCase = new Case();
        insert testCase;
        IndividualApplication testIndividualApplication = new IndividualApplication(
                                                                LicenseTypeId = testRegulatoryAuthorizationType.Id, 
                                                                AppliedDate = System.now(), 
                                                                ApplicationCaseId = testCase.Id,
                                                                Category = 'Grant');
        insert testIndividualApplication;
        Individual_Application_Shadow__c testIndividualApplicationShadow = new Individual_Application_Shadow__c(
                                                                                Individual_Application__c = testIndividualApplication.Id);
        insert testIndividualApplicationShadow;
        
        
        Blob bodyBlob = Blob.valueOf('Unit Test ContentVersion Body');
        ContentVersion content = new ContentVersion(Title = 'Test',
                                                        PathOnClient = '/Test.txt',
                                                        VersionData = bodyBlob);
        insert content;

        Id contentDocumentId = [SELECT contentDocumentId FROM ContentVersion WHERE Id = :content.Id].contentDocumentId;
        Test.startTest();
        ContentDocumentLink testContentDocumentLink = new ContentDocumentLink(
                                                            LinkedEntityId = testIndividualApplicationShadow.id,
                                                            ContentDocumentId = contentDocumentId,
                                                            ShareType = 'I',
                                                            Visibility = 'AllUsers');
        insert testContentDocumentLink;
        Test.stopTest();
        
        Integer countContentDocumentLink = [SELECT Count() FROM ContentDocumentLink WHERE ContentDocumentId = :contentDocumentId];
        System.assertEquals(4, countContentDocumentLink);
    }

    public static testMethod void testRestrictFileExtensionUpload(){
        Profile operationsProfile = [SELECT Id FROM Profile WHERE Name = 'Operations' LIMIT 1];
        String uniqueUserNameOperationsUser = 'operationsuser' + DateTime.now().getTime() + '@testorg.com';
        User operationsUser = new User(Alias='opsusr',
                                        Email='operationsuser@testorg.com',
                                        EmailEncodingKey='UTF-8',
                                        LastName='Testing',
                                        LanguageLocaleKey='en_US',
                                        LocaleSidKey='en_US', 
                                        ProfileId = operationsProfile.Id,
                                        TimeZoneSidKey='America/Los_Angeles',
                                        UserName=uniqueUserNameOperationsUser);
        insert operationsUser;

        Database.SaveResult invalidContentUpload;

        System.runAs(operationsUser){
            Blob bodyBlob = Blob.valueOf('Unit Test ContentVersion Body');
            ContentVersion contentVersion = new ContentVersion(Title = 'Test',
                                                            PathOnClient = '/test.bat',
                                                            VersionData = bodyBlob,
                                                            Origin = 'H');
            //insert contentVersion;
            invalidContentUpload = Database.insert(contentVersion, false);
        }
        System.assert(invalidContentUpload.isSuccess() == false, 'Invalid file extention blocked');
        System.assert(invalidContentUpload.getErrors().size() == 1);
    }

    private static final Decimal CONST_MEDICARE_NUM = Decimal.valueOf('21234567080');
    private static final Decimal CONST_CARD_NUM = Decimal.valueOf('212345670');
    private static final Decimal CONST_REF_NUM = Decimal.valueOf('1');
    private static final String PROFILE_VHFPARTICIPANTCOMMUNITYPLUSUSER = 'VHF Participant Community Plus User';
    private static final Id PERSONACCOUNT_RECORDTYPEID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
    @isTest
    static void testValidContentDocumentLink(){
        System.debug('*** Entered testValidContentDocumentLink');
        // Create Admin user
        UserRole customRole = new UserRole(DeveloperName = 'CustomRole', Name = 'Custom Role');
        insert customRole;
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name='System Administrator' LIMIT 1];
        User adminUser = new User(ProfileId = adminProfile.Id,
                                    firstName = 'Role',
                                    LastName = 'User',
                                    Email = 'testSysAdUser@test.com',
                                    Username = 'testSysAdUser@test.com' + System.currentTimeMillis(),
                                    CompanyName = 'TEST',
                                    Title = 'title',
                                    Alias = 'alias',
                                    TimeZoneSidKey = 'Australia/Sydney',
                                    EmailEncodingKey = 'ISO-8859-1',
                                    LanguageLocaleKey = 'en_US',
                                    LocaleSidKey = 'en_AU',
                                    UserRoleId = customRole.Id);
        insert adminUser;

        User contextUser;
        System.runAs(adminUser){
            // Create participant person account
            Account personAccount = new Account(MedicareNumber__pc = CONST_MEDICARE_NUM,
                                                    Medicare_Card_Number__pc = CONST_CARD_NUM,
                                                    Medicare_Reference_Number__pc = CONST_REF_NUM,
                                                    IsActiveApplicant__pc = 'Yes',
                                                    Is_Participant__pc = true,
                                                    Primary_Participant__pc = true,
                                                    RecordTypeId = PERSONACCOUNT_RECORDTYPEID,
                                                    PersonMailingPostalCode = '6004',
                                                    PersonEmail = 'participant.user1@email.com.invalid',
                                                    LastName = 'userone',
                                                    PersonMailingCity = 'Melbourne',
                                                    PersonMailingState = 'Victoria',
                                                    PersonMailingStreet = 'Collins Street');
            insert personAccount;
            // Create participant portal user
            Id personContactId = [Select PersonContactId from Account where Id =:personAccount.Id].PersonContactId;
            Profile communityProfile = [SELECT Id FROM profile WHERE Name = :PROFILE_VHFPARTICIPANTCOMMUNITYPLUSUSER Limit 1];
            contextUser = new User(ContactId = personContactId,
                                            Username = personAccount.PersonEmail,
                                            Email = personAccount.PersonEmail,
                                            LastName = personAccount.LastName,
                                            CommunityNickname = personAccount.LastName + '_' + System.currentTimeMillis(),
                                            Alias = string.valueOf(personAccount.LastName.substring(0,1) + Math.random() ).substring(0,5),
                                            TimeZoneSidKey = 'Australia/Sydney',
                                            LocaleSidKey = 'en_AU',
                                            EmailEncodingKey = 'ISO-8859-1',
                                            ProfileId = communityProfile.Id,
                                            LanguageLocaleKey = 'en_US',
                                            IsActive = true);
            insert contextUser;
        }

        Test.startTest();
        System.runAs(contextUser){
            // Retrieve Person Account
            Account personAccount = [SELECT id, name, PersonContactId FROM Account WHERE personEmail = 'participant.user1@email.com.invalid' LIMIT 1]; 
            // Create Panel Financier
            Account panelFinancier = new Account(Name = 'Bank of Australia', 
                                                    RecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId());
            insert panelFinancier; 
            // Create Property
            Order property = new Order(AccountId = personAccount.Id,
                                        EffectiveDate = Date.newInstance(Date.today().year() - 1, Date.today().month(), 4),
                                        status = 'Draft',
                                        Panel_Financier_Name__c = panelFinancier.Id,                                    
                                        Actual_Settlement_Date__c = Date.newInstance(Date.today().year() - 1, Date.today().month(), 4),
                                        ByPassValidation__c = True);
            insert property;
            // Create Annual Review
            Annual_Review__c annualReview = new Annual_Review__c(Primary_Participant__c = personAccount.Id,
                                                                    Property__c = property.Id,
                                                                    Status__c = 'Awaiting Submission');
            insert annualReview;
            // Create Content Version
            NetworkMember membership = [SELECT NetworkID, MemberID FROM NetworkMember WHERE memberID = :contextUser.id];
            Blob bodyBlob = Blob.valueOf('Unit Test ContentVersion Body');
            ContentVersion content = new ContentVersion(Title = 'Test',
                                                            PathOnClient = '/Test.txt',
                                                            VersionData = bodyBlob,
                                                            NetworkId = membership.NetworkId);
            insert content;
            // Create Content Document Link
            ContentDocument contentDocument = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument LIMIT 1];
            ContentDocumentLink contentDocumentLink1 = new ContentDocumentLink(LinkedEntityId = annualReview.Id,
                                                                                    ContentDocumentId = contentDocument.id,
                                                                                    ShareType = 'V',
                                                                                    Visibility = 'AllUsers');                                        
            insert contentDocumentLink1;
        }
        Test.stopTest();
    }

    @isTest
    static void testInvalidContentDocumentLink(){
        System.debug('*** Entered testValidContentDocumentLink');
        // Create Admin user
        UserRole customRole = new UserRole(DeveloperName = 'CustomRole', Name = 'Custom Role');
        insert customRole;
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name='System Administrator' LIMIT 1];
        User adminUser = new User(ProfileId = adminProfile.Id,
                                    firstName = 'Role',
                                    LastName = 'User',
                                    Email = 'testSysAdUser@test.com',
                                    Username = 'testSysAdUser@test.com' + System.currentTimeMillis(),
                                    CompanyName = 'TEST',
                                    Title = 'title',
                                    Alias = 'alias',
                                    TimeZoneSidKey = 'Australia/Sydney',
                                    EmailEncodingKey = 'ISO-8859-1',
                                    LanguageLocaleKey = 'en_US',
                                    LocaleSidKey = 'en_AU',
                                    UserRoleId = customRole.Id);
        insert adminUser;

        User contextUser;
        System.runAs(adminUser){
            // Create participant person account
            Account personAccount = new Account(MedicareNumber__pc = CONST_MEDICARE_NUM,
                                                    Medicare_Card_Number__pc = CONST_CARD_NUM,
                                                    Medicare_Reference_Number__pc = CONST_REF_NUM,
                                                    IsActiveApplicant__pc = 'Yes',
                                                    Is_Participant__pc = true,
                                                    Primary_Participant__pc = true,
                                                    RecordTypeId = PERSONACCOUNT_RECORDTYPEID,
                                                    PersonMailingPostalCode = '6004',
                                                    PersonEmail = 'participant.user1@email.com.invalid',
                                                    LastName = 'userone',
                                                    PersonMailingCity = 'Melbourne',
                                                    PersonMailingState = 'Victoria',
                                                    PersonMailingStreet = 'Collins Street');
            insert personAccount;
            // Create participant portal user
            Id personContactId = [Select PersonContactId from Account where Id =:personAccount.Id].PersonContactId;
            Profile communityProfile = [SELECT Id FROM profile WHERE Name = :PROFILE_VHFPARTICIPANTCOMMUNITYPLUSUSER Limit 1];
            contextUser = new User(ContactId = personContactId,
                                            Username = personAccount.PersonEmail,
                                            Email = personAccount.PersonEmail,
                                            LastName = personAccount.LastName,
                                            CommunityNickname = personAccount.LastName + '_' + System.currentTimeMillis(),
                                            Alias = string.valueOf(personAccount.LastName.substring(0,1) + Math.random() ).substring(0,5),
                                            TimeZoneSidKey = 'Australia/Sydney',
                                            LocaleSidKey = 'en_AU',
                                            EmailEncodingKey = 'ISO-8859-1',
                                            ProfileId = communityProfile.Id,
                                            LanguageLocaleKey = 'en_US',
                                            IsActive = true);
            insert contextUser;
        }

        Test.startTest();
        System.runAs(contextUser){
            // Retrieve Person Account
            Account personAccount = [SELECT id, name, PersonContactId FROM Account WHERE personEmail = 'participant.user1@email.com.invalid' LIMIT 1]; 
            // Create Panel Financier
            Account panelFinancier = new Account(Name = 'Bank of Australia', 
                                                    RecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId());
            insert panelFinancier; 
            // Create Property
            Order property = new Order(AccountId = personAccount.Id,
                                        EffectiveDate = Date.newInstance(Date.today().year() - 1, Date.today().month(), 4),
                                        status = 'Draft',
                                        Panel_Financier_Name__c = panelFinancier.Id,                                    
                                        Actual_Settlement_Date__c = Date.newInstance(Date.today().year() - 1, Date.today().month(), 4),
                                        ByPassValidation__c = True);
            insert property;
            // Create Annual Review
            Annual_Review__c annualReview = new Annual_Review__c(Primary_Participant__c = personAccount.Id,
                                                                    Property__c = property.Id,
                                                                    Status__c = 'In Review');
            insert annualReview;
            // Create Content Version
            NetworkMember membership = [SELECT NetworkID, MemberID FROM NetworkMember WHERE memberID = :contextUser.id];
            Blob bodyBlob = Blob.valueOf('Unit Test ContentVersion Body');
            ContentVersion content = new ContentVersion(Title = 'Test',
                                                            PathOnClient = '/Test.txt',
                                                            VersionData = bodyBlob,
                                                            NetworkId = membership.NetworkId);
            insert content;
            // Create Content Document Link
            ContentDocument contentDocument = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument LIMIT 1];
            try{
                ContentDocumentLink contentDocumentLink1 = new ContentDocumentLink(LinkedEntityId = annualReview.Id,
                                                                                    ContentDocumentId = contentDocument.id,
                                                                                    ShareType = 'V',
                                                                                    Visibility = 'AllUsers');                                        
                insert contentDocumentLink1;
            }catch(Exception e){
                System.debug('Exception caught: '+e);
            } 
        }
        Test.stopTest();
    }
    public static testMethod void testPayoutContentDocumentLink(){
        // Regulatory Authorisation Type
        RegulatoryAuthorizationType testRegulatoryAuthorizationType = new RegulatoryAuthorizationType(Name = 'Test');
        insert testRegulatoryAuthorizationType;

        Account accPerson = VHFTestDataFactory.createApplicantPersonAccountWithDetails('Yes', 'test', 'last', 'emailc@test.com');
        insert accPerson;
        Account acc = VHFTestDataFactory.createLenderAccount('Bank');
        insert acc;

        Account participantRecord = [Select Id,PersonContactId from Account where PersonEmail ='emailc@test.com'];
        Id fullPaymentRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Final_Payment').getRecordTypeId();
        
        Order property = VHFTestDataFactory.createProperty(accPerson.Id, 'Draft', acc.Id);
        property.Actual_Settlement_Date__c = date.Today() - 10;
        insert property; 
        
        participantRecord.Property__c = property.Id;
        participantRecord.Is_Participant__pc = true;
        participantRecord.Is_Participant__pc = true;
        update participantRecord;
       
       Case FullPaymentCase = new Case();
        FullPaymentCase.AccountId = participantRecord.Id;
        FullPaymentCase.ContactId = participantRecord.PersonContactId;
        FullPaymentCase.Status = 'New';
        FullPaymentCase.Sub_Status__c = 'Pending';
        FullPaymentCase.Subject = 'Test Full Payment case';
        FullPaymentCase.recordTypeId = fullPaymentRecordTypeId;
        FullPaymentCase.Property__c = property.id; 
        insert FullPaymentCase;

        Payment__c payment = VHFTestDataFactory.createPayment('Created', FullPaymentCase.Id, participantRecord.Id);
        insert payment;
        
        
        Blob bodyBlob = Blob.valueOf('Unit Test ContentVersion Body');
        ContentVersion content = new ContentVersion(Title = 'Test',
                                                        PathOnClient = '/Test.txt',
                                                        VersionData = bodyBlob);
        insert content;

        Id contentDocumentId = [SELECT contentDocumentId FROM ContentVersion WHERE Id = :content.Id].contentDocumentId;
        Test.startTest();
        ContentDocumentLink testContentDocumentLink = new ContentDocumentLink(
                                                            LinkedEntityId = payment.id,
                                                            ContentDocumentId = contentDocumentId,
                                                            ShareType = 'I',
                                                            Visibility = 'AllUsers');
        insert testContentDocumentLink;
        Test.stopTest();
        
        ContentDocumentLink CaseDocumentRecord = [SELECT Id FROM ContentDocumentLink WHERE ContentDocumentId = :contentDocumentId AND LinkedEntityId =: FullPaymentCase.Id];
        System.debug('CaseDocumentRecord>>>'+CaseDocumentRecord);
        System.assert(CaseDocumentRecord != null);
    }
}