force-app/main/default/objects/Account/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The property linked to approved participants in the VHF scheme</description>
    <label>Property</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/Annual_Review__c.object-meta.xml
<CustomObject>
    <description>Stores the responses to questions that participants to the VHF scheme need to complete on an annual basis</description>
    <label>Annual Review</label>
    <nameField>
        <displayFormat>AR-{0000000000}</displayFormat>
        <label>Annual Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Reviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Review__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <description>A field that must be set before an Annual Review can be cancelled</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Cancellation Reason</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Primary_Participant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Primary participant linked to the annual review</description>
    <label>Primary Participant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annual Reviews</relationshipLabel>
    <relationshipName>Annual_Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Annual Reviews</relationshipLabel>
    <relationshipName>Annual_Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Submission</fullName>
                <default>true</default>
                <label>Awaiting Submission</label>
            </value>
            <value>
                <fullName>Awaiting Verification</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Annual_Review__c.field-meta.xml
<CustomField>
    <fullName>Annual_Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Annual Review ID</label>
    <referenceTo>Annual_Review__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <description>Cancellation_Reason</description>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Final payment required</fullName>
            </value>
            <value>
                <fullName>Payment not eligible</fullName>
            </value>
            <value>
                <fullName>Participant Request</fullName>
            </value>
            <value>
                <fullName>Panel Financier Request</fullName>
            </value>
            <value>
                <fullName>Not eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Property</description>
    <label>Property ID</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Panel_Financier_Name__c.field-meta.xml
<CustomField>
    <fullName>Panel_Financier_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Panel Financier for which the property is currently being financed by</description>
    <label>Panel Financier Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CancellationValidationTriggerTest.cls
/*******************************************************************************************
* @Name         CancellationValidationTriggerTest 
* @Author       Lawrence Tang
* @Date         19/10/2021
* @Description  This class is the test class of the Cancellation Validation Trigger
*               on Annual Review object
*******************************************************************************************/


@isTest
private class CancellationValidationTriggerTest {

      @testSetup static void setup() {
        Id personAccountRecordType =  [SELECT Id FROM RecordType WHERE Name = 'Person Account' and SObjectType = 'Account'].Id;
        Account participant = new Account();
        participant.FirstName = 'John';
        participant.LastName = 'West';
        participant.RecordTypeId = personAccountRecordType;
        participant.PersonMailingStreet = '2 ABC Street';
        participant.PersonMailingCity = 'Melbourne';
        participant.PersonMailingState = 'Victoria';
        participant.PersonMailingPostalCode = '3000';
        participant.PersonEmail = 'test@test.com';
        participant.IsActiveApplicant__pc = 'Yes';
        participant.Is_Participant__pc = true;
        participant.Primary_Participant__pc = true;
        insert participant;
        Account lender = new Account();
        lender.Name = 'aBank';
        insert lender;
        Order property = new Order();
        property.Name = 'A property';
        property.Status = 'Draft';
        property.AccountId = participant.Id;
        property.EffectiveDate = System.today();
        property.Panel_Financier_Name__c = lender.Id;
        insert property;
        participant.Property__c = property.Id;
        update participant;
        Annual_Review__c ar = new Annual_Review__c();
        ar.Status__c = 'Awaiting Submission';
        ar.Primary_Participant__c =  participant.Id;
        ar.Property__c = property.Id;
        insert ar;
        Case activeCase = new Case();
        activeCase.Annual_Review__c = ar.Id;
        activeCase.Status = 'New';
        activeCase.Subject = 'Test';
        insert activeCase;          
    }
    
    @isTest static void testActiveCase(){
        Annual_Review__c annualReview = [select id from Annual_Review__c LIMIT 1];
        annualReview.Status__c = 'Cancelled';
        annualReview.Cancellation_Reason__c = 'No longer needed';
        try {
           update annualReview; 
        }
        catch (System.DmlException e){
            System.debug('Exception: ' + e.getMessage());
        }
       Annual_Review__c updatedAR = [select id, Status__c from Annual_Review__c LIMIT 1];
        System.assert(updatedAR.Status__c == 'Awaiting Submission','Assertion failed: Status should remain in Awaiting Submission');    
    }
    
    @isTest static void testCloseCase(){
        Case openCase = [select id from Case LIMIT 1];
        openCase.Status = 'Closed';
        try {
           update openCase; 
        }
        catch (System.DmlException e){
            System.debug('Exception: ' + e.getMessage());
        }
        Annual_Review__c annualReview = [select id from Annual_Review__c LIMIT 1];
        annualReview.Status__c = 'Cancelled';
        annualReview.Cancellation_Reason__c = 'No longer needed';
        try {
           update annualReview; 
        }
        catch (System.DmlException e){
            System.debug('Exception: ' + e.getMessage());
        }
       Annual_Review__c updatedAR = [select id, Status__c from Annual_Review__c LIMIT 1];
       System.assert(updatedAR.Status__c == 'Cancelled','Assertion failed: Status should be Cancelled');    
    }
}