force-app/main/default/objects/Account/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The property linked to approved participants in the VHF scheme</description>
    <label>Property</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to support a many to many relationship between a person account and an application.</description>
    <label>Applicant</label>
    <nameField>
        <displayFormat>Applicant - {0000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <description>Cancellation_Reason</description>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Final payment required</fullName>
            </value>
            <value>
                <fullName>Payment not eligible</fullName>
            </value>
            <value>
                <fullName>Participant Request</fullName>
            </value>
            <value>
                <fullName>Panel Financier Request</fullName>
            </value>
            <value>
                <fullName>Not eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Property</description>
    <label>Property ID</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Property_Valuation_Date__c.field-meta.xml
<CustomField>
    <fullName>Property_Valuation_Date__c</fullName>
    <description>Property Valuation Date</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Property Valuation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEI_OLD__c.field-meta.xml
<CustomField>
    <fullName>SEI_OLD__c</fullName>
    <description>SEI(old)</description>
    <label>SEI (old)</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEM_OLD__c.field-meta.xml
<CustomField>
    <fullName>SEM_OLD__c</fullName>
    <description>SEM(old)</description>
    <label>SEM (old)</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Early_Payment.recordType-meta.xml
<RecordType>
    <fullName>Early_Payment</fullName>
    <active>true</active>
    <businessProcess>Early Payment</businessProcess>
    <label>Early Payment</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/VHF_Application_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>VHF_Application_Record_Type</fullName>
    <active>true</active>
    <businessProcess>VHF Application Support Process</businessProcess>
    <label>VHF Applications</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Primary_Participant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Participant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Participant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <inlineHelpText>Select a cancellation reason</inlineHelpText>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer request</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The property related to the final application once approved and settled</description>
    <label>Property</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Final Applications (Property)</relationshipLabel>
    <relationshipName>Final_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Cancellation/Rejection Comments</inlineHelpText>
    <label>Cancellation/Rejection Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shared_Equity_Interest__c.field-meta.xml
<CustomField>
    <fullName>Shared_Equity_Interest__c</fullName>
    <description>SEI =(SEM/(min(MV,AP)) -(P/LMV) )
SEM = Shared Equity Money
MV – Market value of the property
AP – Initial Acquisition Price
P – Amount to be paid by the applicant . Captured from the Annual Review or Windfall gain notification
LMV – Higher of AP or Market Value of the property (from VGV valuations)</description>
    <label>Shared Equity Interest</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shared_Equity_Money__c.field-meta.xml
<CustomField>
    <fullName>Shared_Equity_Money__c</fullName>
    <description>State&apos;s equity in the Property</description>
    <label>Shared Equity Money</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Stores the payment details that a participant need to make as part of post settlement process</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PID-{00000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Cancellation_Comments__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Comments__c</fullName>
    <description>Updated by SRO Officer</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Cancellation Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <description>Updated by SRO officer</description>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Incorrect Calculation</fullName>
            </value>
            <value>
                <fullName>Payment not Required</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Windfall Gains, Voluntary Payments, Income Threshold Exceeded, Final Payment, Early Payment</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Regenerated__c.field-meta.xml
<CustomField>
    <fullName>Payment_Regenerated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Regenerated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Primary_Participant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Auto-linked when payment record is created</description>
    <label>Primary Participant Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Auto-linked when payment record is created</description>
    <label>Property</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Shared_Equity_Interest__c.field-meta.xml
<CustomField>
    <fullName>Shared_Equity_Interest__c</fullName>
    <formula>Property__r.Shared_Equity_Interest__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shared Equity Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Updated by SRO Officer</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Payment Registered</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Request Expired</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
                <isActive>false</isActive>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Requested</fullName>
                <isActive>false</isActive>
                <label>Requested</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentRegenerationRequestTest.cls
/*******************************************************************************************
* @Name         Payment Regeneration Request Test Class (VHF-2979)
* @Author       Lavanya Kavuri
* @Date         09/12/2021
* @Description  This class is used for Payment Regeneration Request LWC.
*******************************************************************************************/ 
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*  1.0              Lavanya Kavuri     09/12/2021          Created                                                    
*******************************************************************************************/
@isTest
public with sharing class PaymentRegenerationRequestTest {

    private static final Id APP_CASE_RECORDTYPEID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('VHF_Application_Record_Type').getRecordTypeId();
    private static final Id PAYMENT_CASE_RECORDTYPEID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Early_Payment').getRecordTypeId();
    @TestSetup
    static void makeData(){

        UserRole customRole = new UserRole(DeveloperName = 'CustomRole', Name = 'Custom Role');
        insert customRole;

        //Insert Sys Admin Account 
        User adminUser = VHFTestDataFactory.createAdminUser(customRole.Id, 'testadminuser@srotest.com', 'testadminuser@srotest.com'+System.currentTimeMillis(), 'Sroadmin', 'userrec', 'arodsj' );
        insert adminUser;

        System.runAs(adminUser)
        {
            //Lender Account 
            Account bankAccount = VHFTestDataFactory.createLenderAccount('Oz Bank');
            insert bankAccount; 

            //Lender Contact 
            Contact bankLender = VHFTestDataFactory.createLenderContact(bankAccount.Id, 'ozbank', 'lender', 'ozbank.lender@banktest.com', '+61 03 9111 1111');
            insert bankLender; 

            //Applicant Person Account
            Account applicantAcct = VHFTestDataFactory.createApplicantPersonAccount('yes');
            insert applicantAcct;

            //Create Case 
            Case applicantCase = VHFTestDataFactory.createCase(applicantAcct.Id, 'Submitted', 'Pending', APP_CASE_RECORDTYPEID);
            insert applicantCase;

            //Create Reg Auth 
            RegulatoryAuthorizationType regAuth = VHFTestDataFactory.createRegAuth('Victorian Homebuyer Fund', 'License');
            insert regAuth;

            //Individual Application 
            IndividualApplication provApp = VHFTestDataFactory.createProvisionalApplication(regAuth.Id, bankAccount.Id, bankLender.Id, applicantAcct.Id, applicantCase.Id);
            insert provApp;

            //Applicant 
            Applicant__c applicant = VHFTestDataFactory.createApplicant(applicantAcct.Id, provApp.Id);
            insert applicant;

            //Final Application 
            Contract finalApp = VHFTestDataFactory.createFinalApplication(provApp.Id, applicantAcct.Id, 'Draft', applicantCase.Id, 20, '1', '1', '1', 999, bankLender.Id);
            insert finalApp;

            //Property 
            Order property1 = VHFTestDataFactory.createProperty(applicantAcct.Id, 'Draft', bankAccount.Id);
            insert property1;

            //Insert Payment Case 
            Case paymentCase = VHFTestDataFactory.createCase(applicantAcct.Id, 'In progress', 'Pending', PAYMENT_CASE_RECORDTYPEID);
            insert paymentCase;

            //Insert Payment 
            Payment__c paymentRecords = VHFTestDataFactory.createPayment('Created', paymentCase.Id, applicantAcct.Id);
            insert paymentRecords;

        }
    }

    /*
    * Unit Test Method for all Validations Passed Scenario.
    * Assert, Error Message List is Empty.
    */
    @IsTest
    static void validationSuccessTest(){
        
        Order property = [Select Id, Shared_Equity_Interest__c, Shared_Equity_Money__c from Order LIMIT1];
        property.Shared_Equity_Interest__c = 20;
        property.Shared_Equity_Money__c = 200000;
        update property;
        System.debug('Property=' + property);

        Case caseRec = [Select Id, SEI_OLD__c, SEM_OLD__c, Property__c from Case WHERE RecordTypeId =: PAYMENT_CASE_RECORDTYPEID];
        caseRec.SEI_OLD__c = 20;
        caseRec.SEM_OLD__c = 200000;
        caseRec.Property__c = property.Id;
        caseRec.Property_Valuation_Date__c = System.today();
        update caseRec;
        System.debug('Case =' + caseRec);

        Payment__c paymentRec = [Select Id, Property__c, Primary_Participant__c, Cancellation_Comments__c, Cancellation_Reason__c, Case__c, Status__c, Payment_Regenerated__c from Payment__c LIMIT 1];
        paymentRec.Property__c = property.Id;
        paymentRec.Cancellation_Reason__c = 'Other';
        paymentRec.Cancellation_Comments__c = 'Cancelled payment';
        paymentRec.Status__c = 'Cancelled';
        update paymentRec;
        System.debug('Payment=' + paymentRec);

        Test.startTest();
        String response = PaymentRegenerationRequest.validateRequest(paymentRec.Id);
        Map<String,Object> jsonResponse = (Map<String,Object>) JSON.deserializeUntyped(response);
        System.debug('jsonresponse=' + jsonResponse);
        String errorsData = (String)jsonResponse.get('errors');
        System.debug('errors' + errorsData);
        System.debug('errors length' + errorsData.length());
        System.assert(errorsData.length() == 0);
        Test.stopTest();
        
    }

    /*
    * Unit Test Method to validate if a payment regeneration was done for the payment record.
    * Assert, Error Message = Payment has already been regenerated for this Payment Record.
    */
    @IsTest
    static void validationFailureType1Test(){

        Order property = [Select Id, Shared_Equity_Interest__c, Shared_Equity_Money__c from Order LIMIT1];
        property.Shared_Equity_Interest__c = 20;
        property.Shared_Equity_Money__c = 200000;
        update property;
        System.debug('Property=' + property);

        Case caseRec = [Select Id, SEI_OLD__c, SEM_OLD__c, Property__c from Case WHERE RecordTypeId =: PAYMENT_CASE_RECORDTYPEID];
        caseRec.SEI_OLD__c = 20;
        caseRec.SEM_OLD__c = 200000;
        caseRec.Property__c = property.Id;
        caseRec.Property_Valuation_Date__c = System.today();
        update caseRec;
        System.debug('Case =' + caseRec);

        Payment__c paymentRec = [Select Id, Property__c, Case__c, Payment_Regenerated__c from Payment__c LIMIT 1];
        paymentRec.Property__c = property.Id;
        paymentRec.Payment_Regenerated__c = true;
        update paymentRec;
        System.debug('Payment=' + paymentRec);

        Test.startTest();
        try {
          PaymentRegenerationRequest.validateRequest(paymentRec.Id);
        } catch (AuraHandledException e) {
            System.debug(e.getMessage());
            System.debug(e.getTypeName());
            System.assert(e.getMessage().contains('Payment has already been regenerated for this Payment Record.'));
        }

        Test.stopTest();
        
    }

    /*
    * Unit Test Method to validate there are no active payments exists for the property.
    * Assert, Error Message = active payment requests have been completed.
    */
    @IsTest
    static void validationFailureType2Test(){
        
        Order property = [Select Id, Shared_Equity_Interest__c, Shared_Equity_Money__c from Order LIMIT1];
        property.Shared_Equity_Interest__c = 20;
        property.Shared_Equity_Money__c = 200000;
        update property;
        System.debug('Property=' + property);

        Case caseRec = [Select Id, SEI_OLD__c, SEM_OLD__c, Property__c from Case WHERE RecordTypeId =: PAYMENT_CASE_RECORDTYPEID];
        caseRec.SEI_OLD__c = 20;
        caseRec.SEM_OLD__c = 200000;
        caseRec.Property__c = property.Id;
        caseRec.Property_Valuation_Date__c = System.today();
        update caseRec;
        System.debug('Case =' + caseRec);

        Payment__c paymentRec = [Select Id, Property__c, Case__c, Status__c, Payment_Regenerated__c from Payment__c LIMIT 1];
        paymentRec.Property__c = property.Id;
        update paymentRec;
        System.debug('Payment=' + paymentRec);

        Test.startTest();
        String response = PaymentRegenerationRequest.validateRequest(paymentRec.Id);
        Map<String,Object> jsonResponse = (Map<String,Object>) JSON.deserializeUntyped(response);
        System.debug('jsonresponse=' + jsonResponse);
        String errorsData = (String)jsonResponse.get('errors');
        System.debug('errors' + errorsData);
        System.debug('errors length' + errorsData.length());
        String errorMesage; 
        List<Object> errors = (List<Object>) JSON.deserializeUntyped(errorsData);
        for(Object obj: errors)
        {
            errorMesage = (String)obj;
            System.debug(errorMesage);
        }
        System.assert(errorMesage.contains('active payment requests have been completed'));
        Test.stopTest();
        
    }

    /*
    * Unit Test Method to validate SEI and SEM are same in case and property.
    * Assert, Error Message = current SEI matches on the case and property.
    */
    @IsTest
    static void validationFailureType3Test(){
        
        Order property = [Select Id, Shared_Equity_Interest__c, Shared_Equity_Money__c from Order LIMIT1];
        property.Shared_Equity_Interest__c = 10;
        property.Shared_Equity_Money__c = 100000;
        update property;
        System.debug('Property=' + property);

        Case caseRec = [Select Id, SEI_OLD__c, SEM_OLD__c, Property__c from Case WHERE RecordTypeId =: PAYMENT_CASE_RECORDTYPEID];
        caseRec.SEI_OLD__c = 20;
        caseRec.SEM_OLD__c = 200000;
        caseRec.Property__c = property.Id;
        caseRec.Property_Valuation_Date__c = System.today();
        update caseRec;
        System.debug('Case =' + caseRec);

        Payment__c paymentRec = [Select Id, Property__c, Case__c, Cancellation_Reason__c, Cancellation_Comments__c, Status__c, Payment_Regenerated__c from Payment__c LIMIT 1];
        paymentRec.Property__c = property.Id;
        paymentRec.Cancellation_Reason__c = 'Other';
        paymentRec.Cancellation_Comments__c = 'Cancelled payment';
        paymentRec.Status__c = 'Cancelled';
        update paymentRec;
        System.debug('Payment=' + paymentRec);

        Test.startTest();
        String response = PaymentRegenerationRequest.validateRequest(paymentRec.Id);
        Map<String,Object> jsonResponse = (Map<String,Object>) JSON.deserializeUntyped(response);
        System.debug('jsonresponse=' + jsonResponse);
        String errorsData = (String)jsonResponse.get('errors');
        System.debug('errors' + errorsData);
        System.debug('errors length' + errorsData.length());
        String errorMesage; 
        List<Object> errors = (List<Object>) JSON.deserializeUntyped(errorsData);
        for(Object obj: errors)
        {
            errorMesage = (String)obj;
            System.debug(errorMesage);
        }
        System.assert(errorMesage.contains('SEI and SEM has been updated. Create a new case and request payment'));
        Test.stopTest();
        
    }

    /*
    * Unit Test Method to validate if valuation of the property is current.
    * Assert, Error Message = Valuation details are less than 90 days old.
    */
    @IsTest
    static void validationFailureType4Test(){
        
        Order property = [Select Id, Shared_Equity_Interest__c, Shared_Equity_Money__c from Order LIMIT1];
        property.Shared_Equity_Interest__c = 20;
        property.Shared_Equity_Money__c = 200000;
        update property;
        System.debug('Property=' + property);

        Case caseRec = [Select Id, SEI_OLD__c, SEM_OLD__c, Property__c from Case WHERE RecordTypeId =: PAYMENT_CASE_RECORDTYPEID];
        caseRec.SEI_OLD__c = 20;
        caseRec.SEM_OLD__c = 200000;
        caseRec.Property__c = property.Id;
        caseRec.Property_Valuation_Date__c = System.today() - 92;
        update caseRec;
        System.debug('Case =' + caseRec);

        Payment__c paymentRec = [Select Id, Property__c, Cancellation_Comments__c, Cancellation_Reason__c, Case__c, Status__c, Payment_Regenerated__c from Payment__c LIMIT 1];
        paymentRec.Property__c = property.Id;
        paymentRec.Cancellation_Reason__c = 'Other';
        paymentRec.Cancellation_Comments__c = 'Cancelled payment';
        paymentRec.Status__c = 'Cancelled';
        update paymentRec;
        System.debug('Payment=' + paymentRec);

        Test.startTest();
        String response = PaymentRegenerationRequest.validateRequest(paymentRec.Id);
        Map<String,Object> jsonResponse = (Map<String,Object>) JSON.deserializeUntyped(response);
        System.debug('jsonresponse=' + jsonResponse);
        String errorsData = (String)jsonResponse.get('errors');
        System.debug('errors' + errorsData);
        System.debug('errors length' + errorsData.length());
        String errorMesage; 
        List<Object> errors = (List<Object>) JSON.deserializeUntyped(errorsData);
        for(Object obj: errors)
        {
            errorMesage = (String)obj;
            System.debug(errorMesage);
        }
        System.assert(errorMesage.contains('Valuation details are less than 90 days old'));
        Test.stopTest();
        
    }

    /*
    * Unit Test Method to generate a new payment request.
    * Assert, new payment record created.
    */
    @IsTest
    static void createPaymentRequestTest(){
        
        Order property = [Select Id, Shared_Equity_Interest__c, Shared_Equity_Money__c from Order LIMIT1];
        property.Shared_Equity_Interest__c = 20;
        property.Shared_Equity_Money__c = 200000;
        update property;
        System.debug('Property=' + property);

        Case caseRec = [Select Id, SEI_OLD__c, SEM_OLD__c, Property__c from Case WHERE RecordTypeId =: PAYMENT_CASE_RECORDTYPEID];
        caseRec.SEI_OLD__c = 20;
        caseRec.SEM_OLD__c = 200000;
        caseRec.Property__c = property.Id;
        caseRec.Property_Valuation_Date__c = System.today() - 92;
        update caseRec;
        System.debug('Case =' + caseRec);

        Payment__c paymentRec = [Select Id, Property__c, Case__c, Cancellation_Reason__c, Cancellation_Comments__c, Status__c, Payment_Regenerated__c from Payment__c LIMIT 1];
        paymentRec.Property__c = property.Id;
        paymentRec.Cancellation_Reason__c = 'Other';
        paymentRec.Cancellation_Comments__c = 'Cancelled payment';
        paymentRec.Status__c = 'Cancelled';
        update paymentRec;
        System.debug('Payment=' + paymentRec);

        Test.startTest();

        Payment__c newPaymentRec = PaymentRegenerationRequest.createPaymentRequest(paymentRec.Id, 'this is test'); 
        System.assert(newPaymentRec != null);
        
        Test.stopTest();
        
    }


}