force-app/main/default/objects/Account/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The property linked to approved participants in the VHF scheme</description>
    <label>Property</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Actual_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Current_Loan_Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Maturity_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Current loan maturity date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Property</description>
    <label>Property ID</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Refinanced_Loan_Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>Refinanced_Loan_Maturity_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Refinanced Loan Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Refinance.recordType-meta.xml
<RecordType>
    <fullName>Refinance</fullName>
    <active>true</active>
    <businessProcess>Refinance</businessProcess>
    <label>Refinance</label>
</RecordType>

force-app/main/default/objects/Order/fields/Actual_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PopulateEndPaymentDateOnPropertyTest.cls
/*******************************************************************************************
* @Name         PopulateEndPaymentDateOnPropertyTest
* @Author       Pradeep Selvaraj
* @Date         14/04/2022
* @Description  : Test class for PopulateEndPaymentDateOnProperty
*******************************************************************************************/
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*  1.0             Pradeep            13/04/2022          Initial Creation                                 
*******************************************************************************************/

@IsTest
public class PopulateEndPaymentDateOnPropertyTest {
	
    @IsTest
     static void testEndPaymentDatePopulation(){
         
      /*   Account lender = VHFTestDataFactory.createLenderAccount('Commbank');
         insert lender;
         Account a = VHFTestDataFactory.createApplicantPersonAccountWithDetails('Yes','Mike','The Tester','mike@testing101.com');
         a.Is_Participant__pc = true;
         insert a;
         Order property = VHFTestDataFactory.createProperty(String.valueOf(a.id), 'Draft', String.valueOf(lender.id));
         insert property;
         a.Property__c = property.id;
         update a;
         Id refinanceRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Refinance').getRecordTypeId();
         
         Case testCase = VHFTestDataFactory.createCase(String.valueOf(a.id), 'Refinanced - Same PF', 'Completed', String.valueOf(refinanceRecordTypeId));
         insert testCase;
         
         //update case
         testCase.Property__c = property.id ; 
         testCase.Current_Loan_Maturity_Date__c = Date.newInstance(2052, 02, 03);
         testcase.Actual_Settlement_Date__c = Date.newInstance(2022, 01, 02);
         testCase.Refinanced_Loan_Maturity_Date__c = Date.newInstance(2052, 02, 02);
         system.debug(testCase);
         update testCase;
         */
         
         //check if property is updated 
         
     }
}