force-app/main/default/objects/Account/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The property linked to approved participants in the VHF scheme</description>
    <label>Property</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_ins__Email__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/Annual_Review__c.object-meta.xml
<CustomObject>
    <description>Stores the responses to questions that participants to the VHF scheme need to complete on an annual basis</description>
    <label>Annual Review</label>
    <nameField>
        <displayFormat>AR-{0000000000}</displayFormat>
        <label>Annual Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Reviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Review__c/fields/Primary_Participant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Primary participant linked to the annual review</description>
    <label>Primary Participant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annual Reviews</relationshipLabel>
    <relationshipName>Annual_Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Annual Reviews</relationshipLabel>
    <relationshipName>Annual_Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Submission</fullName>
                <default>true</default>
                <label>Awaiting Submission</label>
            </value>
            <value>
                <fullName>Awaiting Verification</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Participant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Participant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Participant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Panel_Financier_Name__c.field-meta.xml
<CustomField>
    <fullName>Panel_Financier_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Panel Financier for which the property is currently being financed by</description>
    <label>Panel Financier Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/updateAnnualReviewTaskTriggerHelperTest.cls
@isTest
public class updateAnnualReviewTaskTriggerHelperTest {
	@IsTest
    private static void testUpdateAnnualReview() {
        
        Account businessAcc = new account(Name='HSBC',type='Investor', vlocity_ins__Email__c='test191@yahoo.com');
        insert businessAcc;
        
        Order property = new order(accountId=businessAcc.id,EffectiveDate=System.today(), Status='Draft', Panel_Financier_Name__c=businessAcc.id);
        insert property;
        
        String recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account acc= new Account(
        RecordTypeID=recordTypeId ,
        FirstName='Test FName',
        LastName='Test LName',
        PersonMailingStreet='test@yahoo.com',
        PersonMailingPostalCode='1234',
        PersonMailingCity='SFO',
        PersonMailingState='Victoria',
        PersonEmail='test@yahoo.com',
        PersonHomePhone='1234567',
        PersonMobilePhone='12345678',
        property__c = property.id,
        Is_Participant__pc = true,
        IsActiveApplicant__pc = 'Yes'
        );
        
        insert acc;
        
        contact con = [select id from contact where accountid =: acc.id limit 1];
        Campaign camp = new Campaign(Name = 'Test11', IsActive = TRUE);            
		insert camp;
        
        CampaignMember member = new CampaignMember(
    	ContactId = con.id,
    	Status = 'Sent',
    	CampaignId = camp.Id
    	);
		insert member;
            
        Annual_review__c annualReview = new Annual_review__c(status__c='Awaiting Verification', Primary_Participant__c=acc.id, Property__c=property.id);
        insert annualReview;
            
        task newTask = new task(status='Open', whatId=annualReview.id);
        insert newTask;
            
        list<task> taskList = [select id, status from task where status = 'Open' limit 1];
        taskList[0].status = 'Completed';
        update taskList;
        
        system.assertEquals('Submitted',[select status__c from Annual_review__c].status__c);
    }

}