force-app/main/default/objects/Account/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The property linked to approved participants in the VHF scheme</description>
    <label>Property</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to support a many to many relationship between a person account and an application.</description>
    <label>Applicant</label>
    <nameField>
        <displayFormat>Applicant - {0000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Property</description>
    <label>Property ID</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEI_new__c.field-meta.xml
<CustomField>
    <fullName>SEI_new__c</fullName>
    <description>SEI(new)</description>
    <label>SEI (new)</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEM_new__c.field-meta.xml
<CustomField>
    <fullName>SEM_new__c</fullName>
    <description>SEM(new)</description>
    <label>SEM (new)</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Final_Early_Payment.recordType-meta.xml
<RecordType>
    <fullName>Final_Early_Payment</fullName>
    <active>true</active>
    <businessProcess>Final%2FEarly Payment</businessProcess>
    <label>Final/Early Payment</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/VHF_Application_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>VHF_Application_Record_Type</fullName>
    <active>true</active>
    <businessProcess>VHF Application Support Process</businessProcess>
    <label>VHF Applications</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The property related to the final application once approved and settled</description>
    <label>Property</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Final Applications (Property)</relationshipLabel>
    <relationshipName>Final_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shared_Equity_Interest__c.field-meta.xml
<CustomField>
    <fullName>Shared_Equity_Interest__c</fullName>
    <description>SEI =(SEM/(min(MV,AP)) -(P/LMV) )
SEM = Shared Equity Money
MV – Market value of the property
AP – Initial Acquisition Price
P – Amount to be paid by the applicant . Captured from the Annual Review or Windfall gain notification
LMV – Higher of AP or Market Value of the property (from VGV valuations)</description>
    <label>Shared Equity Interest</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shared_Equity_Money__c.field-meta.xml
<CustomField>
    <fullName>Shared_Equity_Money__c</fullName>
    <description>State&apos;s equity in the Property</description>
    <label>Shared Equity Money</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Stores the payment details that a participant need to make as part of post settlement process</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PID-{00000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Windfall Gains, Voluntary Payments, Income Threshold Exceeded, Final Payment, Early Payment</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Auto-linked when payment record is created</description>
    <label>Property</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Date__c</fullName>
    <description>Auto-populated when status is updated to payment requested</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Requested Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Shared_Equity_Interest__c.field-meta.xml
<CustomField>
    <fullName>Shared_Equity_Interest__c</fullName>
    <formula>Property__r.Shared_Equity_Interest__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shared Equity Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Updated by SRO Officer</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Payment Registered</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Request Expired</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
                <isActive>false</isActive>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Requested</fullName>
                <isActive>false</isActive>
                <label>Requested</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentNotificationsFlowTest.cls
/*******************************************************************************************
* @Name         PaymentNotificationsFlowTest Class
* @Author       Lavanya Kavuri
* @Date         09/12/2021
* @Description  This is unit test for the Flow: PaymentNotifications
*******************************************************************************************/ 
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*  1.0              Lavanya Kavuri     14/12/2021          Created                                                    
*******************************************************************************************/
@isTest
public with sharing class PaymentNotificationsFlowTest {

    private static final Id APP_CASE_RECORDTYPEID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('VHF_Application_Record_Type').getRecordTypeId();
    private static final Id PAYMENT_CASE_RECORDTYPEID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Final_Early_Payment').getRecordTypeId();
    @TestSetup
    static void makeData(){

        UserRole customRole = new UserRole(DeveloperName = 'CustomRole', Name = 'Custom Role');
        insert customRole;

        //Insert Sys Admin Account 
        User adminUser = VHFTestDataFactory.createAdminUser(customRole.Id, 'testadminuser@srotest.com', 'testadminuser@srotest.com'+System.currentTimeMillis(), 'Sroadmin', 'userrec', 'arodsj' );
        insert adminUser;

        System.runAs(adminUser)
        {
            //Lender Account 
            Account bankAccount = VHFTestDataFactory.createLenderAccount('Oz Bank');
            insert bankAccount; 

            //Lender Contact 
            Contact bankLender = VHFTestDataFactory.createLenderContact(bankAccount.Id, 'ozbank', 'lender', 'ozbank.lender@banktest.com', '+61 03 9111 1111');
            insert bankLender; 

            //Applicant Person Account
            Account applicantAcct = VHFTestDataFactory.createApplicantPersonAccount('yes');
            insert applicantAcct;

            //Create Case 
            Case applicantCase = VHFTestDataFactory.createCase(applicantAcct.Id, 'Submitted', 'Pending', APP_CASE_RECORDTYPEID);
            insert applicantCase;

            //Create Reg Auth 
            RegulatoryAuthorizationType regAuth = VHFTestDataFactory.createRegAuth('Victorian Homebuyer Fund', 'License');
            insert regAuth;

            //Individual Application 
            IndividualApplication provApp = VHFTestDataFactory.createProvisionalApplication(regAuth.Id, bankAccount.Id, bankLender.Id, applicantAcct.Id, applicantCase.Id);
            insert provApp;

            //Applicant 
            Applicant__c applicant = VHFTestDataFactory.createApplicant(applicantAcct.Id, provApp.Id);
            insert applicant;

            //Final Application 
            Contract finalApp = VHFTestDataFactory.createFinalApplication(provApp.Id, applicantAcct.Id, 'Draft', applicantCase.Id, 20, '1', '1', '1', 999, bankLender.Id);
            insert finalApp;

            //Property 
            Order property1 = VHFTestDataFactory.createProperty(applicantAcct.Id, 'Draft', bankAccount.Id);
            insert property1;

            //Insert Payment Case 
            Case paymentCase = VHFTestDataFactory.createCase(applicantAcct.Id, 'In progress', 'Pending', PAYMENT_CASE_RECORDTYPEID);
            insert paymentCase;

            //Insert Payment 
            Payment__c paymentRecords = VHFTestDataFactory.createPayment('Payment Registered', paymentCase.Id, applicantAcct.Id);
            insert paymentRecords;

        }
    }

    

    @IsTest
        static void paymentRegisteredNodeTest(){
            Payment__c payment = [Select Id, Status__c, Requested_Date__c from Payment__c LIMIT 1 ];
            System.debug('Payment Record=' + payment);
            Test.startTest();
            System.assertEquals('Payment Requested', payment.Status__c);
            System.assert(payment.Requested_Date__c != null);
            Test.stopTest();
            
        }
    
        @IsTest
        static void paymentReceivedNodeTest(){

            Order property = [Select Id, Shared_Equity_Interest__c, Shared_Equity_Money__c from Order LIMIT 1];

            Case paymentCase = [Select Id, Property__c, Type from Case Where RecordTypeId =: PAYMENT_CASE_RECORDTYPEID LIMIT 1] ;
            paymentCase.Type = 'Windfall Gain';
            paymentCase.Property__c = property.Id;
            paymentCase.SEI_new__c = 20;
            paymentCase.SEM_new__c = 200000;
            update paymentCase; 
            System.debug('case rec=' + paymentCase);

            Payment__c updatePayment = [Select Id, Status__c, Property__c, Case__c, Property__r.Shared_Equity_Interest__c, Property__r.Shared_Equity_Money__c from Payment__c LIMIT 1 ];
            updatePayment.Status__c = 'Payment Received';
            updatePayment.Case__c = paymentCase.Id;
            updatePayment.Property__c = property.Id;
            update updatePayment;
            System.debug('payment record=' + updatePayment);

            Payment__c paymentRec = [Select Id, Case__c, Property__c, Property__r.Shared_Equity_Interest__c, Property__r.Shared_Equity_Money__c, Status__c from Payment__c where Case__c =: paymentCase.Id ];
            System.debug('updated payment rec=' + paymentRec);
            
            Test.startTest();
            
            System.assertEquals(paymentRec.Property__r.Shared_Equity_Interest__c, paymentCase.SEI_new__c);
            System.assertEquals(paymentRec.Property__r.Shared_Equity_Money__c, paymentCase.SEM_new__c);

            Test.stopTest();
            
        }

        @IsTest
        static void paymentNotReceivedNodeTest(){
            Payment__c payment = [Select Id, Status__c, Requested_Date__c from Payment__c LIMIT 1 ];
            payment.Status__c = 'Payment Requested';
            payment.Requested_Date__c = System.today() - 15;

            EmailMessage emailMsg = new EmailMessage();
            emailMsg.FromAddress = 'no-reply@sro.vic.gov.au';
            emailMsg.FromName = 'State Revenue Office Victoria';
            emailMsg.HtmlBody =  '<h1>This is a test email message</h1>';
            emailMsg.IsTracked = true;
            emailMsg.MessageDate = System.today();
            emailMsg.RelatedToId = payment.Id;
            emailMsg.Status = '3';
            emailMsg.Subject = 'This is atest';
            emailMsg.ToAddress = 'test@testeamil.com';
            insert emailMsg;


            Test.startTest();
            
            EmailMessage emailMesasge = [Select Id, ParentId from EmailMessage where RelatedToId =: payment.Id ];
            System.assert(emailMessage.Id != null);

            Test.stopTest();
            
        }
}