force-app/main/default/objects/Account/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The property linked to approved participants in the VHF scheme</description>
    <label>Property</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Shared_Mailbox__c.field-meta.xml
<CustomField>
    <fullName>Shared_Mailbox__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>VHF-3045 requirements - used to set recipient for email communications with Panel Financiers</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Shared Mailbox</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Actual_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>VHF-1712</description>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Current_Panel_Financier__c.field-meta.xml
<CustomField>
    <fullName>Current_Panel_Financier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Panel Financier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Current Panel Financier)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/New_Panel_Financier__c.field-meta.xml
<CustomField>
    <fullName>New_Panel_Financier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Panel Financier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Refinance(New Panel Financier)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Property</description>
    <label>Property ID</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Property_ID__c.field-meta.xml
<CustomField>
    <fullName>Property_ID__c</fullName>
    <description>Property ID</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Property ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Refinance.recordType-meta.xml
<RecordType>
    <fullName>Refinance</fullName>
    <active>true</active>
    <businessProcess>Refinance</businessProcess>
    <label>Refinance</label>
</RecordType>

force-app/main/default/objects/Confirmation__c/Confirmation__c.object-meta.xml
<CustomObject>
    <label>Refinance Confirmation</label>
    <nameField>
        <displayFormat>CF-{00000000}</displayFormat>
        <label>Confirmation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refinance Confirmations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Confirmation__c/fields/Actual_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Confirmation__c/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Confirmation__c/fields/New_PF__c.field-meta.xml
<CustomField>
    <fullName>New_PF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Panel Financier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Refinance Confirmations (New PF)</relationshipLabel>
    <relationshipName>Confirmations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Confirmation__c/fields/Property_ID__c.field-meta.xml
<CustomField>
    <fullName>Property_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property ID</label>
    <referenceTo>Order</referenceTo>
    <relationshipName>Confirmations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Confirmation__c/fields/Refinance_Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Refinance_Case_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Refinance Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Refinance Confirmations</relationshipLabel>
    <relationshipName>Confirmations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Actual_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Settlement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateCaseHandlerTest.cls
@isTest
public class UpdateCaseHandlerTest {
    @TestSetup
    static void testDataSetup(){

        UserRole newCustomRole = VHFTestDataFactory.createCustomRole('CustomRole', 'CustomRole');
        insert newCustomRole;

        User VlocityCustomActionsTestUser = VHFTestDataFactory.createAdminUser(newCustomRole.Id, 'VlocityCustomActions.Test@test.com', 'VlocityCustomActions.Test@test.com', 'VlocityCustomActions', 'Test', 'vcatest');
        insert VlocityCustomActionsTestUser;
        
        System.runAs(VlocityCustomActionsTestUser){

            Account oBendigoAccount = VHFTestDataFactory.createLenderAccount('Bendigo Bank');
            oBendigoAccount.Shared_Mailbox__c = 'VlocityCustomActionsTest.Bendigo@getnada.com';
            insert oBendigoAccount;

            Account oBankofAustraliaAccount = VHFTestDataFactory.createLenderAccount('Bank of Australia');
            oBankofAustraliaAccount.Shared_Mailbox__c = 'VlocityCustomActionsTest.BankofAustralia@getnada.com';
            insert oBankofAustraliaAccount;

            Account accPerson = VHFTestDataFactory.createApplicantPersonAccountWithDetails('Yes', 'test', 'last', 'emailc@test.com');
            insert accPerson;
            
            Order oProperty = VHFTestDataFactory.createProperty(accPerson.Id, 'Draft', oBendigoAccount.Id);
            oProperty.Actual_Settlement_Date__c = date.Today() - 10;
            insert oProperty;
           
            Id Refinance_RECORDTYPEID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Refinance').getRecordTypeId();
            Case newRefinanceCase = VHFTestDataFactory.createCase(accPerson.Id, 'New', 'Pending', Refinance_RECORDTYPEID);
            newRefinanceCase.Subject = 'Test Refinance case';
            newRefinanceCase.Current_Panel_Financier__c = oBendigoAccount.Id;
            newRefinanceCase.Property__c = oProperty.id; 
            newRefinanceCase.ByPassValidation__c =true;
            newRefinanceCase.New_Panel_Financier__c= oBankofAustraliaAccount.id;
            newRefinanceCase.ContactId = [SELECT PersonContactId FROM Account WHERE Id = :accPerson.Id].PersonContactId;
            insert newRefinanceCase;

            Confirmation__c confirmation = new Confirmation__c();
            confirmation.Refinance_Case_ID__c = newRefinanceCase.Id;
            confirmation.Property_Id__c =  oProperty.id; 
            insert confirmation;

        }
    }

    @isTest
    private static void UpdateNewPanelFinancier_Success(){
        Test.startTest();
        String sNewPanelFinancier = 'Bank of Australia';
        Case oCase_Before = [Select Id from Case LIMIT 1];
        Map<String, Object> input = new Map<String, Object>{'CaseId'=>oCase_Before.Id,'NewPanelFinancier' => 'Bank of Australia'};
        Map<String, Object> output = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        UpdateCaseHandler.UpdateNewPanelFinancier(input, output, options);
        
        Account oAccount = [select Id from Account where Name = :sNewPanelFinancier];
        Case oCase_After = [Select Id, New_Panel_Financier__c from Case where Id = :oCase_Before.Id];
        
        system.assertEquals(oAccount.Id, oCase_After.New_Panel_Financier__c);
        system.assertEquals(true, (Boolean)output.get('success'));
        List<Confirmation__c> CList = [Select Id, New_PF__c From Confirmation__c Where Refinance_Case_ID__c =: oCase_After.Id order by createdDate desc];
        system.assertEquals(CList[0].New_PF__c,oCase_After.New_Panel_Financier__c);
        Test.stopTest();
    }
}