force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to support a many to many relationship between a person account and an application.</description>
    <label>Applicant</label>
    <nameField>
        <displayFormat>Applicant - {0000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>VHF-1712</description>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <description>Cancellation_Reason</description>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Final payment required</fullName>
            </value>
            <value>
                <fullName>Payment not eligible</fullName>
            </value>
            <value>
                <fullName>Participant Request</fullName>
            </value>
            <value>
                <fullName>Panel Financier Request</fullName>
            </value>
            <value>
                <fullName>Not eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Reason__c</fullName>
    <label>Rejection Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invalid absence reason</fullName>
            </value>
            <value>
                <fullName>Not eligible to exit</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <description>sub status specific to victorian homebuyer fund</description>
    <label>Sub Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Notification Sent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/VHF_Application_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>VHF_Application_Record_Type</fullName>
    <active>true</active>
    <businessProcess>VHF Application Support Process</businessProcess>
    <label>VHF Applications</label>
</RecordType>

force-app/main/default/objects/Contract/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <inlineHelpText>Select a cancellation reason</inlineHelpText>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer request</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Reason__c</fullName>
    <label>Rejection Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Property is in an ineligible location</fullName>
            </value>
            <value>
                <fullName>Identification documents were not provided</fullName>
            </value>
            <value>
                <fullName>Discrepancies between application and contract details</fullName>
            </value>
            <value>
                <fullName>Certificate of Occupancy was not provided</fullName>
            </value>
            <value>
                <fullName>Contract of Sale was not provided</fullName>
            </value>
            <value>
                <fullName>Applicant is not an Australian Citizen or PR holder</fullName>
            </value>
            <value>
                <fullName>Applicant deposit contribution is less than 3.5%</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Applicant is not an Australian Citizen</fullName>
                <isActive>false</isActive>
                <label>Applicant is not an Australian Citizen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Cancellation/Rejection Comments</inlineHelpText>
    <label>Cancellation/Rejection Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Final_Application_In_Progress_c__c.field-meta.xml
<CustomField>
    <fullName>Final_Application_In_Progress_c__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final Application in Progress</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Hard_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Hard_Expiry_Date__c</fullName>
    <description>This date holds the final date beyond which no application can or should be extended.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Hard Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Lender_Account__c.field-meta.xml
<CustomField>
    <fullName>Lender_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel Financier Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individual Applications</relationshipLabel>
    <relationshipName>Individual_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Reason__c</fullName>
    <label>Rejection Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applicant owns a property in Victoria</fullName>
            </value>
            <value>
                <fullName>Applicant deposit contribution is less than 3.5%</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IndividualApplication/fields/Second_Extension_Requested__c.field-meta.xml
<CustomField>
    <fullName>Second_Extension_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The second Expiry date extension indicator.</description>
    <label>Second Extension Requested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FinalAppBtnControllerTest.cls
//Added testExtendExpDateBtn - Nayana R - Oct 1st
@IsTest
public with sharing class FinalAppBtnControllerTest {

   
  private static final String PROFILE = 'VHF Lender Community Plus User';
  

  @TestSetup
  private static void setupData(){
    Id vhfApplicationsCaseRT_Id = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('VHF_Application_Record_Type').getRecordTypeId();

    UserRole customRole = VHFTestDataFactory.createCustomRole('CustomRole', 'CustomRole');
    insert customRole;
    
    User userWithARole = VHFTestDataFactory.createAdminUser(customRole.Id, 'testSysAdUser@test.com', 'testSysAdUser@test.com' + System.currentTimeMillis(), 'Role', 'User', 'alias');
    insert userWithARole;
    
    user sysAdUser = [SELECT Id FROM user WHERE Email = 'testSysAdUser@test.com'];
    System.runAs(sysAdUser) 
    {
        Account oOzBankRecord = VHFTestDataFactory.createLenderAccount('Oz Bank');
        insert oOzBankRecord;

        Contact oContact = VHFTestDataFactory.createLenderContact(oOzBankRecord.Id, 'lender', 'officer1', 'lender.Officer1@getnada.com', '+61 2 9311 1111');
        insert oContact;
            
        Profile communityProfile = [SELECT Id FROM profile WHERE Name = :PROFILE Limit 1];
        String nickName = oContact.LastName + '_' + System.currentTimeMillis();
        String alias = string.valueOf(oContact.LastName.substring(0,1) + Math.random() ).substring(0,5);
        User comPortalUser = VHFTestDataFactory.createCommunityUser(oContact.Id, oContact.Email, oContact.LastName, oContact.Email, nickName, alias, communityProfile.Id);
        insert comPortalUser;
            
        Account oApplicantPersonAccountRecord = VHFTestDataFactory.createApplicantPersonAccount('Yes');
        insert oApplicantPersonAccountRecord;

        System.debug('*** Results: ' + oApplicantPersonAccountRecord);

        Case applicationCase = VHFTestDataFactory.createCase(oApplicantPersonAccountRecord.Id, 'In Progress', 'Pending', vhfApplicationsCaseRT_Id);
        insert applicationCase;
        
        RegulatoryAuthorizationType authType = VHFTestDataFactory.createRegAuth('Victorian HomebuyerFund', 'License');
        insert authType;
        
        IndividualApplication oIndividualApplication = VHFTestDataFactory.createProvisionalApplication(authType.Id, oOzBankRecord.Id, oContact.Id, oApplicantPersonAccountRecord.Id,applicationCase.Id );
        insert oIndividualApplication;
        
        Applicant__c oApplicant = VHFTestDataFactory.createApplicant(oApplicantPersonAccountRecord.Id, oIndividualApplication.Id);
        insert oApplicant;

        Contract finalApp = VHFTestDataFactory.createFinalApplication(oIndividualApplication.Id, oApplicantPersonAccountRecord.Id, 'Final Application Submitted', applicationCase.Id, 28, '1', 'PS832324H', '1', 1, oContact.Id);
        insert finalApp;
    }
  }

  @isTest 
  private static void testGetBtnVisibileFalse() {
      Test.startTest();
      IndividualApplication app = [Select Id from IndividualApplication LIMIT 1];
      Boolean result = FinalAppBtnController.getBtnVisibile(app.Id);
      System.assertEquals(false, result);
      Test.stopTest();
  }

  @isTest static void testExtendExpDateBtn()
    {
        Test.startTest();
        Account acc = [Select Id, Name from Account where name = 'Oz Bank'];
        Account applicant = [Select Id, Name from Account where PersonEmail = 'test@email.com.invalid'];
        IndividualApplication app = [Select Id, Status, ByPassValidation__c from IndividualApplication where Lender_Account__c =: acc.Id];
        Case cs = [Select Id, Status, Sub_Status__c from Case where accountId =: applicant.Id];

        app.status = 'Provisionally Approved';
        app.ByPassValidation__c = false;
        update app;
        

        boolean result = FinalAppBtnController.displayButtonForExpiry(app.Id);
        Test.stopTest();
    }

    @isTest static void testGetBtnVisibileTrue()
    {
        Test.startTest();
        Individualapplication app = [Select Id from Individualapplication LIMIT 1];
        app.status = 'Rejected';
        app.Cancellation_Reason__c = 'Customer request';
        app.Rejection_Reason__c = 'Applicant owns a property in Victoria';
        update app;

        boolean result = FinalAppBtnController.getBtnVisibile(app.Id);
        System.assertEquals(false, result);
        Test.stopTest();
    }

    @isTest private static void testExpiry() {
        Test.startTest();
        IndividualApplication app = [Select Id from IndividualApplication LIMIT 1];
        app.status = 'Provisionally Approved';
        app.Hard_Expiry_Date__c = System.today();
        app.Final_Application_In_Progress_c__c = false;
        app.Second_Extension_Requested__c = false;
        update app;

        boolean result = FinalAppBtnController.displayButtonForExpiry(app.Id);
        System.assertEquals(true, result);
    }


}